"""Build CHEATSHEET.html as one self-contained file: the design tokens (site/tokens.css), the data, the
sheet code and styles, the figures and the fonts are all inlined, and links point at the published site. Send the file to anyone; it
works offline, on a desktop and on a phone.

    python coding/build_sheet.py

Run it after any change in coding/, figures/ or site/tokens.css. Never edit CHEATSHEET.html by hand.
"""
import base64, io, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SITE = "https://pranavmishra17.github.io/self-study/"


def read(path):
    return io.open(os.path.join(ROOT, path), encoding="utf-8").read()


def font(family, weight, name):
    data = base64.b64encode(open(os.path.join(ROOT, "fonts", name), "rb").read()).decode()
    return ("@font-face { font-family: '%s'; font-style: normal; font-weight: %d; font-display: swap; "
            "src: url(data:font/woff2;base64,%s) format('woff2'); }" % (family, weight, data))


def script(js):
    # A literal "</script" inside the inlined code would end the tag early.
    return "<script>\n" + js.replace("</script", "<\\/script") + "\n</script>\n"


FONTS = "\n".join([
    font("Atkinson Hyperlegible", 400, "AtkinsonHyperlegible-400-latin.woff2"),
    font("Atkinson Hyperlegible", 700, "AtkinsonHyperlegible-700-latin.woff2"),
    font("JetBrains Mono", 400, "JetBrainsMono-400-latin.woff2"),
])

page = ('<!DOCTYPE html>\n<html lang="en">\n<head>\n<meta charset="utf-8">\n'
        '<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">\n'
        '<title>Coding cheat sheet</title>\n<meta name="theme-color" content="#FBF8F1">\n'
        '<!-- Generated by coding/build_sheet.py from coding/ and figures/. One file: send it as it is. -->\n'
        '<style>\n' + read("site/tokens.css") + '\n' + FONTS + '\n' + read("figures/figures.css") + '\n' + read("coding/sheet.css") +
        '\nbody { margin: 0; background: var(--bg); }\n</style>\n</head>\n<body>\n'
        '<div class="cheat" role="main" aria-label="Coding cheat sheet">\n'
        '  <div class="cs-top"><b>Coding cheat sheet</b><div class="cs-tabs"></div>'
        '<span class="hint">Tap or click a card for examples and variations. F for full screen.</span>'
        '<span class="grow"></span><a href="' + SITE + 'CODING.html" target="_blank" rel="noopener">Full page</a>'
        '<button type="button" class="wide" id="cs-full">Full screen</button></div>\n'
        '  <div class="cs-grid"></div>\n</div>\n'
        + script(read("figures/icons.js")) + script(read("figures/figures.js"))
        + script(read("coding/data.js")) + script(read("coding/sheet.js")) +
        '<script>\n(function () {\n  "use strict";\n'
        '  // "Open on the page" links go to the published coding page.\n'
        '  window.CS.pageBase = "' + SITE + 'CODING.html";\n'
        '  window.CS.mountSheet(document.querySelector(".cheat"));\n'
        '  document.getElementById("cs-full").addEventListener("click", window.CS.fullScreen);\n'
        '  document.addEventListener("keydown", function (e) {\n'
        '    if (!window.CS.popOpen() && (e.key === "f" || e.key === "F")) { window.CS.fullScreen(); }\n'
        '  });\n}());\n</script>\n</body>\n</html>\n')

io.open(os.path.join(ROOT, "CHEATSHEET.html"), "w", encoding="utf-8", newline="\n").write(page)
print("wrote CHEATSHEET.html: %d KB, self-contained" % (len(page.encode()) // 1024))
