"""Stamp the figure files (and the coding page's coding/ files) that the tracker, the system design
guide, CODING.html and CHEATSHEET.html load with a hash of their contents, so a changed file is
never served from a stale browser cache.

    python figures/stamp.py

Run it after any change in figures/. The loop pages are stamped by interviews/build.py;
ALAAP.html is generated by alaap/build.py. Only the ?v= part of each link changes.
"""
import hashlib, io, os, re

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
PAGES = ["index.html", "SYSTEM DESIGN.html", "CODING.html"]   # CHEATSHEET.html is built by coding/build_sheet.py

for page in PAGES:
    path = os.path.join(ROOT, page)
    s = io.open(path, encoding="utf-8", newline="").read()

    def stamp(m):
        d, f = m.group(1), m.group(2)
        p = os.path.join(ROOT, d, f)
        if not os.path.exists(p):
            return m.group(0)
        v = hashlib.sha1(io.open(p, "rb").read()).hexdigest()[:8]
        return '"%s/%s?v=%s"' % (d, f, v)

    out, n = re.subn(r'"(figures|coding)/([a-z-]+\.(?:js|css))(?:\?v=[0-9a-f]+)?"', stamp, s)
    if out != s:
        io.open(path, "w", encoding="utf-8", newline="\n").write(out)
    print("%s: %d links" % (page, n))
