/* Multiple choice for the Audio and speech field: 2 or 3 per topic. Checked by baseline/quiz/check.js. */
BASELINE.quiz("audio", {
  "sampling": [
    { q: "8 kHz phone audio goes into a model trained on 16 kHz, with no resampling. What is the likely result?",
      o: ["The model hears the speech at double speed and can still return confident, wrong text", "The model raises a format error and stops", "Accuracy drops slightly but the words come out right", "The model hears only the frequencies below 2 kHz", "The model resamples the input itself before decoding"],
      a: 0,
      why: "Samples carry no rate label: 8,000 samples read as 16,000 a second play twice as fast. Nothing fails loudly, which is why a rate mismatch is the classic silent bug." },
    { q: "A recording is sampled at 8 kHz. Which sound can it not represent?",
      o: ["A 3 kHz tone", "A 5 kHz hiss", "A 300 Hz vowel", "A 1 kHz beep", "A 100 Hz hum"],
      a: 1,
      why: "Nyquist: a sample rate represents only frequencies below half of itself, here 4 kHz. Anything above folds back as aliasing unless it is filtered out before sampling." },
    { q: "How many bytes is one 20 ms frame of 16 kHz, 16-bit mono PCM?",
      o: ["160", "320", "640", "1,280", "32,000"],
      a: 2,
      why: "16,000 samples/s × 0.02 s = 320 samples; at 2 bytes each that is 640 bytes." }
  ],
  "spectrograms": [
    { q: "Why can't a log-mel spectrogram be played straight back as audio?",
      o: ["Its sample rate is too low for speakers", "The mel filters remove everything above 4 kHz", "Taking the log makes the values negative", "It keeps magnitude but drops phase, so a waveform has to be rebuilt", "It stores frames, and speakers need single samples"],
      a: 3,
      why: "A spectrogram records how strong each frequency is, not its phase. Inventing a plausible phase and detail is the job of a vocoder." },
    { q: "Why do speech systems map the frequency axis onto the mel scale?",
      o: ["To remove phase information", "To make the FFT run faster", "To align audio frames with text tokens", "To raise the sample rate before the model", "Hearing resolves low frequencies finely and high ones coarsely, so the bins follow that"],
      a: 4,
      why: "Mel filters are narrow at low frequencies and wide at high ones, matching how we hear and cutting about 200 FFT bins to 80 or 128 useful values." },
    { q: "30 seconds of 16 kHz audio, 25 ms windows stepping 10 ms, 80 mel filters. What grid does the model see?",
      o: ["About 80 × 3,000", "About 80 × 1,200", "About 201 × 3,000", "About 400 × 160", "About 80 × 480,000"],
      a: 0,
      why: "The 10 ms step sets the frame count: 30 s / 10 ms = 3,000 frames, each reduced to 80 mel values. That is Whisper's input shape." }
  ],
  "codecs": [
    { q: "A voice pipeline converts mu-law to PCM to Opus and back on every hop. What does that cost?",
      o: ["Nothing, since each conversion is lossless", "Quality and a few milliseconds at every decode and re-encode", "Only bandwidth, never quality", "Only CPU, since latency is set by the network", "Accuracy on music, but not on speech"],
      a: 1,
      why: "Lossy codecs lose a little at each re-encode, and each step adds delay. Pick one format per leg and resample once." },
    { q: "Why does G.711 mu-law store its 8-bit samples on a logarithmic curve?",
      o: ["To double the effective sample rate", "To add error correction for packet loss", "To keep quiet sounds precise with few bits", "To stay compatible with Opus", "To remove frequencies above 4 kHz"],
      a: 2,
      why: "A log curve spends more of its 256 levels on small amplitudes, where the ear notices error most, so 8 bits is acceptable for speech." },
    { q: "You build a browser voice app and want good speech at a low bitrate with 20 ms frames. Which codec fits?",
      o: ["16 kHz PCM in WAV", "G.711 A-law", "MP3 at 128 kbit/s", "Opus", "FLAC"],
      a: 3,
      why: "Opus is the WebRTC default: it switches between a speech mode and a music mode, runs from 6 kbit/s up and uses short frames. MP3 and FLAC are file formats, not live codecs." }
  ],
  "signal-processing": [
    { q: "A caller on speakerphone hears the agent, and the agent keeps stopping to answer its own words. What is missing?",
      o: ["Noise suppression", "Automatic gain control", "A high-pass filter", "A larger jitter buffer", "Acoustic echo cancellation"],
      a: 4,
      why: "Echo cancellation learns the echo path from the known outgoing audio and subtracts it. Without it, VAD and ASR treat the agent's own voice as the caller's." },
    { q: "After noise suppression is turned up, ASR starts missing the first syllable of soft words. What is the best explanation?",
      o: ["The suppressor clips quiet word onsets before the model hears them", "The ASR model needs fine-tuning on noisy data", "The sample rate changed when suppression was enabled", "Echo cancellation is fighting the suppressor", "The VAD threshold is too low"],
      a: 0,
      why: "Aggressive suppression attenuates quiet speech along with noise. The errors look like ASR errors, but no model change brings back audio removed upstream." }
  ],
  "vad": [
    { q: "An agent treats 500 ms of VAD silence as the end of the caller's turn. What goes wrong?",
      o: ["Coughs get transcribed as words", "It talks over callers who pause mid-thought", "It cannot hear callers in noisy rooms", "Its replies always come too late", "It doubles the cost of ASR"],
      a: 1,
      why: "VAD detects speech sounds, not finished thoughts. A pause to read a number or to think looks the same as the end of a turn.",
      pair: "vad-vs-endpointing" },
    { q: "Why does a VAD use a higher probability to start speech than to keep it going?",
      o: ["To save CPU on silent frames", "To recognise who is speaking", "To avoid flickering on and off around a single threshold", "To drop bursts shorter than 250 ms", "To make the model run in under a millisecond"],
      a: 2,
      why: "Hysteresis: a high bar resists false starts, and a lower bar stops brief dips inside a sentence from ending it. A minimum length handles short bursts separately." }
  ],
  "asr": [
    { q: "A medical transcription team worries about text that was never said. Which recognizer type is most prone to it?",
      o: ["CTC, because each frame's output is independent", "A transducer, because it streams", "An energy-based recognizer", "An encoder-decoder, because its decoder writes like a language model", "Any model with a Conformer encoder"],
      a: 3,
      why: "An attention decoder can produce fluent text the audio does not support. CTC fails more honestly, with misspellings.",
      pair: "ctc-vs-encoder-decoder" },
    { q: "A CTC model emits `h e l l o` with no blank between the two l's. What text comes out after collapsing?",
      o: ["hello", "hel lo", "hlo", "h e l l o", "helo"],
      a: 4,
      why: "CTC merges repeats before dropping blanks, so `l l` becomes one l. A double letter needs a blank between, `l _ l`." },
    { q: "You need a streaming recognizer whose output conditions on the text it has already emitted. Which design fits?",
      o: ["A transducer (RNN-T)", "Plain CTC", "A full-attention encoder-decoder", "An x-vector encoder", "A Gaussian mixture model"],
      a: 0,
      why: "The transducer adds a prediction network over previous tokens and still streams. CTC treats frames independently; an encoder-decoder wants the whole utterance." }
  ],
  "whisper": [
    { q: "Whisper hears 20 seconds of hold music and outputs a sentence thanking the caller. Why?",
      o: ["Its CTC head mislabels blank frames", "Its decoder is a language model that can invent text on non-speech", "The 30-second window cuts the music off", "Its training data had no music, so it treats music as speech", "Its mel filters remove the music"],
      a: 1,
      why: "Whisper's autoregressive decoder writes plausible text even when nobody is speaking. Production systems put a VAD in front of it." },
    { q: "Why is Whisper a poor fit for low-latency streaming recognition?",
      o: ["It only supports English", "It needs 48 kHz input", "It works on 30-second windows with an autoregressive decoder", "Its encoder has no attention", "It cannot output timestamps"],
      a: 2,
      why: "Fixed 30-second windows and token-by-token decoding add delay. Streaming models use bounded lookahead with CTC or transducer decoders." },
    { q: "How does one Whisper model switch from transcribing Spanish to translating it into English?",
      o: ["A separate translation head is loaded", "The audio is resampled to a different rate", "The encoder is fine-tuned per language pair", "A special task token in the decoder prompt changes", "A text translator runs on the transcript afterwards"],
      a: 3,
      why: "Special tokens steer the decoder: the language, transcribe or translate, and timestamps. Swapping one token changes the task." }
  ],
  "streaming-asr": [
    { q: "Streaming partials read 'I need to read', then 'I need to reschedule'. How should an agent use partials?",
      o: ["Reply as soon as each partial arrives", "Ignore partials entirely", "Treat the first partial as final", "Send each partial to TTS to cut latency", "Start preparing on partials, and commit the reply only on the final"],
      a: 4,
      why: "Partials save hundreds of milliseconds but may change. Prefetching on them is safe; speaking a reply based on them is not." },
    { q: "What does finalization latency measure in a streaming recognizer?",
      o: ["Time from the end of a word to its final text", "Time from call start to the first partial", "Time the LLM takes to produce its first token", "Total time to transcribe a recording", "Delay added by the jitter buffer"],
      a: 0,
      why: "It is the streaming cost that sits beside WER: how long after a word ends before its text stops changing." }
  ],
  "speaker-diarization": [
    { q: "The same customer calls once from a phone and once from a studio mic, and the system treats them as two people. Why?",
      o: ["The clustering used too few segments", "Speaker embeddings capture the channel as well as the voice", "Diarization cannot compare two separate calls", "Verification is scored by character error rate", "Overlapping speech confused the model"],
      a: 1,
      why: "Embeddings encode the microphone and line along with the voice, so a channel change moves the vector." },
    { q: "What separates speaker verification from diarization?",
      o: ["Verification clusters segments; diarization compares two embeddings", "Both need every speaker enrolled in advance", "Verification checks one claimed voice; diarization finds who spoke when, with speakers unknown", "Diarization transcribes the words; verification does not", "They are two names for the same task"],
      a: 2,
      why: "Verification compares two embeddings against a threshold. Diarization segments, embeds and clusters without knowing the speakers in advance.",
      pair: "verification-vs-diarization" },
    { q: "Where do diarization systems still lose most of their errors?",
      o: ["Long silences", "Single-speaker recordings", "Very short calls", "Overlapping speech", "Recordings at 16 kHz"],
      a: 3,
      why: "When two people talk at once, a segment holds two voices and its embedding fits neither cluster cleanly." }
  ],
  "tts": [
    { q: "A TTS voice reads '3/4' as 'three slash four' in an appointment reminder. Which stage failed?",
      o: ["The vocoder", "The acoustic model", "The neural codec", "The jitter buffer", "The text normalization front end"],
      a: 4,
      why: "The front end turns numbers, dates and abbreviations into words. Many agent teams normalize the LLM's output before TTS sees it." },
    { q: "For a voice agent, which TTS number matters most?",
      o: ["Time to first audio", "Total synthesis time for the reply", "Model parameter count", "Output sample rate", "Number of voices offered"],
      a: 0,
      why: "The caller waits for the first sound. A model that needs the whole sentence before it speaks adds that delay to every turn." }
  ],
  "vocoders": [
    { q: "A fine-tuned TTS voice sounds buzzy and metallic, while its pitch and timing are fine. What is the cheapest likely fix?",
      o: ["Retrain the acoustic model from scratch", "Fine-tune the vocoder on audio like the target voice", "Raise the mel filter count to 256", "Switch to WaveNet for speed", "Add noise suppression after synthesis"],
      a: 1,
      why: "Buzz and hiss usually come from a vocoder that saw too little audio like the target. Pitch and timing are the acoustic model's job, and those are fine." },
    { q: "Why did GAN vocoders such as HiFi-GAN replace WaveNet for real-time use?",
      o: ["They need no training data", "They keep the phase stored in the spectrogram", "They generate all samples in parallel instead of one at a time", "They output text as well as audio", "They work only at 8 kHz"],
      a: 2,
      why: "WaveNet generated sample by sample and was far too slow. GAN vocoders generate in parallel, trained against discriminators that judge the waveform." }
  ],
  "neural-codecs": [
    { q: "In residual vector quantization, what happens when you keep fewer codebooks?",
      o: ["The frame rate drops", "Sequences get longer", "The coarse content goes first", "Bitrate falls and fine detail goes, while coarse content stays", "The codec falls back to mu-law"],
      a: 3,
      why: "Each codebook encodes what the earlier ones missed, so early codebooks carry content and later ones carry detail." },
    { q: "Why does a lower codec frame rate help a TTS language model?",
      o: ["It raises audio quality", "It removes the need for a decoder", "It improves speaker similarity", "It adds more codebooks per frame", "It shortens the token sequence, at the cost of fine timing"],
      a: 4,
      why: "Fewer frames a second means fewer tokens to generate, which suits a transformer. The lost timing detail caps the quality of everything generated through it." },
    { q: "EnCodec runs at 75 frames a second with 8 codebooks of 1,024 entries. How many tokens a second must a TTS model predict?",
      o: ["600", "75", "1,024", "6,000", "8"],
      a: 0,
      why: "75 frames × 8 codebooks = 600 tokens. Each token is 10 bits, so 6,000 is the bitrate in bits, not the token count." }
  ],
  "voice-cloning": [
    { q: "A zero-shot clone made from a 6-second clip recorded in a car comes out with road hum. What is the fix?",
      o: ["Fine-tune the vocoder on car audio", "Record the reference clip in a quiet room", "Raise the TTS sample rate", "Use a longer text prompt", "Add a speaker embedding on top"],
      a: 1,
      why: "Codec language models continue the prompt's acoustics, noise included. A clean reference gives a clean clone with no model change." },
    { q: "What does cheap zero-shot voice cloning mean for a bank's phone line?",
      o: ["Voice biometrics become stronger", "Only fine-tuned clones are a risk", "A voice alone is now weak proof of identity", "Calls must move to WebRTC", "Diarization can replace verification"],
      a: 2,
      why: "A few seconds of someone's speech can produce a convincing clone, so a voice should be one factor among others, never a password." }
  ],
  "speech-to-speech": [
    { q: "A regulated insurer picks a cascade over a speech-to-speech model. Which reason is strongest?",
      o: ["Cascades hear tone and hesitation better", "Cascades always have lower latency", "Speech-to-speech models cannot be interrupted", "A cascade leaves a transcript and an LLM call to inspect before it speaks", "Speech-to-speech models need 8 kHz audio"],
      a: 3,
      why: "Speech-to-speech gives up the text step, so there is nothing to check before it speaks, and tool calling is weaker. Cascades win on control.",
      pair: "cascade-vs-speech-to-speech" },
    { q: "What can a full-duplex model do that a turn-based one cannot?",
      o: ["Run without a GPU", "Transcribe with lower WER", "Call tools more reliably", "Clone a voice from 3 seconds", "Listen while talking, backchannel and be interrupted naturally"],
      a: 4,
      why: "Full-duplex models treat the user's and the assistant's audio as two parallel streams, so speaking and listening overlap." }
  ],
  "voice-agent-pipeline": [
    { q: "In a cascaded voice agent, when should the LLM's first sentence go to TTS?",
      o: ["As soon as it is written, before the rest of the reply", "After the whole reply is generated", "After any tool call returns", "After ASR confirms the reply", "When the caller's next turn starts"],
      a: 0,
      why: "Every stage streams, so audio reaches the caller while later sentences are still being written. Waiting for the whole reply adds its full generation time." },
    { q: "A team wants a cascade to feel instant while still reasoning carefully and calling tools. What pattern fits?",
      o: ["Replace ASR with a bigger model", "Run a small fast model to talk and a larger one to think in parallel", "Remove the turn detector", "Turn off streaming to avoid partial errors", "Spread services across regions"],
      a: 1,
      why: "A fast model carries the conversation, including filler while tools run, while the larger model works. The cascade keeps its control and gains speed." }
  ],
  "telephony-webrtc": [
    { q: "On a lossy mobile network, why does audio over a TCP WebSocket stall where WebRTC only glitches?",
      o: ["TCP uses a lower sample rate", "WebRTC sends every packet twice", "TCP holds every later packet until the lost one is resent", "WebSockets cannot carry Opus", "WebRTC has no jitter buffer"],
      a: 2,
      why: "TCP delivers in order, so one loss blocks everything behind it. WebRTC runs over UDP, skips the lost packet and the decoder conceals the gap.",
      pair: "tcp-vs-udp-audio" },
    { q: "Audio arriving from a phone provider over a WebSocket is typically in which form?",
      o: ["48 kHz Opus", "16 kHz 16-bit PCM", "44.1 kHz WAV", "8 kHz mu-law", "24 kHz codec tokens"],
      a: 3,
      why: "The public phone network is narrowband G.711, so a 16 kHz model needs it decoded and resampled first." }
  ],
  "turn-taking": [
    { q: "A caller cuts the agent off halfway through a sentence. What belongs in the conversation history?",
      o: ["The full sentence the LLM generated", "Nothing from that agent turn", "Only the caller's words, marked as an interruption", "A summary of the full sentence", "Only the part of the sentence the caller actually heard"],
      a: 4,
      why: "Otherwise the agent later refers to something the caller never heard. Truncate the history at the barge-in point." },
    { q: "A caller says 'my number is 4 1 5' and pauses to read the rest. Which approach avoids answering half a number?",
      o: ["A semantic turn detector that reads the transcript", "A shorter silence threshold", "A higher VAD threshold", "Faster barge-in handling", "Counting backchannels as interruptions"],
      a: 0,
      why: "A fixed silence rule cannot tell a pause from an ending. A semantic model sees the number is unfinished, while a plain 'yes' still ends the turn at once." },
    { q: "The caller says 'right' while the agent is talking. What should the agent do?",
      o: ["Stop speaking and cancel TTS", "Keep talking, since it is a backchannel", "Restart the sentence from the beginning", "Hand off to a human", "End its turn and wait"],
      a: 1,
      why: "Backchannels signal listening, not a wish to speak. Counting them as barge-in makes the agent stop all the time." }
  ],
  "latency-budget": [
    { q: "A p95 budget: endpointing 400 ms, LLM first token 350, TTS first byte 150, ASR final 100, network 80. Where is the cheapest big saving?",
      o: ["A faster LLM", "A faster TTS provider", "A semantic turn model that safely shortens endpointing", "A more accurate ASR", "Harder audio compression"],
      a: 2,
      why: "Endpointing is the largest item and it is a setting, not a model. Cutting it safely saves more than any model upgrade." },
    { q: "What is voice-to-voice latency?",
      o: ["The LLM's time to first token", "The network round trip", "The length of the agent's reply", "From the end of the user's speech to the first audio they hear back", "From call start to the greeting"],
      a: 3,
      why: "It sums every stage: network, endpointing, ASR, LLM, TTS and buffers. Budget each one at p95." },
    { q: "Why budget voice latency at p95 rather than the mean?",
      o: ["The mean is harder to compute", "p95 is always lower than the mean", "Providers only publish p95", "The mean leaves out network time", "Callers remember the slow turns, and the mean hides them"],
      a: 4,
      why: "A mean of 900 ms can hide one turn in twenty taking 2 seconds, and that is the turn a caller notices." }
  ],
  "evaluation": [
    { q: "Two ASR vendors report 6% and 9% WER on different test sets with different text normalizers. What can you conclude?",
      o: ["Very little, until both are scored on the same audio with one normalizer", "The 6% vendor is better", "The 9% vendor handles noise better", "Anything above 5% WER is unusable", "Their character error rates will match"],
      a: 0,
      why: "Normalization alone (case, punctuation, 'ten' against '10') moves WER by points. Compare on your own audio under one normalizer." },
    { q: "A model has low WER on LibriSpeech, but your agent keeps getting customer names wrong. What should you measure?",
      o: ["MOS on your own audio", "Entity accuracy on names and numbers in your own calls", "WER on a larger public set", "Real-time factor", "Character error rate on LibriSpeech"],
      a: 1,
      why: "Names, numbers and domain terms carry most of the meaning and most of the errors, and an average WER hides them." },
    { q: "Can word error rate go above 100%?",
      o: ["No, it is a share of words recognized", "Only for languages without spaces", "Yes, because insertions count and can outnumber the reference words", "Only when the audio is silent", "Only when scored with MOS"],
      a: 2,
      why: "WER is (substitutions + deletions + insertions) / reference word count, so a hypothesis full of extra words can pass 100%." }
  ]
});
