/* Multiple choice for the Backend field: 2 or 3 per topic. Checked by baseline/quiz/check.js. */
BASELINE.quiz("backend", {
  "load-balancing": [
    { q: "Some requests call an LLM and take 5 s; others read a cache and take 5 ms. Which balancing algorithm spreads load best?",
      o: ["Round robin", "Least outstanding requests", "Random with equal weights", "Hashing by client IP", "Sticky sessions by cookie"],
      a: 1,
      why: "Round robin assumes every request costs the same. Least outstanding requests sends work to whichever server is least busy right now." },
    { q: "After a deploy, users pinned by sticky sessions are logged out. What is the root cause?",
      o: ["The TLS certificate rotated", "The health check failed", "Layer 4 balancing dropped the cookies",
          "Session state lived on the server; keep it in a shared store", "Round robin reset every session"],
      a: 3,
      why: "Sticky sessions make each server stateful, so a deploy or crash loses its users. A shared store lets any server take any request." },
    { q: "What can a layer 7 load balancer do that a layer 4 one cannot?",
      o: ["Route by URL path or header", "Forward TCP connections", "Spread load across servers", "Take an unhealthy server out", "Listen on one address"],
      a: 0,
      why: "Layer 7 parses HTTP, so it can route on its contents, terminate TLS and retry idempotent requests. Layer 4 forwards connections without reading them.",
      pair: "layer4-vs-layer7" }
  ],
  "rest": [
    { q: "A client times out on `POST /charges`. Why can it not retry as freely as it could a `PUT`?",
      o: ["POST responses are never cached", "POST is safe but not idempotent", "POST is neither safe nor idempotent, so a retry may charge twice",
          "POST requests cannot carry JSON bodies", "Proxies forbid retrying POST"],
      a: 2,
      why: "`PUT` and `DELETE` are idempotent, so retries are safe. A `POST` that creates something needs an idempotency key to be retried." },
    { q: "An API is JSON over HTTP with no hypermedia links, and a reviewer says it is not 'real REST'. What matters more?",
      o: ["Adding hypermedia links to every response", "Switching the payloads to XML", "Using only `GET` and `POST`",
          "Putting verbs in the URL paths", "Correct status codes, safe retries and stable versioning"],
      a: 4,
      why: "Most APIs called REST are HTTP plus JSON, and that is fine. Meaningful status codes, retry safety and versioning are what clients feel." }
  ],
  "grpc-graphql": [
    { q: "Which fits calls between your own backend services best?",
      o: ["gRPC with typed clients generated from `.proto` files", "GraphQL with one public endpoint", "REST with hand-written clients and no schema",
          "Webhooks for every call", "Server-sent events"],
      a: 0,
      why: "gRPC gives small, fast messages and contracts that break at compile time. Browsers need a proxy for it, which matters less inside your own system.",
      pair: "grpc-vs-graphql" },
    { q: "A GraphQL query for 50 posts and their authors fires 51 database queries. What is the standard fix?",
      o: ["Cache every resolver result forever", "Switch the API to gRPC", "Add query depth limits",
          "Batch the author lookups with a loader such as DataLoader", "Send the query with `GET` instead of `POST`"],
      a: 3,
      why: "Naive resolvers fetch each related object separately. A batching layer collects the ids and loads them in one query." },
    { q: "Why does a public GraphQL API need depth and cost limits?",
      o: ["GraphQL has no schema to check against", "The client decides the query's shape, so one query can be very expensive",
          "GraphQL cannot run over HTTPS", "Resolvers run in the client's browser", "Deep queries return XML"],
      a: 1,
      why: "GraphQL hands query cost to the client. Without limits, one nested query can fan out into thousands of fetches.",
      pair: "grpc-vs-graphql" }
  ],
  "webhooks": [
    { q: "A webhook handler charges a card inline and takes 40 s; the provider times out and retries. What happens, and what is the fix?",
      o: ["Nothing, since providers do not retry", "The retry fails the signature check", "The work runs twice; acknowledge, enqueue, then process idempotently",
          "The provider cancels the event", "Return 500 so the provider stops retrying"],
      a: 2,
      why: "A handler that times out gets the event again. Return 2xx fast, do the work from a queue, and skip event ids already processed." },
    { q: "How should a receiver verify that a webhook came from the provider?",
      o: ["Check the sender's IP address only", "Trust the `User-Agent` header", "Compare the payload to the previous event",
          "Ask the provider to log in with basic auth", "Check an HMAC over the raw body, plus a timestamp"],
      a: 4,
      why: "The HMAC with a shared secret proves the sender; the timestamp stops an old request being replayed." },
    { q: "Webhook events arrive out of order, and some arrive twice. What should handlers do?",
      o: ["Record processed event ids, treat repeats as no-ops, and not rely on order", "Reject any event older than the last one",
          "Process only the first event each minute", "Ask the provider for ordered delivery", "Return a 4xx for duplicates"],
      a: 0,
      why: "Delivery is at least once and unordered. Idempotent handlers make repeats harmless." }
  ],
  "realtime": [
    { q: "A dashboard needs one-way updates from the server and should reconnect and resume on its own. Which fits?",
      o: ["WebSockets", "Server-sent events with `EventSource`", "Polling every 100 ms", "gRPC called from the browser", "Webhooks"],
      a: 1,
      why: "SSE streams events down one HTTP response, and `EventSource` reconnects and resumes from the last event id. WebSockets suit two-way traffic.",
      pair: "sse-vs-websockets" },
    { q: "Users with several tabs open find their SSE streams stall over HTTP/1.1. Why?",
      o: ["SSE needs WebSockets underneath", "`EventSource` buffers every event", "The server allows one stream per user",
          "Browsers allow six connections per domain on HTTP/1.1, shared across tabs", "HTTP/1.1 cannot stream responses"],
      a: 3,
      why: "Each open stream uses one of the six slots. HTTP/2 multiplexes streams over one connection and removes the limit." },
    { q: "Ten servers hold WebSocket connections. How does a message reach a user connected to server 7?",
      o: ["Through pub/sub, such as Redis, that every server listens to", "Through the load balancer's sticky table",
          "By broadcasting over UDP", "By server 1 opening its own socket to the user", "By polling the database every second"],
      a: 0,
      why: "The sender does not know which server holds the user. A shared pub/sub channel lets the right server deliver it." }
  ],
  "sessions-tokens": [
    { q: "A JWT's payload contains the user's email. Who can read it?",
      o: ["Only the server holding the signing key", "Nobody, since the signature encrypts it", "Anyone holding the token, since it is signed, not encrypted",
          "Only the browser that received it", "Only services that hold the public key"],
      a: 2,
      why: "The signature proves the payload was not changed; it hides nothing. Never put secrets in a JWT." },
    { q: "An admin must log a user out of every device immediately. Which design supports that?",
      o: ["Long-lived JWTs with no server store", "JWTs kept in `localStorage`", "Unsigned cookies holding the user id",
          "A JWT with a 30-day expiry", "Server-side sessions, or short access tokens with a revocable refresh token"],
      a: 4,
      why: "A signed token cannot be revoked before it expires. Deleting a session row, or refusing the refresh token, ends access.",
      pair: "session-vs-jwt" },
    { q: "Why prefer an `HttpOnly` cookie over `localStorage` for holding a token?",
      o: ["Cookies are encrypted by default", "Scripts cannot read it, so an XSS bug cannot steal it", "`localStorage` is cleared on each page load",
          "Cookies never expire", "`localStorage` is not sent over HTTPS"],
      a: 1,
      why: "Any script on the page can read `localStorage`. An `HttpOnly` cookie is sent by the browser but invisible to scripts." }
  ],
  "oauth": [
    { q: "An app treats any valid access token from a provider as proof of who the user is. What is the problem?",
      o: ["Access tokens expire too quickly", "Access tokens are encrypted", "Scopes cannot be checked",
          "OAuth grants access, not identity; identity needs an OpenID Connect ID token", "The token must be refreshed first"],
      a: 3,
      why: "An access token says what an app may do, not who the user is. OpenID Connect exists to fix exactly this bug.",
      pair: "oauth-vs-oidc" },
    { q: "What does PKCE protect in the OAuth flow?",
      o: ["The code exchange, binding it to the app that started the flow", "The user's password at the provider",
          "The signature on the ID token", "Where the refresh token is stored", "The list of approved scopes"],
      a: 0,
      why: "PKCE ties the code exchange to a secret the starting app made, so a stolen code is useless to anyone else." },
    { q: "A nightly job calls another service's API with no user involved. Which grant fits?",
      o: ["Authorization code with PKCE", "Implicit grant", "Client credentials", "Password grant", "Device code"],
      a: 2,
      why: "Client credentials is for machine to machine calls, leaving the user out. The implicit and password grants are dropped in OAuth 2.1." }
  ],
  "authorization": [
    { q: "An API returns `/invoices/1234` to any logged-in user who guesses the id. What is this?",
      o: ["Cross-site scripting", "A weak password policy", "SQL injection", "A missing rate limit", "Broken object level authorization"],
      a: 4,
      why: "Authentication passed, but nobody checked that this user may see this object. It is first in the OWASP API Security Top 10." },
    { q: "'You may edit this document because your team owns its folder.' Which model is that?",
      o: ["RBAC", "ReBAC", "ABAC", "IP allow lists", "OAuth scopes"],
      a: 1,
      why: "Access follows relationships in a graph (team owns folder, folder holds doc), which is relationship-based access control.",
      pair: "rbac-vs-rebac" },
    { q: "Access checks exist only in the React UI. What is true?",
      o: ["It is safe, since users cannot edit the UI", "It is safe if the API uses TLS", "It is safe if roles are cached",
          "There is no check: anyone can call the API directly", "It is safe behind a CDN"],
      a: 3,
      why: "A check only in the UI is no check. Enforce it on the server, ideally in one central policy." }
  ],
  "orms": [
    { q: "Loading 50 orders, then touching each order's customer, fires 51 queries. What fixes it?",
      o: ["Eager loading: a `JOIN`, or a second query with `IN`", "An index on `orders.id`", "A larger connection pool",
          "Caching each customer for a day", "Serializable isolation"],
      a: 0,
      why: "That is the N+1 query. Eager loading fetches all customers in one or two queries instead of fifty." },
    { q: "What habit best catches ORM performance problems early?",
      o: ["Add indexes only once in production", "Write raw SQL for everything", "Log queries in development and count them per request",
          "Run the ORM in a separate service", "Ban joins in all queries"],
      a: 2,
      why: "The ORM hides the moment you needed SQL and indexes. Counting queries per request shows it before users do." }
  ],
  "connection-pools": [
    { q: "Why keep a Postgres connection pool small, starting near twice the database's CPU cores?",
      o: ["Postgres accepts at most 16 connections", "Large pools leak memory in the app", "Small pools make TLS faster",
          "Drivers do not support larger pools", "Postgres handles many active connections poorly"],
      a: 4,
      why: "Each connection is a server process, and hundreds of active ones contend for CPU and locks. A small pool keeps the database efficient." },
    { q: "After adding PgBouncer in transaction mode, `LISTEN` stops working and advisory locks misbehave. Why?",
      o: ["PgBouncer drops idle connections", "Session state does not carry over, since each transaction may get a different server connection",
          "Transaction mode turns off MVCC", "PgBouncer forbids `SELECT ... FOR UPDATE`", "The pool is too small"],
      a: 1,
      why: "In transaction mode a server connection is held only for one transaction, so anything tied to the session breaks." },
    { q: "Each Lambda instance opens its own Postgres connection, with no proxy. What happens at a traffic spike?",
      o: ["Lambda shares one connection across instances", "Postgres queues them all without trouble", "Each connection gets faster",
          "The database runs out of connections", "Lambda switches to HTTP on its own"],
      a: 3,
      why: "Hundreds of instances mean hundreds of connections. An external pooler such as PgBouncer multiplexes them." }
  ],
  "migrations": [
    { q: "How do you rename a column with no downtime?",
      o: ["Expand and contract: add new, write both, backfill, move reads, drop old later", "Rename it in place during a quiet hour",
          "Drop and recreate the table", "Run a down migration first", "Rename it and deploy the new code at the same moment"],
      a: 0,
      why: "Old and new code run against one database during a deploy, so every step must work with both." },
    { q: "A migration builds an index on a busy Postgres table without `CONCURRENTLY`. What happens?",
      o: ["Reads block but writes continue", "Nothing, since index builds are always online", "Writes to the table block for the whole build",
          "The index is built on a replica", "The table is copied to a new file"],
      a: 2,
      why: "A plain index build holds a lock that blocks writes until it finishes. `CREATE INDEX CONCURRENTLY` avoids it." },
    { q: "A bad release ships. What usually keeps a team safe with schema migrations?",
      o: ["Running the down migration in production", "Restoring last night's backup", "Freezing the schema during deploys",
          "Skipping migrations for hotfixes", "Each step is backward compatible, so the previous release still runs"],
      a: 4,
      why: "Down migrations are rarely trusted; teams roll forward. Backward-compatible steps let you roll the code back without touching the schema." }
  ],
  "caching": [
    { q: "The code deletes the cache key on every write, yet stale values still appear. How?",
      o: ["Redis ignores deletes under load", "A concurrent reader fetched the old value and writes it back after the delete",
          "TTLs override deletes", "The CDN puts the key back", "Deletes apply only once an hour"],
      a: 1,
      why: "A reader that missed before the write can fill the cache after the delete with what it read. Short TTLs or versioned keys bound the damage." },
    { q: "The service fails whenever Redis is down, because the database cannot handle the full read load. What has the cache become?",
      o: ["A write-through cache", "A CDN", "A read replica", "A database with no durability", "A message queue"],
      a: 3,
      why: "A cache the system cannot run without is no longer a cache. Know what load the database sees when the cache is empty." }
  ],
  "queues-workers": [
    { q: "A worker dies halfway through a job. What does a typical queue do?",
      o: ["Makes the job visible again after a timeout, for another worker", "Loses the job permanently",
          "Blocks until that worker restarts", "Marks the job as done", "Asks the producer to resend it"],
      a: 0,
      why: "Unacknowledged jobs return after the visibility timeout. That is also why jobs sometimes run twice." },
    { q: "A job fails every time on bad input and is retried forever. What is missing?",
      o: ["A bigger worker pool", "A longer visibility timeout", "A dead-letter queue after a retry limit", "Exactly-once delivery", "A faster broker"],
      a: 2,
      why: "A job that always fails needs to be set aside for a human, not retried endlessly." },
    { q: "Why use `SELECT ... FOR UPDATE SKIP LOCKED` for a job queue in Postgres?",
      o: ["It makes each job run exactly once", "It locks the whole table for safety", "It sorts the jobs by priority",
          "It turns off MVCC for speed", "Many workers claim different rows without blocking each other"],
      a: 4,
      why: "Each worker locks the row it takes and skips rows others hold, and the job can commit in the same transaction as its data." }
  ],
  "idempotency": [
    { q: "A server charges a card, then records the idempotency key in a separate step, and crashes in between. What happens on retry?",
      o: ["The retry returns the stored result", "The card is charged again, since the key was never recorded",
          "The provider rejects the retry", "The retry waits in a queue", "Nothing, since the key is optional"],
      a: 1,
      why: "The key, the lock and the effect belong in one transaction. An external call made inside needs its own key." },
    { q: "Who generates an idempotency key, and when?",
      o: ["The server, once per attempt", "The database, once per row", "The load balancer, once per connection",
          "The client, once per logical operation, reused on every retry", "The client, freshly on every retry"],
      a: 3,
      why: "The key names the operation, not the attempt. A new key per retry would make each retry look like a new charge." }
  ],
  "timeouts-retries": [
    { q: "A dependency slows down, and every client retries three times at once. What follows?",
      o: ["A retry storm that keeps the dependency down", "Faster recovery, since more requests get through", "No change in load",
          "Lower latency for every caller", "Circuit breakers open on their own"],
      a: 0,
      why: "Retries multiply load on something already struggling. Fewer, slower retries with a budget recover faster." },
    { q: "Why add jitter to exponential backoff?",
      o: ["To make retries faster", "To make retrying non-idempotent calls safe", "To spread retries so clients do not retry in lockstep",
          "To shorten timeout values", "To bypass the circuit breaker"],
      a: 2,
      why: "Without randomness, clients that failed together retry together and hit the dependency in waves." },
    { q: "Where should a call's timeout usually sit?",
      o: ["At ten times the mean latency", "At the p50 latency", "Unset, so slow calls can finish", "At exactly the mean latency",
          "A little above the dependency's p99 latency"],
      a: 4,
      why: "Above p99, normal slow calls succeed; much higher, a stuck dependency holds threads and connections until the service stalls." }
  ],
  "rate-limiting": [
    { q: "Why can a fixed-window limit of 100 per minute let close to 200 requests through in one minute?",
      o: ["Clocks drift between servers", "A burst at the end of one window and the start of the next both pass", "Tokens refill too fast",
          "Redis counters are not atomic", "Clients ignore `Retry-After`"],
      a: 1,
      why: "Each window counts on its own, so a burst straddling the boundary gets two full allowances. Sliding windows fix it." },
    { q: "An API limits by IP, and a whole company behind one office NAT gets 429s. What is better?",
      o: ["Raise the IP limit tenfold", "Exempt that IP", "Limit by user agent",
          "Limit by the key that matches what you protect, such as API key or tenant", "Switch to fixed windows"],
      a: 3,
      why: "IP limits punish shared addresses and miss attackers with many addresses. Choose the key that matches the resource." }
  ],
  "serverless-edge": [
    { q: "A voice agent streams LLM output over WebSockets for minutes at a time. Where should it run?",
      o: ["As a long-lived service in containers", "As a Lambda invocation per message", "As edge functions in V8 isolates",
          "As a scheduled cron job", "As static files on a CDN"],
      a: 0,
      why: "Serverless suits short, spiky, stateless work. Long streams, WebSockets and connection pools need a process that stays up." },
    { q: "An edge function starts in milliseconds near the user, but responses are still slow. What is a common cause?",
      o: ["V8 isolates run code slowly", "Edge functions cannot use HTTPS", "The database sits in one region, so each query travels far",
          "Edge functions are capped at 15 minutes", "Cold starts take over a second"],
      a: 2,
      why: "The function is near the user, but the data is not. Every query crosses the distance the edge was meant to save." }
  ],
  "monolith-microservices": [
    { q: "A team of six splits its app into an auth service, a database service and an API service. What is the likely result?",
      o: ["Independent scaling at no new cost", "Simpler transactions across data", "Faster deploys with less coordination",
          "Fewer network failures", "The costs of both, since parts that change together are now split"],
      a: 4,
      why: "Splitting by technical layer gives network calls and lost transactions without independent change. Split along business boundaries, if at all." },
    { q: "What does a modular monolith give you?",
      o: ["Independent deploys for each team", "Enforced boundaries inside one deployable, with shared transactions",
          "A separate database per module over the network", "Automatic scaling per module", "Freedom from module boundaries"],
      a: 1,
      why: "It keeps the simplicity of one deploy and one transaction while enforcing the boundaries a later split would need." }
  ],
  "observability": [
    { q: "One request is slow and touches twelve services. Which signal finds the culprit?",
      o: ["Logs searched by timestamp", "CPU metrics per host", "The overall error rate", "A trace showing the time spent in each span",
          "Saturation alerts"],
      a: 3,
      why: "A trace follows one request as a tree of spans, so the slow call stands out." },
    { q: "Mean latency is 80 ms and the team says the service is fine, yet users complain. What should they check?",
      o: ["Percentiles such as p99, which the mean hides", "The mean over a longer window", "Total request count",
          "The number of log lines", "CPU use on each host"],
      a: 0,
      why: "A mean of 80 ms can sit on a p99 of four seconds. Track percentiles." },
    { q: "What should page an on-call engineer?",
      o: ["Every CPU spike above 80%", "Each error line in the logs", "Symptoms users feel, tied to service level objectives",
          "Disk use above 50%", "Every deploy"],
      a: 2,
      why: "Alert on what users feel (latency, errors against an SLO); causes like CPU belong on dashboards, not pagers." }
  ],
  "testing-services": [
    { q: "A bug lives in how a SQL query handles NULLs. Which test catches it?",
      o: ["A unit test with the database mocked", "An integration test against a real Postgres in a container", "A snapshot test of the JSON output",
          "A lint rule", "A contract test of the HTTP API"],
      a: 1,
      why: "A mocked database mostly tests the mock. Bugs in SQL, migrations and serialisation show up only against a real one." },
    { q: "A test fails one run in twenty, so CI retries it automatically. What is better?",
      o: ["Raise the retries to five", "Skip it forever", "Run it only on main", "Use a bigger CI machine",
          "Find the shared state, time or ordering problem, or delete the test"],
      a: 4,
      why: "A suite nobody trusts gets ignored. Flaky tests usually point at shared state, time or ordering." }
  ]
});
