/* Multiple choice for the Cloud field: 2 or 3 per topic. Checked by baseline/quiz/check.js. */
BASELINE.quiz("cloud", {
  "what-is-cloud": [
    { q: "A team launches a product that might get 100 users or 100,000, and nobody knows which. Why does the cloud suit this well?",
      o: ["Cloud hardware is faster than anything you can buy",
          "The cloud is always cheaper than owning servers",
          "The provider takes responsibility for the app's design",
          "They can start small in minutes and add or remove capacity, paying for what runs",
          "Cloud servers never fail, so there is no need for spare capacity"],
      a: 3,
      why: "Rapid elasticity and metered billing turn a large upfront purchase sized for an unknown peak into paying for today's load." },
    { q: "A company runs a large, steady, predictable workload in the cloud for years. What might it find?",
      o: ["Owning hardware could cost less, since it pays for flexibility it does not use",
          "The cloud bill falls each year without any changes",
          "Steady workloads are not allowed on on-demand pricing",
          "Moving back on premises is impossible once data is in the cloud",
          "The provider moves it to free capacity once usage is steady"],
      a: 0,
      why: "The cloud is cheaper to start and to scale quickly, not automatically cheaper. At steady, large load, some companies move workloads back to their own hardware." }
  ],
  "regions-zones": [
    { q: "Three app instances run in zones a, b and c behind one load balancer, and zone a loses power. What happens?",
      o: ["The whole region fails over to another region",
          "The service goes down until zone a returns",
          "Health checks fail for zone a's instance and traffic moves to the other two",
          "The load balancer moves zone a's instance to zone b live",
          "Requests to zone a queue until its power returns"],
      a: 2,
      why: "Zones have separate power, cooling and network, so one failing leaves the others serving at reduced capacity while autoscaling replaces the lost instance." },
    { q: "A chatty service has its two halves in different zones of one region and makes thousands of calls between them per second. What is the hidden cost?",
      o: ["Cross-zone calls add about 100 ms each",
          "Cross-zone traffic is blocked unless you open a VPN",
          "Zones in one region cannot share a load balancer",
          "The service loses its multi-AZ protection",
          "Traffic between zones is billed, so every call costs money"],
      a: 4,
      why: "Zones are only a few milliseconds apart, but providers charge for data crossing between them. Multi-AZ is cheap insurance; chatty traffic across zones is not free." },
    { q: "Which is a good reason to choose a particular region, rather than a reason to spread across zones?",
      o: ["Surviving a fire in one data centre",
          "Data residency law for your users' data",
          "Keeping a database standby ready for failover",
          "Running three replicas of the app",
          "Surviving a power failure in one building"],
      a: 1,
      why: "Regions are chosen for latency to users, data residency and which services and GPUs they offer. Zones are where you spread for availability.",
      pair: "region-vs-zone" }
  ],
  "service-models": [
    { q: "A vulnerability is found in OpenSSL. Your code runs on a provider's managed Lambda runtime. Who patches the runtime's OpenSSL?",
      o: ["You, by rebuilding the VM image",
          "You, by redeploying every function with a patched copy",
          "Nobody, serverless runtimes are not affected",
          "The provider, under you, as part of the managed runtime",
          "The OpenSSL project, directly on your account"],
      a: 3,
      why: "Moving up the stack moves patching to the provider. On IaaS you rebuild images yourself; on managed serverless runtimes the provider does it." },
    { q: "Your app runs on a PaaS such as App Engine, and a library in your own dependencies is vulnerable. Whose job is the fix?",
      o: ["Yours: the provider patches the runtime, but your app's libraries stay yours",
          "The provider's, because PaaS covers everything above the hardware",
          "Nobody's, a PaaS sandbox makes library bugs harmless",
          "The library's maintainers, who push the fix to your app",
          "The provider's, but only if you open a support ticket"],
      a: 0,
      why: "The shared responsibility split moves with the model, and your code and its dependencies are always on your side. A breach in your half is still your breach.",
      pair: "iaas-vs-paas" }
  ],
  "big-three": [
    { q: "An engineer who knows AWS joins a Google Cloud team. Which mapping is correct?",
      o: ["S3 is BigQuery, EKS is Cloud Run",
          "S3 is Filestore, EKS is Compute Engine",
          "S3 is Google Cloud Storage, EKS is GKE",
          "S3 is Persistent Disk, EKS is App Engine",
          "S3 is Spanner, EKS is Cloud Functions"],
      a: 2,
      why: "The providers sell the same primitives under different names: object storage is S3, Cloud Storage and Azure Blob; managed Kubernetes is EKS, GKE and AKS." },
    { q: "Moving from one big cloud to another, where do outages and surprise bills most often come from?",
      o: ["The core ideas, which differ completely between providers",
          "Object storage, which works in incompatible ways",
          "Kubernetes, which only one provider supports fully",
          "IAM, which only exists on AWS",
          "Defaults, quotas and pricing, which differ even when the ideas match"],
      a: 4,
      why: "IAM, VPCs, object storage and managed Postgres carry over. The names, defaults, quotas and prices differ, and the defaults are where trouble starts." }
  ],
  "developer-platforms": [
    { q: "A Next.js app on Vercel runs a long agent task in a server function, and it starts failing on long runs. What is the likely wall and the usual move?",
      o: ["A database limit; move to a bigger Supabase plan",
          "The function timeout; move that one service to a container platform",
          "A DNS limit; put Cloudflare in front of Vercel",
          "A memory leak in Next.js; downgrade the framework",
          "A region limit; deploy the app to more regions"],
      a: 1,
      why: "Developer platforms are fastest at the start and limiting at the edges, and function timeouts are often the first edge. Moving the one long-running service out is the usual fix." },
    { q: "Why does it help to know that Supabase is Postgres underneath?",
      o: ["Supabase only accepts Postgres-compatible SQL from approved drivers",
          "It means Supabase has no auth or storage of its own",
          "Postgres knowledge makes the Supabase dashboard faster",
          "You know the primitive you are on, so you can leave when you outgrow the platform",
          "It means the platform can never limit you"],
      a: 3,
      why: "Each platform wraps a primitive (Supabase wraps Postgres, Vercel functions are serverless functions). Knowing it tells you what you can export and where to go next." }
  ],
  "virtual-machines": [
    { q: "An autoscaling group runs VMs from one image with min 2, max 10 and a target of 50 percent CPU. At the morning peak, average CPU hits 80 percent. What happens?",
      o: ["It launches more VMs from the same image until average CPU falls near 50 percent",
          "It resizes the existing VMs to a larger instance type",
          "It stops accepting traffic until CPU falls",
          "It moves VMs to a less busy zone",
          "It waits for an engineer to approve new capacity"],
      a: 0,
      why: "The group keeps a target by adding or removing identical instances, and replaces any that fail health checks. The image must make every instance interchangeable." },
    { q: "A key VM was configured by hand over SSH over two years, and the provider schedules it for retirement. What is the lesson?",
      o: ["Pick an instance type the provider never retires",
          "Take a disk snapshot weekly and restore it by hand",
          "Bake images or use configuration as code so any instance can be rebuilt",
          "Keep a second hand-built VM as a pet in reserve",
          "Ask the provider to exempt important VMs"],
      a: 2,
      why: "Treat VMs as cattle, not pets. A machine nobody can rebuild is a risk, and providers do retire hardware." }
  ],
  "containers": [
    { q: "An image on Cloud Run has concurrency set to 80, and a spike brings 800 concurrent requests. About how many instances run?",
      o: ["One, because Cloud Run scales vertically",
          "800, one per request",
          "80, one per allowed concurrent request",
          "Zero, because requests queue until the spike ends",
          "About 10, each serving up to 80 at once"],
      a: 4,
      why: "Concurrency is requests per instance, so 800 divided by 80 is about 10. With no traffic it scales back to zero." },
    { q: "A startup with four services asks whether to start on managed Kubernetes because large companies use it. What is the usual advice?",
      o: ["Yes, Kubernetes is the only way to run containers in production",
          "Not yet: a serverless container platform is less work for a handful of services",
          "No, containers should never be used before product-market fit",
          "Yes, because managed Kubernetes needs no one to operate it",
          "No, use bare VMs, since containers add overhead"],
      a: 1,
      why: "Kubernetes earns its cost with many services and a team to run it. With managed Kubernetes you usually still own the nodes and the YAML." },
    { q: "A Cloud Run service has been idle for an hour. Why is the next request slower than the ones after it?",
      o: ["The image is rebuilt from source on each idle period",
          "DNS for the service expires when idle",
          "The TLS certificate is reissued after idle",
          "It waits for a cold start, because the service had scaled to zero",
          "The load balancer throttles the first request after idle"],
      a: 3,
      why: "Scale to zero saves money when idle, and the price is a cold start when traffic returns. Keep a minimum instance if that latency matters." }
  ],
  "serverless": [
    { q: "A burst of 500 concurrent requests hits a Lambda function that opens a Postgres connection on each invocation, and Postgres hits its connection limit. What is the fix?",
      o: ["Put a connection pooler between the functions and the database",
          "Raise the function's memory so it runs faster",
          "Switch the function to a larger instance type",
          "Increase the function timeout to 15 minutes",
          "Retry failed connections in a tight loop"],
      a: 0,
      why: "A burst of traffic opens a burst of execution environments, each with its own connection. A pooler multiplexes them onto a few database connections." },
    { q: "A team wants to run a 40-minute video transcode on AWS Lambda. What is the problem?",
      o: ["Lambda cannot read files from S3",
          "Lambda bills per request, so long jobs are free",
          "Lambda stops a run at 15 minutes, so the job needs a container or batch service",
          "Lambda only supports JavaScript",
          "Lambda keeps no memory between lines of code"],
      a: 2,
      why: "Functions are time-limited and stateless. Long jobs belong on a container or batch platform, or split into short steps." },
    { q: "A Lambda thumbnail function runs for 300 ms per upload. How is it billed?",
      o: ["Per hour that the function exists",
          "A fixed monthly fee per function",
          "By the size of the uploaded file",
          "Per gigabyte of code deployed",
          "Time used multiplied by the memory size configured"],
      a: 4,
      why: "With no traffic nothing runs and nothing is billed. Each invocation is billed for its duration times its memory setting." }
  ],
  "gpus": [
    { q: "A 70B-parameter model in 16-bit weights must be served. Why does it not fit on one 80 GB H100?",
      o: ["H100s cannot run 16-bit models",
          "The weights alone need about 140 GB, more than the card holds",
          "The KV cache alone needs exactly 80 GB",
          "70B models need eight GPUs by licence",
          "The model is limited by FLOPs, not memory"],
      a: 1,
      why: "Two bytes per parameter times 70 billion is about 140 GB. Split it across GPUs or quantise to 8-bit, about 70 GB, to fit one card. Memory picked the hardware." },
    { q: "A team rents GPUs for an inference service that is busy only during office hours. Which matters most for cost?",
      o: ["Picking the provider with the lowest hourly GPU price",
          "Buying the largest GPU available for headroom",
          "Running each request alone so latency stays low",
          "Keeping the GPUs busy: batching, a right-sized card, scaling to zero",
          "Using on-demand instances only, never reserved ones"],
      a: 3,
      why: "An idle rented GPU is the most expensive idle machine in the cloud. Utilisation matters more than the hourly price." }
  ],
  "storage": [
    { q: "A Postgres database runs on a cloud VM. Which storage holds its data directory?",
      o: ["Block storage: a virtual disk attached to that VM",
          "Object storage, so the data is copied across zones",
          "File storage that many machines mount at once",
          "A CDN cache close to the users",
          "The VM's memory, which persists between restarts"],
      a: 0,
      why: "A database needs a disk it can edit in place. Object storage replaces whole objects over HTTP; file storage is for shared access.",
      pair: "block-vs-object-storage" },
    { q: "Users upload 20 MB videos. Why return a presigned S3 URL instead of accepting the upload on the app servers?",
      o: ["Presigned URLs make the file smaller in transit",
          "S3 refuses uploads that pass through a server",
          "The browser sends the file straight to S3, so app servers never carry the bytes",
          "Presigned URLs keep the file private forever without any policy",
          "It lets the database store the whole video"],
      a: 2,
      why: "The URL grants a time-limited right to write one key. The app stores only the key, and the heavy transfer skips your servers." },
    { q: "A team keeps 50 TB in S3 and plans to copy it to another region every night. What is the catch?",
      o: ["S3 cannot store more than a few terabytes per bucket",
          "Cross-region copies lose S3's consistency",
          "S3 deletes objects that are copied too often",
          "Copies in another region cannot be read",
          "Moving data costs far more than storing it, so the transfer bill can dwarf storage"],
      a: 4,
      why: "Storage is cheap to keep and expensive to move. Cross-region and internet egress are billed per gigabyte." }
  ],
  "vpc": [
    { q: "Postgres sits in a private subnet, and its security group allows port 5432 only from the app's security group. An attacker learns its IP. Can they connect from the internet?",
      o: ["Yes, if they know the database password",
          "No: nothing routes in from the internet, and the firewall admits only the app",
          "Yes, through the NAT gateway",
          "Only on port 443",
          "Yes, private subnets only hide the address"],
      a: 1,
      why: "Two layers stop them: the private subnet has no route from the internet gateway, and the security group allows only the app's group." },
    { q: "A private service downloads large model weights from S3 every deploy, and the NAT gateway bill is huge. What fixes it?",
      o: ["Move the service to a public subnet",
          "Download the weights twice to warm a cache",
          "Add a second NAT gateway",
          "Add a VPC endpoint for S3 so the traffic skips the NAT gateway",
          "Compress the weights with gzip"],
      a: 3,
      why: "NAT gateways charge per gigabyte processed. A storage endpoint keeps that traffic on the provider's network without passing through the NAT." },
    { q: "You allow inbound port 443 in a security group. Do you need an outbound rule for the responses?",
      o: ["No: security groups are stateful and allow replies to allowed traffic",
          "Yes: every rule needs a matching rule in the other direction",
          "Yes, unless the instance is in a public subnet",
          "No, because outbound traffic is never filtered in a VPC",
          "Only for UDP, not TCP"],
      a: 0,
      why: "Security groups track connections, so replies flow back. Network ACLs are stateless subnet rules and do need the return direction allowed.",
      pair: "security-group-vs-nacl" }
  ],
  "load-balancers": [
    { q: "You need to send `/api/*` to one pool of servers and everything else to another. Which load balancer does that?",
      o: ["A layer 4 balancer, routing by port",
          "DNS round robin across both pools",
          "A layer 7 balancer, which reads the HTTP path",
          "A NAT gateway with two routes",
          "A layer 4 balancer with sticky sessions"],
      a: 2,
      why: "Layer 4 sees only addresses and ports. Layer 7 reads HTTP, so it can route by path or host and terminate TLS.",
      pair: "l4-vs-l7" },
    { q: "An app keeps user sessions in server memory and turns on sticky sessions at the balancer. What goes wrong?",
      o: ["The balancer can no longer run health checks",
          "TLS stops working for sticky users",
          "Requests stop reaching the servers",
          "Every request goes to a random server",
          "Load spreads unevenly, and users lose their session when their server dies"],
      a: 4,
      why: "A load balancer spreads load, not state. Keep servers stateless and put sessions in a shared store." },
    { q: "Server B behind an ALB starts returning 500s on `/health` after a bad config push. What happens?",
      o: ["The balancer keeps sending traffic until B is deleted",
          "After failed checks B gets no new requests, and it rejoins once it passes again",
          "The ALB's DNS name changes to exclude B",
          "All three servers are marked unhealthy together",
          "B is restarted automatically by the load balancer"],
      a: 1,
      why: "Health checks remove failing targets from rotation and add them back when they recover, with no DNS change." }
  ],
  "dns": [
    { q: "A service runs in two regions and must move traffic to the second when the first fails. How does DNS help in the cloud?",
      o: ["It copies the database between regions",
          "It restarts failed servers in the other region",
          "It encrypts traffic between the regions",
          "A failover record answers with the healthy region's address based on health checks",
          "It keeps old answers forever so clients never notice"],
      a: 3,
      why: "Route 53 and Cloudflare can answer by health, latency, geography or weight. Clients still hold old answers until the TTL expires." },
    { q: "You point `www.example.com` at `myapp.vercel.app`, a name the platform controls and may re-point to new addresses. Which record type fits?",
      o: ["CNAME, an alias for another name",
          "A, with the platform's current IP",
          "MX, which forwards web traffic",
          "TXT, holding the target name",
          "AAAA, with an IPv6 address"],
      a: 0,
      why: "A CNAME follows the other name, so when the platform changes its addresses you need no update. An A record pins one address that can go stale.",
      pair: "cname-vs-a-record" }
  ],
  "cdn": [
    { q: "A site serves `app.3f9a.js` with a one-year `immutable` cache header. How should the next release reach users?",
      o: ["Purge the CDN cache for the whole site",
          "Lower the max-age to one minute for every file",
          "Ship it under a new URL, such as `app.7c21.js`",
          "Ask users to clear their browser cache",
          "Disable the CDN during the release"],
      a: 2,
      why: "Versioned asset URLs make invalidation unnecessary: the new file has a new URL, and the old one can stay cached forever." },
    { q: "A CDN caches the response of `GET /account`, which shows the logged-in user's details. What can happen?",
      o: ["The page loads faster for that user only",
          "The CDN refuses to cache it because it is dynamic",
          "The response is cached per browser automatically",
          "The CDN strips the personal fields before caching",
          "Another user is served the first user's details from the cache"],
      a: 4,
      why: "Caching personal responses and serving them to others is a real, recurring leak. Mark anything personal `Cache-Control: private` and cache only public content." },
    { q: "The first user in Mumbai requests a file from a site hosted in Virginia, behind a CDN. What happens?",
      o: ["The Mumbai edge answers from its cache in milliseconds",
          "A cache miss: the edge fetches from the origin, stores it, and serves later users from the copy",
          "The request goes straight to Virginia and the edge stays empty",
          "The CDN refuses the request until the file is uploaded to Mumbai",
          "The user's browser downloads it from Virginia and the edge from the browser"],
      a: 1,
      why: "The first request misses and pays the trip to the origin; later users in that city hit the edge copy, per its `Cache-Control` header." }
  ],
  "managed-databases": [
    { q: "At 14:05 someone runs `DELETE FROM orders` without a `WHERE` on RDS. What is the standard recovery?",
      o: ["Undo the statement from the RDS console",
          "Fail over to the standby, which still has the rows",
          "Restore last night's snapshot over the live database",
          "Restore to a new instance as of 14:04 and copy the rows back",
          "Ask the provider's support to recover the table"],
      a: 3,
      why: "Point-in-time restore replays the transaction logs on top of a snapshot up to a chosen minute. The standby is useless here: it replicated the delete too." },
    { q: "A team moves to a managed Postgres and its slow queries stay slow. Why?",
      o: ["Managed means the server is kept alive; queries, indexes and schema are still yours",
          "Managed databases run older Postgres versions",
          "The provider throttles queries on smaller plans",
          "Managed databases do not support indexes",
          "Slow queries mean the failover is misconfigured"],
      a: 0,
      why: "Managed does not mean tuned. Patching, backups and failover move to the provider; query design and connection limits do not." },
    { q: "A managed database fails over to its standby in another zone. What must the application handle?",
      o: ["Nothing, failover is invisible to clients",
          "A schema migration on the new primary",
          "Open connections drop, so it must reconnect and retry",
          "Restoring the data from the last backup",
          "Changing the database endpoint in its config"],
      a: 2,
      why: "Failover usually completes within a minute or two behind the same endpoint, but existing connections break. Apps need reconnect and retry logic." }
  ],
  "iam": [
    { q: "One policy allows `s3:*` on a bucket, and another explicitly denies `s3:DeleteObject` on it. Can the principal delete objects?",
      o: ["Yes, the broader allow wins",
          "Yes, whichever policy was attached last wins",
          "Only if the bucket is public",
          "Only from inside the same VPC",
          "No, an explicit deny always wins"],
      a: 4,
      why: "Everything is denied unless allowed, and an explicit deny overrides any allow." },
    { q: "A worker on a VM needs to read from S3. How should it get credentials?",
      o: ["A long-lived access key in its config file",
          "A role with short-lived credentials the platform rotates",
          "The root account's key, kept in an environment variable",
          "A shared key used by every service",
          "A personal user key from the engineer who built it"],
      a: 1,
      why: "Roles give workloads temporary credentials with no secret to leak from config. Long-lived keys get copied, committed and forgotten." },
    { q: "An image worker's role allows only `s3:GetObject` on `uploads/*` and `s3:PutObject` on `thumbs/*`. The worker is compromised. What can the attacker do?",
      o: ["Delete every bucket in the account",
          "Start new instances to mine cryptocurrency",
          "Read the production database",
          "Read uploads and write thumbnails, nothing else",
          "List all buckets and read their contents"],
      a: 3,
      why: "Least privilege limits the blast radius to exactly what the role was granted. Over-broad permissions stay invisible until someone uses them against you." }
  ],
  "cloud-cost": [
    { q: "A service serves 50 TB a month of downloads straight from S3. What dominates the bill, and what cuts it?",
      o: ["Egress to the internet; a CDN with a high hit ratio cuts what leaves S3",
          "Storage; moving to a cheaper storage class cuts it",
          "Request count; batching downloads cuts it",
          "Ingress; compressing uploads cuts it",
          "Compute; a larger instance cuts it"],
      a: 0,
      why: "Egress is billed per gigabyte and runs to thousands of dollars a month here, far more than storing the data. Ingress is free." },
    { q: "A team signs a big discount commitment, yet costs keep growing. Their design copies data across regions and through a NAT gateway. What is the lesson?",
      o: ["Discounts always outweigh design choices",
          "They should switch to a different provider",
          "Architecture decides most of the bill, and fixing it later is a migration",
          "Cross-region traffic is free with a commitment",
          "They should add more tags to their resources"],
      a: 2,
      why: "A design that moves data across regions, through NAT or out to another cloud pays every month. Discounts trim a bill that the architecture set." },
    { q: "Nobody can tell which team caused a 40 percent jump in the cloud bill. What FinOps habit addresses that?",
      o: ["Buying reserved instances for every service",
          "Giving one finance person access to the console",
          "Turning off all dev environments each night",
          "Moving everything to spot instances",
          "Tagging every resource with a team and showing cost per service"],
      a: 4,
      why: "FinOps makes engineers see and own spend: tags, cost per service and per customer, and treating a cost jump like a performance regression." }
  ],
  "spot-and-reserved": [
    { q: "A service needs 10 instances all day and 25 at the evening peak, plus a nightly report job. Which mix fits?",
      o: ["All 25 on a three-year commitment",
          "The steady 10 on a commitment, the peak on-demand, the nightly job on spot",
          "Everything on spot to get the deepest discount",
          "Everything on-demand to keep flexibility",
          "The peak on a commitment and the base on spot"],
      a: 1,
      why: "Commit for the steady floor, pay list price for short peaks, and put interruptible work on spot." },
    { q: "A training job runs on spot instances without checkpoints. What happens when a node is reclaimed?",
      o: ["The provider pauses the job and resumes it later",
          "The job moves to an on-demand node at the spot price",
          "Nothing, spot nodes are only reclaimed when idle",
          "The work since the start is lost, and the rerun costs again",
          "The provider refunds the lost hours automatically"],
      a: 3,
      why: "Spot is cheap only if the work survives being killed. With checkpoints a retry resumes from the last saved point." }
  ],
  "disaster-recovery": [
    { q: "An app sets RPO at 5 minutes and RTO at 1 hour. It takes only nightly snapshots. Which target does it fail?",
      o: ["The RPO: up to 24 hours of data could be lost",
          "The RTO: snapshots cannot be restored within a day",
          "Neither, nightly snapshots meet both",
          "Both, because snapshots stay in one region",
          "The RTO, because RPO does not apply to snapshots"],
      a: 0,
      why: "RPO is how much recent data you can lose. A nightly snapshot can lose a day; continuous replication about a second behind meets 5 minutes.",
      pair: "rpo-vs-rto" },
    { q: "Data replicates to a second region about a second behind. Someone drops a table. What protects you?",
      o: ["The replica, which keeps the table for an hour",
          "Failing over to the second region quickly",
          "Point-in-time backups, because the drop replicated too",
          "The CDN, which cached the table's pages",
          "Nothing, dropped tables cannot be recovered"],
      a: 2,
      why: "Replication copies mistakes in seconds. Backups you can restore to a time before the mistake are still essential." },
    { q: "Which strategy gives near-zero RTO and brings the hard problem of writes in two places?",
      o: ["Backup and restore",
          "Pilot light",
          "Warm standby",
          "Nightly snapshots copied across regions",
          "Active-active across regions"],
      a: 4,
      why: "Active-active serves from several regions at once, so there is little to fail over, but concurrent writes in two regions must be reconciled." }
  ],
  "lock-in": [
    { q: "Version A stores events in DynamoDB with Lambda triggers on its stream; version B uses Postgres and a container polling a jobs table. What does B buy?",
      o: ["Lower running cost today in every case",
          "A much lower price for leaving: a dump, a restore and a new connection string",
          "No operational work at all",
          "Automatic scaling to zero",
          "Better consistency than any managed service"],
      a: 1,
      why: "Lock-in is the price of switching. Portable choices cost a little more to run and far less to leave." },
    { q: "A team decides to avoid every provider-specific service. What is the cost of that choice?",
      o: ["None, portable tools are always cheaper",
          "They lose the ability to use containers",
          "They can no longer use Postgres",
          "They run more themselves on the lowest common denominator",
          "They must use several clouds at once"],
      a: 3,
      why: "Accept lock-in where a managed service saves real work, and keep the data in a format you can export." }
  ]
});
