/* Multiple choice for the Data field: 2 or 3 per topic. Checked by baseline/quiz/check.js. */
BASELINE.quiz("data", {
  "relational-sql": [
    { q: "`EXPLAIN ANALYZE` shows the planner estimated 10 rows for a step that returned 2 million. What does that suggest?",
      o: ["The query has a syntax error", "The index is corrupt and must be rebuilt",
          "Stale or missing statistics led the planner to a poor plan", "The table needs a primary key",
          "The database has run out of memory"],
      a: 2,
      why: "The planner picks join order and algorithms from statistics. An estimate far from the actual count usually means a wrong plan; refresh statistics with `ANALYZE`." },
    { q: "An endpoint listing 100 posts with their authors is slow. The query log shows 101 queries. What is it?",
      o: ["A missing index on the posts table", "A deadlock between readers", "A slow sequential scan",
          "A table lock from a running migration", "The N+1 pattern from the ORM's lazy loading"],
      a: 4,
      why: "One query for the list, then one per row. Log the queries an endpoint runs before tuning anything else." },
    { q: "What does it mean that SQL is declarative?",
      o: ["You describe the result, and the planner chooses indexes, join order and algorithms", "You list the steps the database must run, in order",
          "Queries are compiled ahead of time into machine code", "Every query must name the indexes it uses",
          "Tables must be declared before rows are inserted"],
      a: 0,
      why: "You say what you want; the query planner decides how, using statistics about the data." }
  ],
  "indexes": [
    { q: "A composite index exists on `(tenant_id, created_at)`. Which filter can it not serve efficiently?",
      o: ["`WHERE tenant_id = 5`", "`WHERE created_at > '2026-01-01'` on its own", "`WHERE tenant_id = 5 AND created_at > '2026-01-01'`",
          "`WHERE tenant_id = 5 ORDER BY created_at`", "`WHERE tenant_id IN (5, 6)`"],
      a: 1,
      why: "The index is sorted by `tenant_id` first. Without that column, matching `created_at` values are scattered across the whole index." },
    { q: "There is an index on `email`, yet `WHERE lower(email) = 'a@b.com'` runs a sequential scan. Why?",
      o: ["B-tree indexes cannot hold text values", "The index serves only range scans",
          "The index must be rebuilt after each insert", "A function on the column skips a plain index; index the expression",
          "Email columns need a GIN index"],
      a: 3,
      why: "The index stores `email`, not `lower(email)`. An expression index on `lower(email)` makes the lookup a B-tree read again." },
    { q: "Why does a B-tree over a billion rows need only about four levels?",
      o: ["Each page holds hundreds of keys, so each level fans out widely", "It stores only every thousandth key",
          "It hashes the keys into four buckets", "It keeps the whole tree in CPU cache", "It compresses every key to four bytes"],
      a: 0,
      why: "With hundreds of keys per page, a few levels cover billions of keys, so a lookup reads a handful of pages." }
  ],
  "lsm-trees": [
    { q: "Why does an LSM engine take writes faster than an in-place B-tree?",
      o: ["It skips the write-ahead log", "It writes only to memory, never to disk",
          "It turns random writes into sequential ones, via a memtable and immutable files", "It stores keys unsorted on disk",
          "It locks the whole table for each write"],
      a: 2,
      why: "Writes land in a log and an in-memory sorted table, then flush as whole sorted files. Disks handle sequential writes far better than scattered in-place updates.",
      pair: "lsm-vs-btree" },
    { q: "What do Bloom filters do during an LSM read?",
      o: ["Sort the memtable before it flushes", "Compress SSTables on disk", "Merge overlapping files", "Keep deleted keys forever",
          "Let the read skip files that cannot contain the key"],
      a: 4,
      why: "A read may otherwise check many files. A Bloom filter answers 'definitely not here' cheaply, so most files are never opened." },
    { q: "An LSM store shows latency spikes an hour after a heavy write burst ended. What is the likely cause?",
      o: ["The memtable was lost and is being rebuilt", "Compaction fell behind and is catching up, using disk bandwidth",
          "Bloom filters were switched off", "The write-ahead log is replaying", "The B-tree is rebalancing its pages"],
      a: 1,
      why: "Compaction merges files in the background. Under heavy writes it falls behind, and the catch-up competes with reads long after the burst." }
  ],
  "transactions-isolation": [
    { q: "At read committed, code runs `SELECT stock` and then `UPDATE ... SET stock = <value read> - 1` for each purchase. Under concurrency, what goes wrong?",
      o: ["Every purchase deadlocks", "Dirty reads of uncommitted rows", "Phantom rows appear in the result",
          "Lost updates: two buyers read the same value and both write it minus one", "Stock is never decremented"],
      a: 3,
      why: "Read-modify-write in application code loses updates. Use an atomic `UPDATE ... SET stock = stock - 1 WHERE stock > 0`, `SELECT ... FOR UPDATE`, or serializable with retries.",
      pair: "write-skew-vs-lost-update" },
    { q: "Two doctors are on call. Each transaction checks that at least two are on call, then takes one doctor off. Both commit under snapshot isolation, leaving none. What anomaly is this?",
      o: ["Write skew", "Dirty read", "Lost update", "Non-repeatable read", "Dirty write"],
      a: 0,
      why: "Each transaction checked a condition on its snapshot and wrote a different row, so neither saw the other. Snapshot isolation allows it; serializable does not.",
      pair: "write-skew-vs-lost-update" },
    { q: "What must an application do when it runs transactions at serializable in Postgres?",
      o: ["Take table locks before every write", "Avoid indexes on tables it writes", "Retry transactions that abort with a serialization failure",
          "Turn off MVCC for the session", "Read only from replicas"],
      a: 2,
      why: "Postgres detects dangerous patterns and aborts one transaction. Correctness depends on the application retrying it." }
  ],
  "normalisation": [
    { q: "What is the main benefit of normalisation?",
      o: ["Reads never need joins", "Writes skip foreign key checks", "Every query touches one table", "Storage becomes columnar",
          "An update happens once, so copies cannot disagree"],
      a: 4,
      why: "Each fact lives in one place and is referenced by key, so there is nothing to keep in sync." },
    { q: "A product's catalogue price changes. Should the price on last month's order rows change with it?",
      o: ["Yes, since normalisation requires one copy of the price", "No, since the order's price is a historical record, not a cache",
          "Yes, through a trigger that keeps them consistent", "No, since foreign keys forbid the update",
          "Yes, but only in a nightly batch"],
      a: 1,
      why: "Some copies are history, not redundancy. Decide which copies are caches to keep in sync and which are records to freeze." },
    { q: "A posts table stores a `comment_count` column. What does that copy need?",
      o: ["A separate database of its own", "A GIN index on the column", "Serializable isolation for every read",
          "A rule that keeps it right, such as updating it in the same transaction", "Nothing, since counts cannot drift"],
      a: 3,
      why: "Denormalised copies make reads cheap but need a rule to stay correct: the same transaction, a trigger, or an event that updates them." }
  ],
  "document-kv": [
    { q: "How do you start designing data for a document or key-value store?",
      o: ["List the access patterns, then shape keys so each one is a single lookup", "Normalise to 3NF, then add indexes",
          "Draw the entity diagram and add joins later", "Put each table into one large document", "Model it as a graph and flatten it later"],
      a: 0,
      why: "The method is the reverse of relational: access patterns first, then keys and embedded data built around them." },
    { q: "A year into a schemaless store, the team adds a field, and old documents lack it. Where does that complexity live?",
      o: ["In the database, which migrates old documents itself", "Nowhere, since schemaless means no schema",
          "In application code, which must read every old shape", "In the indexes, which reject old documents",
          "In the query planner, which fills in defaults"],
      a: 2,
      why: "Schemaless means the schema lives in code instead, and every shape ever written must still be readable." },
    { q: "A new report needs every cart joined with its user, an access pattern nobody planned for in the key-value store. What should the team expect?",
      o: ["A fast query, since every key is indexed", "An automatic secondary index", "A rewrite by the query planner",
          "One lookup per user", "An expensive scan, or a new copy of the data keyed for it"],
      a: 4,
      why: "Key-value stores are fast for planned lookups. Joins and unplanned patterns mean scanning or writing the data again in a new shape." }
  ],
  "wide-column": [
    { q: "In a wide-column store, what does the clustering key do?",
      o: ["Chooses which node holds the row", "Sorts rows inside a partition", "Compresses columns for analytics",
          "Encrypts the partition at rest", "Defines the secondary indexes"],
      a: 1,
      why: "The partition key picks the node; the clustering key orders rows within the partition, so a query reads a sorted slice.",
      pair: "partition-vs-clustering-key" },
    { q: "A chat app partitions messages by `channel_id`. One huge channel's partition becomes a hot spot. What fixes it?",
      o: ["Add a secondary index on the channel", "Move the data to a columnar store", "Raise the replication factor",
          "Bucket the partition key by time, such as channel plus day", "Join the messages at read time"],
      a: 3,
      why: "A partition that grows without bound lands on one node. Adding a time bucket to the key spreads it and caps each partition." },
    { q: "A colleague says Cassandra is a 'wide-column' store, so it suits analytics like a columnar warehouse. What is wrong?",
      o: ["Wide-column stores are row stores grouped by partition, not analytics engines", "Cassandra keeps only one column per table",
          "Wide-column and columnar are the same design", "Cassandra has no partitions at all", "Wide-column stores cannot hold numbers"],
      a: 0,
      why: "The names look alike. Columnar engines store each column contiguously for scans; wide-column stores serve one partition's sorted rows by key.",
      pair: "wide-column-vs-columnar" }
  ],
  "graph-db": [
    { q: "A Postgres app needs a 'friends of friends' feature, two hops deep. What is the sensible start?",
      o: ["Migrate all data to a graph database", "Add a vector index for friendships", "A join or a recursive CTE in Postgres",
          "Denormalise friends into a document store", "Precompute every pair into a cache"],
      a: 2,
      why: "Two or three hops run fine with joins or a recursive CTE. A graph database earns its place when deep traversal is the main workload." },
    { q: "Why does one hop in a native graph store cost about the same however large the graph is?",
      o: ["The whole graph is kept in memory", "Queries are compiled to SQL first", "Every node is hashed into a global table",
          "Graph databases cap the graph's size", "Each node stores its relationships next to it"],
      a: 4,
      why: "Following a relationship means reading a pointer stored with the node, not searching an index over the whole graph." },
    { q: "Which workload most justifies a graph database?",
      o: ["Monthly revenue by region", "Fraud rings found by patterns of unknown depth across accounts", "User sessions with a TTL",
          "Fetching an order by its id", "Appending sensor readings"],
      a: 1,
      why: "Graphs fit queries many hops deep or of unknown depth, where SQL needs many self-joins or recursion." }
  ],
  "vector-db": [
    { q: "What does raising `ef_search` in an HNSW index trade?",
      o: ["Lower memory for lower recall", "Faster writes for slower reads", "Exact results at no cost in speed",
          "Higher recall for slower queries", "Smaller vectors for higher recall"],
      a: 3,
      why: "A wider search walks more of the graph, finding more true neighbours at the cost of time. Tune it against a labelled test set." },
    { q: "After adding a tenant filter to vector search, users start missing relevant documents. Why?",
      o: ["Filtering with an approximate index can silently drop recall", "The embedding model changed underneath",
          "Cosine distance stops working with filters", "The filter forces exact search", "Tenants share one embedding space"],
      a: 0,
      why: "The index finds approximate neighbours, then the filter removes many of them, leaving too few. Hybrid search with a reranker often helps more than tuning." },
    { q: "How does an IVF index avoid comparing the query with every vector?",
      o: ["It walks a layered graph from coarse to fine", "It quantizes queries to one bit", "It clusters vectors and searches only the nearest clusters",
          "It caches the last thousand queries", "It filters by keyword first"],
      a: 2,
      why: "IVF partitions vectors into clusters and probes the few nearest the query. The layered graph is HNSW.",
      pair: "hnsw-vs-ivf" }
  ],
  "oltp-olap": [
    { q: "Why is columnar storage fast for summing one column over a billion rows?",
      o: ["It keeps every row in memory", "It keeps a B-tree per column", "It updates rows in place",
          "It takes fewer locks per query", "It reads only that column, compressed, in SIMD batches"],
      a: 4,
      why: "Each column is stored contiguously and compresses well; the query reads only the columns it names and processes them in vectorised batches.",
      pair: "row-vs-columnar" },
    { q: "A small team runs heavy analytics queries on the production Postgres. What is the risk, and the fix?",
      o: ["None, Postgres isolates analytics on its own", "They compete with users for CPU and cache; replicate to an analytics store",
          "They corrupt indexes; rebuild them nightly", "They lock rows; use read uncommitted",
          "They fill the disk; add partitions"],
      a: 1,
      why: "Analytics and users share one CPU and cache. Replicate first, even small: DuckDB on Parquet files is often enough." },
    { q: "Which of these is an OLTP workload?",
      o: ["A dashboard summing a year of sales", "A nightly job computing churn by cohort", "A data scientist scanning event logs",
          "Thousands of small reads and writes by key each second", "A quarterly report across all regions"],
      a: 3,
      why: "OLTP is the application's own traffic: many small keyed queries, many of them writes. The rest scan many rows and few columns, which is OLAP." }
  ],
  "warehouses-lakehouses": [
    { q: "What does a table format such as Apache Iceberg add to files in a data lake?",
      o: ["Snapshots in metadata, giving atomic commits, schema evolution and time travel", "A proprietary storage engine",
          "Row-level B-tree indexes", "Faster object storage hardware", "A replacement for Parquet files"],
      a: 0,
      why: "Metadata files list which data files make up each snapshot, which brings transactions to plain files and lets several engines share the tables." },
    { q: "A streaming job writes to an Iceberg table every few seconds, and queries keep getting slower. Why?",
      o: ["Iceberg cannot accept streaming writes", "Old snapshots are being lost", "Many small files slow every query until compaction rewrites them",
          "Parquet turns row-oriented when streamed", "Time travel has been switched off"],
      a: 2,
      why: "Every commit adds files, and queries pay per file. Compaction rewrites small files into large ones." },
    { q: "A team moves to open table formats to avoid lock-in. What lock-in remains?",
      o: ["Storage, since the files stay proprietary", "The Parquet format itself", "None, since open formats remove it",
          "The object storage API", "The catalogue, governance and compute around the tables"],
      a: 4,
      why: "Open formats free the storage. The catalogue, access rules and the engines you build on still tie you in." }
  ],
  "batch-stream": [
    { q: "A mobile event happened at 10:01 but reached the server at 10:20. For 'events per minute', which window should it count in?",
      o: ["10:20, by processing time", "10:01, by event time", "Neither, since late events are dropped", "Both windows",
          "The window when the job restarts"],
      a: 1,
      why: "Results that describe what happened group by event time. Processing time only says when the system saw it.",
      pair: "event-vs-processing-time" },
    { q: "In stream processing, what does a watermark do?",
      o: ["Marks duplicate events", "Encrypts the stream in transit", "Orders events by key",
          "Estimates when a window has seen all its events", "Caps the stream's throughput"],
      a: 3,
      why: "Some events arrive late. The watermark is the engine's estimate that a window is complete, so it can emit the result." },
    { q: "The business wants a dashboard refreshed every hour. The team proposes Flink. What is the best response?",
      o: ["Run an hourly batch, since streaming costs more to build and run", "Flink is required for anything under a day",
          "Use Kafka Streams instead of Flink", "Stream it, since streaming is cheaper", "Add a watermark for each hour"],
      a: 0,
      why: "If an hourly batch meets the need, run the batch: simpler to reason about, rerun and operate." }
  ],
  "etl-elt": [
    { q: "A transformation bug is found three months later. Why is recovery easier with ELT?",
      o: ["ELT transforms on a separate server", "ELT throws the raw data away", "Raw data was kept, so the fixed transform reruns over all history",
          "ELT has no transformations", "ELT runs in real time"],
      a: 2,
      why: "ELT loads raw data before transforming, so the history is still there to rebuild from.",
      pair: "etl-vs-elt" },
    { q: "What does dbt do in a data stack?",
      o: ["Extracts data from SaaS tools", "Schedules jobs across all systems", "Stores tables as Parquet files",
          "Streams change events to Kafka", "Builds tables and views from SQL `SELECT`s, in dependency order, with tests"],
      a: 4,
      why: "Extraction is Fivetran or Airbyte, scheduling is Airflow or Dagster; dbt is the transformation layer in SQL." },
    { q: "A warehouse has 600 dbt models, many with no owner. What practice helps most?",
      o: ["Move back to ETL", "Treat transforms as code: review, test, and delete models nobody reads", "Add more warehouse compute",
          "Merge all models into one", "Turn off tests to speed up runs"],
      a: 1,
      why: "ELT moves the mess into the warehouse, where it grows without limit unless it is owned like code." }
  ],
  "cdc": [
    { q: "An application writes to Postgres, then publishes the event to Kafka, and crashes in between. What is this problem called?",
      o: ["Write skew", "The N+1 problem", "Replication lag", "Dual writes", "A cache stampede"],
      a: 3,
      why: "Two separate writes can disagree after a crash. CDC or a transactional outbox makes the database the single source." },
    { q: "An upstream team renames a column, and three downstream consumers of the CDC feed break. How do you prevent this?",
      o: ["Publish a stable event contract, often through an outbox table", "Pause CDC during every deploy",
          "Read the binlog instead of the WAL", "Run the source at serializable", "Index the renamed column"],
      a: 0,
      why: "Raw CDC events carry the physical schema. A deliberate event contract decouples consumers from table changes." },
    { q: "What does change data capture read?",
      o: ["The application's log files", "Query results polled every minute", "The database's own change log, such as the Postgres WAL",
          "A nightly full dump of each table", "The database's backups"],
      a: 2,
      why: "The database already logs every committed change for recovery and replication; CDC turns that log into ordered events." }
  ],
  "data-quality-lineage": [
    { q: "A dashboard showed yesterday's numbers as today's for a week before anyone noticed. Which check would have caught it?",
      o: ["A uniqueness test on keys", "A not-null test", "An accepted-values test", "A foreign key test", "A freshness check on the source"],
      a: 4,
      why: "A stopped pipeline leaves valid-looking data. Freshness is the failure dashboards hide best, so alert on it." },
    { q: "A revenue figure looks wrong. What does lineage give you?",
      o: ["The correct value", "Every upstream table and job it depends on", "The name of whoever last edited it",
          "A rollback of the pipeline", "The SQL rewritten to run faster"],
      a: 1,
      why: "Lineage is a graph of which jobs read and wrote which datasets, so you can walk from the number to its sources." },
    { q: "Where should the strictest data quality checks sit?",
      o: ["Only on the dashboard", "In the BI tool's cache", "At the end of the pipeline", "Where data enters", "In the orchestrator's logs"],
      a: 3,
      why: "Checks at the end find problems after they spread. Checks at the entry stop bad data before it reaches anything." }
  ],
  "caching": [
    { q: "A hot key expires and thousands of requests hit the database at once. What fixes this?",
      o: ["Request coalescing, so one request refills while the others wait", "Shorter TTLs on every key",
          "Write-through on every read", "Removing TTLs entirely", "Adding database replicas and nothing else"],
      a: 0,
      why: "That is a stampede. Coalescing, or refreshing hot keys before they expire, keeps the refill to one request.",
      pair: "stampede-vs-invalidation" },
    { q: "The cache cluster restarts, and the database falls over minutes later. What was the mistake?",
      o: ["Using cache-aside", "Setting TTLs on entries", "Never checking what load the database sees with an empty cache",
          "Using write-through", "Storing JSON in the cache"],
      a: 2,
      why: "A cache hides load until it fails. Know what happens with an empty cache before relying on one." },
    { q: "Why give every cache entry a TTL, even when writes invalidate keys?",
      o: ["TTLs make reads faster", "TTLs reduce memory fragmentation", "Redis requires a TTL on every key",
          "TTLs prevent stampedes", "So stale data disappears even when invalidation misses"],
      a: 4,
      why: "Invalidation will miss sometimes. A TTL bounds how long a stale value can live.",
      pair: "stampede-vs-invalidation" }
  ]
});
