/* Multiple choice for the DevOps, security and reliability field: 2 or 3 per topic. Checked by baseline/quiz/check.js. */
BASELINE.quiz("devops", {
  "version-control": [
    { q: "A team keeps feature branches open for three weeks and merges them all right before each release. What problem does trunk-based development target here?",
      o: ["Developers who cannot see each other's code",
          "Release tags that become hard to name",
          "Large, late merges that surface integration bugs near the release",
          "Commits that are too small to review properly",
          "A git history that grows too long to search"],
      a: 2,
      why: "Long-lived branches drift apart, so integration happens all at once and late. Short branches merged daily keep the trunk close to releasable." },
    { q: "A team starts merging to main every day, but its tests take two hours and miss many breakages. What is the likely result?",
      o: ["Feature flags will catch the bugs instead of tests",
          "Merge conflicts rise sharply and slow everyone down",
          "Breakage reaches everyone on main faster, since nothing catches it before merge",
          "Fewer bugs, because each merge is smaller",
          "No change, because branching style does not affect quality"],
      a: 2,
      why: "Trunk-based work relies on fast, trusted CI. Without it, frequent merges spread bugs instead of preventing them." },
    { q: "Half of a feature is merged to trunk but must not be visible to users yet. What is the usual tool?",
      o: ["Keep the work on a long-lived branch until it is finished",
          "Revert it from trunk and merge it again later",
          "A separate release branch for that one feature",
          "A git tag that marks the commits as unfinished",
          "A feature flag that keeps the new code path off"],
      a: 4,
      why: "Flags let unfinished work live on the trunk without users seeing it, which is what keeps branches short.",
      pair: "trunk-vs-feature-branches" }
  ],
  "ci-cd": [
    { q: "Every passing change becomes a release artifact, and a person presses a button to send it to production. What is this?",
      o: ["Continuous deployment",
          "Continuous integration only",
          "Blue-green deployment",
          "Trunk-based development",
          "Continuous delivery"],
      a: 4,
      why: "Continuous delivery keeps every change releasable behind a button; continuous deployment removes the button and ships automatically.",
      pair: "delivery-vs-deployment" },
    { q: "A test fails about one run in ten for no code reason, and people re-run the pipeline until it passes. What is the main danger?",
      o: ["Merges get slower but stay equally safe",
          "Nothing, since the test still passes eventually",
          "People learn to ignore red builds, so real failures slip through",
          "The pipeline costs a little more compute per merge",
          "Coverage figures become slightly inaccurate"],
      a: 2,
      why: "A flaky test trains the team to distrust failures. Quarantine or fix it at once." },
    { q: "A pipeline takes an hour, so developers start pushing a day's work at a time. Why does that undercut CI?",
      o: ["Batching lowers test coverage for each change",
          "Long pipelines cannot build container images",
          "Batched changes mean a failure hides among many changes, which CI exists to prevent",
          "An hour is too long for the CI server's time limit",
          "Larger pushes use more build runners in parallel"],
      a: 2,
      why: "CI's value is fast feedback on small changes. A slow pipeline invites batching, and batching brings back late, tangled failures." }
  ],
  "deployment-strategies": [
    { q: "You want to roll back in seconds by switching traffic, and can afford two full environments. Which strategy fits?",
      o: ["Blue-green",
          "Rolling",
          "Canary",
          "Recreate",
          "Shadow traffic"],
      a: 0,
      why: "Blue-green keeps the old environment intact and idle, so rollback is a traffic switch back.",
      pair: "blue-green-vs-canary" },
    { q: "A new version drops a database column the old version still reads, and you roll it out as a canary. What goes wrong?",
      o: ["The old version, still serving most traffic, breaks once the column is gone",
          "Nothing, because the canary only receives 1% of traffic",
          "Kubernetes rejects the canary automatically",
          "The new version cannot start until the old one stops",
          "Only the canary's users see any errors"],
      a: 0,
      why: "Every gradual strategy runs old and new side by side, so schema changes must be backward compatible: expand first, contract later." },
    { q: "Staging tests pass, then a configuration push causes a production outage. What lesson does this point to?",
      o: ["Config outages are rare enough to accept",
          "Treat config pushes as deploys, with staged rollout and rollback",
          "Config pushes should skip review so fixes move faster",
          "Staging must be made identical to production first",
          "Only code changes need a canary"],
      a: 1,
      why: "Config and content pushes cause as many outages as code. Staging rarely matches production, so a gradual rollout is often the first real test." }
  ],
  "feature-flags": [
    { q: "New code is in production, but users cannot see it until a flag is turned on. What has the flag separated?",
      o: ["Rollback from roll forward",
          "Deploy from release",
          "Build from test",
          "Staging from production",
          "Commit from merge"],
      a: 1,
      why: "A deploy puts code on servers; a release exposes it to users. Flags let you do them at different times.",
      pair: "deploy-vs-release" },
    { q: "During a traffic spike, on-call wants to switch off an expensive recommendation widget without a deploy. Which kind of flag is this?",
      o: ["A permission flag",
          "A migration flag",
          "An ops flag",
          "A release flag",
          "An experiment flag"],
      a: 2,
      why: "Ops flags exist so operators can shed load or disable a feature under pressure without shipping code." },
    { q: "A codebase has 300 flags, many of them fully rolled out a year ago. What is the main cost?",
      o: ["Old flags expire and turn features off unexpectedly",
          "Old flags block new deploys from running",
          "The flag service charges per flag stored",
          "Each flag multiplies code paths, and stale ones rot and confuse",
          "Flag lookups noticeably slow every request"],
      a: 3,
      why: "Every flag doubles the paths through the code. Give release flags an owner and an expiry, and delete them once rolled out." }
  ],
  "containers": [
    { q: "Why does a container start in milliseconds while a virtual machine takes much longer?",
      o: ["Containers are compiled ahead of time for the host",
          "Containers skip the filesystem until first use",
          "Containers run outside the kernel in user space",
          "It is an isolated process on the host's shared kernel, so no OS has to boot",
          "Container images are always smaller than VM disks"],
      a: 3,
      why: "Namespaces and cgroups isolate and limit an ordinary process. There is no guest kernel to boot.",
      pair: "container-vs-vm" },
    { q: "You need to run untrusted, user-submitted code. Why is a plain container a weak boundary?",
      o: ["Container images cannot be scanned for malware",
          "Containers always run their process as root",
          "All containers share the host kernel, so one kernel exploit escapes them all",
          "Containers cannot cap CPU or memory use",
          "Container networking cannot be turned off"],
      a: 2,
      why: "A shared kernel is a weaker boundary than a VM. Untrusted code goes in gVisor, Firecracker microVMs or Kata containers.",
      pair: "container-vs-vm" },
    { q: "A deployment pulls `myapp:latest` and starts behaving differently with no change on your side. What is the likely cause?",
      o: ["The local Docker layer cache expired",
          "The tag now points to a newer image; pin images by digest instead",
          "The registry corrupted some image layers",
          "cgroups lowered the container's memory limit",
          "The host kernel was upgraded overnight"],
      a: 1,
      why: "A tag is a movable name; a digest identifies exact image contents." }
  ],
  "kubernetes": [
    { q: "You delete one pod belonging to a deployment set to 3 replicas. What happens next?",
      o: ["The whole deployment restarts from scratch",
          "A controller sees 2 of 3 running and starts a replacement pod",
          "The deployment now runs 2 replicas until edited",
          "Kubernetes raises an alert and waits for an operator",
          "The service stops routing until the pod is restored"],
      a: 1,
      why: "Kubernetes is a set of control loops comparing desired with actual state and acting to close the gap." },
    { q: "Pods come and go with new IP addresses. What gives other workloads one stable address for a set of pods?",
      o: ["An ingress",
          "A deployment",
          "The kubelet",
          "etcd",
          "A service"],
      a: 4,
      why: "A service fronts a changing set of pods. An ingress routes outside HTTP traffic in, usually to services.",
      pair: "service-vs-ingress" },
    { q: "A four-person startup with one web app asks whether to run its own Kubernetes cluster. What is the usual advice?",
      o: ["No, because containers are wrong for small apps",
          "Usually not: a managed container service spares them the platform work",
          "Yes, since it is required to run containers at all",
          "Yes, since it removes networking and storage work",
          "Only if they also adopt a service mesh"],
      a: 1,
      why: "Kubernetes solves scheduling and healing, then hands you networking, storage, security policy and upgrades. It is a platform for building platforms." }
  ],
  "infrastructure-as-code": [
    { q: "Someone edits a firewall rule by hand in the cloud console. What can the next `terraform apply` do?",
      o: ["Revert it to match the code, often without anyone noticing",
          "Import the hand edit into the code automatically",
          "Refuse to run until the console change is undone",
          "Nothing, since Terraform ignores console changes",
          "Delete the whole firewall and recreate it empty"],
      a: 0,
      why: "A manual change is drift: the code and state still describe the old rule, so apply puts it back." },
    { q: "Two engineers run `terraform apply` at the same moment, each with a local state file. What is the risk, and the fix?",
      o: ["Conflicting or lost state; keep state remote with locking",
          "Slow applies; run Terraform on a faster machine",
          "Duplicate resources; split the code into modules",
          "Missing variables; move them into a .tfvars file",
          "No risk, since Terraform merges both runs"],
      a: 0,
      why: "The state file records what exists. Remote storage with a lock stops two applies racing, and it should be protected since it can hold secrets." }
  ],
  "config-and-secrets": [
    { q: "Why should a database URL come from the environment rather than be built into the image?",
      o: ["So one build runs unchanged in dev, staging and production",
          "Because environment variables are encrypted at rest",
          "Because images cannot contain connection strings",
          "Because it makes the app start faster",
          "Because Kubernetes refuses images with URLs"],
      a: 0,
      why: "The Twelve-Factor rule: what differs between environments lives in the environment, so the artifact you tested is the one you ship." },
    { q: "A team keeps an API key in a Kubernetes Secret and assumes it is encrypted. Is it?",
      o: ["No, Secrets are copied into the image in plain text",
          "It is only base64-encoded, unless encryption at rest is configured for etcd",
          "Yes, Secrets are always encrypted with AES",
          "Yes, as long as the pod runs as a non-root user",
          "Yes, because only the kubelet can read etcd"],
      a: 1,
      why: "Base64 is an encoding, not encryption. Turn on encryption at rest, or fetch from a secrets manager." },
    { q: "A CI job needs cloud credentials to deploy. What is better than a long-lived access key saved in CI settings?",
      o: ["The key in an encrypted file inside the repo",
          "A shared admin account used only by CI",
          "The key passed in as a Docker build argument",
          "Exchanging the run's OIDC token for short-lived cloud credentials",
          "The same key, rotated once a year"],
      a: 3,
      why: "Credentials that never exist as long-lived strings cannot leak as long-lived strings." }
  ],
  "observability": [
    { q: "A request is slow and passes through five services. Which signal shows where the time went?",
      o: ["A metric of average latency per service",
          "A log line written when the request ends",
          "A CPU dashboard for each host",
          "An uptime check against the front door",
          "A trace, with a span per step and its duration"],
      a: 4,
      why: "Traces follow one request across services as a tree of spans, so the slow hop stands out.",
      pair: "metrics-vs-traces" },
    { q: "A team labels its latency metric with user id, for millions of users. What happens?",
      o: ["One time series per user, so cost can exceed the service it watches",
          "The metric becomes more accurate at no extra cost",
          "The backend drops the label automatically",
          "Alerts fire faster, since there is more data",
          "Nothing, since labels are stored once per metric"],
      a: 0,
      why: "Metric cost scales with cardinality. Put high-cardinality detail on traces and logs, and keep metric labels few.",
      pair: "metrics-vs-traces" },
    { q: "What does OpenTelemetry give a team that runs several monitoring vendors?",
      o: ["A query language shared by all databases",
          "A tool that only collects application logs",
          "An alerting service with built-in SLOs",
          "One vendor-neutral SDK and wire format for logs, metrics and traces",
          "A hosted dashboard that replaces all vendors"],
      a: 3,
      why: "Instrument once with OpenTelemetry and send the data to any backend." }
  ],
  "slos-error-budgets": [
    { q: "The SLO is 99.9% of requests good over 30 days, and the budget is used up in week two. What does an error budget policy do?",
      o: ["Raise the SLO so the target is easier to meet",
          "Ship features faster to make up the lost time",
          "Pause monitoring until the window resets",
          "Shift work toward reliability until the budget recovers",
          "Pay the customers the SLA penalty right away"],
      a: 3,
      why: "The budget turns speed versus stability into arithmetic: while it lasts, take risks; when it is gone, fix reliability." },
    { q: "How should an SLA relate to the internal SLO?",
      o: ["The SLA is looser, so you notice a miss before it costs money",
          "The SLA is stricter, so customers get extra margin",
          "They are always the same number",
          "The SLA measures CPU while the SLO measures errors",
          "The SLA replaces the SLO once signed"],
      a: 0,
      why: "The SLA is a contract with a penalty; the SLO is the tighter internal target that warns you first.",
      pair: "slo-vs-sla" },
    { q: "A product manager asks for a 100% availability target. Why is that the wrong goal?",
      o: ["100% removes the need for any monitoring",
          "Cloud providers forbid 100% targets",
          "Users cannot tell the extra nines through their own networks, and each costs far more",
          "100% is easy to reach with enough servers",
          "SLOs must always be set below 99%"],
      a: 2,
      why: "Pick the SLO from what users notice, measured close to them. Past that point, nines cost a lot and buy nothing visible." }
  ],
  "alerting": [
    { q: "Which of these should page someone at night?",
      o: ["A batch job ran 5% slower than yesterday",
          "A dependency published a new minor version",
          "Error rate is spending the monthly error budget quickly",
          "CPU on one node has been at 90% for ten minutes",
          "Disk usage on a log server reached 60%"],
      a: 2,
      why: "A good page is urgent, actionable and about a symptom users feel, not a cause such as CPU." },
    { q: "Why use a multiwindow burn rate alert instead of a single short window?",
      o: ["It measures CPU and memory in one alert",
          "It replaces the need for an SLO",
          "It pages only during business hours",
          "It fires fast on a real outage and clears fast after, without flapping on blips",
          "It sends fewer alerts by ignoring short outages entirely"],
      a: 3,
      why: "Requiring both a long and a short window to exceed the threshold filters noise while still catching sharp burns." },
    { q: "Most pages on a rotation need no action. What should the team do?",
      o: ["Route the alerts to email and keep them all",
          "Keep them, since more alerts mean more coverage",
          "Delete or demote every alert that fired without needing a human",
          "Add a second person to watch the noisy alerts",
          "Raise every threshold by a fixed amount"],
      a: 2,
      why: "Alert fatigue makes people miss the real page. An alert that needs no action is noise." }
  ],
  "incident-response": [
    { q: "Ten minutes into an outage, the team argues about the root cause while users still see errors. What should come first?",
      o: ["Wait for more data before acting",
          "Mitigate: roll back, fail over or turn off the flag",
          "Finish the root cause analysis before touching anything",
          "Write the postmortem timeline while it is fresh",
          "Find out who made the change"],
      a: 1,
      why: "Serve users again first. Root cause can wait until the bleeding stops." },
    { q: "An outage starts with no obvious cause. What is the fastest first question?",
      o: ["Which cloud region is the most reliable?",
          "What is the service's long-term SLO?",
          "Has this alert fired before this year?",
          "What changed in the last hour: a deploy, a config push, a flag flip?",
          "Which engineer is on call this week?"],
      a: 3,
      why: "Most incidents follow a change, and undoing it is often the quickest mitigation." },
    { q: "Why is a postmortem written blameless?",
      o: ["People who fear blame hide the details needed to fix the system",
          "So that no action items have to be assigned",
          "Because the cause is always the system, never a change",
          "So that the incident does not count against the SLO",
          "Because legal teams require it for every outage"],
      a: 0,
      why: "Blameless asks how the system let a reasonable person make the mistake, and it still ends with owned action items." }
  ],
  "on-call": [
    { q: "What most makes a 3 a.m. page survivable for the engineer holding it?",
      o: ["A longer acknowledgement window of an hour",
          "A rule that only seniors carry the pager",
          "A larger number of alerts for more context",
          "A policy of fixing root causes before mitigating",
          "A runbook and dashboard linked from the alert, and authority to roll back"],
      a: 4,
      why: "Runbooks, linked dashboards and the right to roll back turn a page into a known procedure." },
    { q: "A team's on-call rotation leaves people exhausted every week. Where does the fix usually lie?",
      o: ["Fewer noisy alerts and fragile services, paid for from the error budget",
          "Hiring engineers who handle pressure better",
          "Longer shifts so handovers happen less often",
          "Removing the secondary on-call to save time",
          "Turning off alerting outside business hours"],
      a: 0,
      why: "On-call load is a signal about the system. Google's SRE book caps on-call at 25% of time and about two incidents per shift." }
  ],
  "owasp-top-10": [
    { q: "A user changes `/invoices/1041` to `/invoices/1042` in the URL and sees another customer's invoice. Which class of bug is this?",
      o: ["Injection",
          "Cryptographic failure",
          "Security misconfiguration",
          "Cross-site request forgery",
          "Broken access control"],
      a: 4,
      why: "The server must check that this user may see this object on every request. It leads the OWASP list.",
      pair: "authn-vs-authz" },
    { q: "An app passes an automated security scanner with no findings. What can it still have?",
      o: ["Only bugs in the CSS and HTML",
          "Access control bugs, which are logic errors the scanner cannot know",
          "Nothing serious, since scanners cover the whole Top 10",
          "Only performance problems, not security ones",
          "Only issues in third-party libraries"],
      a: 1,
      why: "The list is a floor. Access control needs someone who knows the app's rules to test it." },
    { q: "Which defence fits SQL injection?",
      o: ["Parameterised queries that keep data apart from the SQL",
          "Hashing the input with bcrypt before using it",
          "Escaping quotes with a regular expression",
          "Running the database on a private network",
          "Encrypting the database at rest"],
      a: 0,
      why: "Parameterised queries send values separately, so input can never change the statement's structure." }
  ],
  "threat-modelling": [
    { q: "When is a threat model worth the most?",
      o: ["After launch, once real attacks are seen",
          "During the annual compliance audit",
          "Only after a penetration test fails",
          "Once the system is fully documented",
          "Before code exists, while the design can still change cheaply"],
      a: 4,
      why: "It is structured worry done early. Keep it to one diagram and one list, and redo it when a new trust boundary appears." },
    { q: "Your system gains a webhook endpoint that accepts data from a partner. What does that add to the model?",
      o: ["A need for a new encryption algorithm",
          "A new trust boundary to walk for threats",
          "Nothing, since partners are trusted",
          "Only a performance concern",
          "A reason to drop the existing diagram"],
      a: 1,
      why: "Where data crosses from outside into your control is where threats live, and STRIDE gives the checklist for walking it." },
    { q: "In STRIDE, an attacker who makes the server act as an admin user is an example of which threat?",
      o: ["Spoofing",
          "Tampering",
          "Repudiation",
          "Information disclosure",
          "Elevation of privilege"],
      a: 4,
      why: "Spoofing is pretending to be someone; elevation of privilege is gaining rights you should not have.",
      pair: "spoofing-vs-elevation" }
  ],
  "supply-chain": [
    { q: "A scanner reports 400 vulnerable dependencies. How should a team prioritise?",
      o: ["By fixing them all in one large upgrade",
          "By ignoring the scanner until a breach happens",
          "By removing every dependency with any alert",
          "By reachability and exposure: is the vulnerable code called and reachable?",
          "Strictly by CVE number, oldest first"],
      a: 3,
      why: "Most alerts are for code paths you never call. Small, frequent updates keep the urgent patch a small diff." },
    { q: "What do lockfiles and pinned versions protect against?",
      o: ["Known vulnerabilities in the pinned versions",
          "A compromised maintainer of a pinned release",
          "Secrets committed to the repository",
          "Typos in your own import statements",
          "A build silently pulling a new, possibly malicious, version"],
      a: 4,
      why: "Pinning makes builds reproducible and stops surprise upgrades; it does not fix the version you pinned." },
    { q: "The SolarWinds attack shipped a backdoor inside a signed update. What did it compromise?",
      o: ["The customers' firewalls directly",
          "An unsigned download mirror",
          "The build system, so the signature itself was genuine",
          "A typosquatted package on a public registry",
          "A library with a known, public vulnerability"],
      a: 2,
      why: "Signing proves who built it, not that the build was clean. SLSA levels address build integrity." }
  ],
  "secrets-scanning": [
    { q: "A developer commits an AWS key, pushes, then deletes it in the next commit. What should happen?",
      o: ["Nothing more, since the line is deleted",
          "Force-push to rewrite history, and keep the key",
          "Make the repository private and keep the key",
          "Add the file to .gitignore and keep the key",
          "Revoke and rotate the key, check access logs, then clean up"],
      a: 4,
      why: "The key remains in git history, forks and caches. Any secret that reached a remote is compromised." },
    { q: "Where should secret scanning run?",
      o: ["Only on files named config",
          "As a pre-commit hook, in CI, and continuously over the repo and its history",
          "Only in production log files",
          "Only once, before the first release",
          "Only on pull requests from outside contributors"],
      a: 1,
      why: "Each point catches what the others miss: before commit, before merge, and in history already pushed." }
  ],
  "zero-trust": [
    { q: "A company replaces its VPN with an identity-aware proxy, but internal services still accept any caller on the network. Is it zero trust?",
      o: ["Yes, since users now sign in with SSO",
          "Yes, as long as the firewall stays in place",
          "No, because zero trust requires no firewall at all",
          "Not yet: only the front door changed, services still trust the network",
          "Yes, since the VPN is gone"],
      a: 3,
      why: "Zero trust is an architecture. Every request, person or service, is authenticated and authorised on its own." },
    { q: "How do services authenticate each other in a zero trust design?",
      o: ["With one shared API key across all services",
          "By placing them in the same subnet",
          "With the user's session cookie passed along",
          "Mutual TLS with workload identities, often via a service mesh",
          "By trusting any caller with an internal IP"],
      a: 3,
      why: "Mutual TLS proves both sides' identities on every connection, with identities such as SPIFFE rather than network location.",
      pair: "network-vs-identity" }
  ]
});
