/* Multiple choice for the Distributed systems field: 2 or 3 per topic. Checked by baseline/quiz/check.js. */
BASELINE.quiz("distributed", {
  "why-distribute": [
    { q: "A service stores 2 TB and takes 5,000 writes per second on one large cloud machine. What is the best first reason to add a second machine?",
      o: ["Sharding, so each machine holds 1 TB",
          "Multi-leader replication, so both machines take writes",
          "Fault tolerance: a standby replica in another zone",
          "Consistent hashing, so new nodes can join later",
          "Scale, because one machine cannot take 5,000 writes"],
      a: 2,
      why: "One modern machine handles this load. What it cannot do is survive its own failure, so a replica comes before sharding, which earns its cost at tens of terabytes or more writes than one primary can take." },
    { q: "Where does most of the difficulty of spreading a system over many machines lie?",
      o: ["In the load balancer that spreads requests",
          "In the stateless web tier, which must be copied everywhere",
          "In the network bandwidth between machines",
          "In the container images, which must match on every host",
          "In the state, because copies can disagree and fail separately"],
      a: 4,
      why: "Stateless services scale out by adding copies. State brings copies that disagree, coordination and partial failure, so distribute it only when one machine plus replicas cannot do the job." }
  ],
  "partial-failure": [
    { q: "A service calls a payment API with a 2 s timeout, and the timeout fires. What does the caller know?",
      o: ["The charge failed and can be retried freely",
          "Nothing about whether the charge happened",
          "The payment server has crashed",
          "The network between them is down",
          "The charge succeeded but the reply was slow"],
      a: 1,
      why: "A timeout cannot tell a lost request from a lost reply, a crash, a pause or overload. The server may have done the work." },
    { q: "After that timeout, what makes it safe to retry the payment?",
      o: ["Waiting twice as long before the retry",
          "Retrying on a different server of the payment API",
          "Doubling the timeout so it fires less often",
          "Sending an idempotency key so the server can recognise a repeat",
          "Checking that the network is healthy before retrying"],
      a: 3,
      why: "Any retry after an unknown outcome must be safe to repeat. With an idempotency key the server returns the stored result instead of charging twice." },
    { q: "A node has not answered for 5 seconds. Which statement is correct?",
      o: ["It may be crashed, paused, overloaded, or its reply lost, and you cannot tell which",
          "It has crashed, because a live node always replies within a second",
          "It is paused for garbage collection, the usual cause of silence",
          "It is overloaded, since a crashed node would refuse the connection",
          "The network has failed, because nodes themselves rarely fail"],
      a: 0,
      why: "From the sender's side every failure looks like silence. Systems design around unknown outcomes with timeouts, idempotent retries, leases and quorums." }
  ],
  "clocks-ordering": [
    { q: "Node A's clock runs 50 ms fast. A user sets their name to `Ann` on A, then 20 ms later to `Anna` on B. Last writer wins by timestamp. What is stored?",
      o: ["`Anna`, because it was written last",
          "Both values, kept as siblings for the app to merge",
          "`Ann`, because the fast clock gave the older write a larger stamp",
          "Neither, because the timestamps conflict and both are rejected",
          "Whichever value reaches the other node first over the network"],
      a: 2,
      why: "Wall clocks drift, so timestamp order is not real order. A Lamport counter carried from the first write to the second would order them correctly." },
    { q: "Which clock should you use to measure how long a request took on one machine?",
      o: ["The wall clock, corrected by NTP",
          "A Lamport clock",
          "A vector clock",
          "A hybrid logical clock",
          "A monotonic clock"],
      a: 4,
      why: "NTP can step the wall clock, even backwards, mid-request. A monotonic clock only moves forward, which is what a duration needs. Lamport and vector clocks order events, they do not measure time.",
      pair: "wall-vs-monotonic-clock" },
    { q: "Two users edit the same field at the same time on different replicas, and both edits matter. What actually solves this?",
      o: ["More accurate clocks so last writer wins picks correctly",
          "A merge rule or a CRDT, because any winner rule drops one edit",
          "A shorter replication delay between the two replicas",
          "Lamport clocks, which make one edit causally first",
          "Using GPS time on both replicas"],
      a: 1,
      why: "Concurrent writes have no true order, so last writer wins silently drops one however good the clocks. Vector clocks can detect the conflict; a merge rule resolves it." }
  ],
  "replication-leader": [
    { q: "A user changes their email; the next page load reads from a replica 300 ms behind and shows the old email. Which fix addresses this?",
      o: ["Add more replicas so reads are spread thinner",
          "Switch the replica to a larger instance type",
          "Cache the user's profile for five minutes",
          "Read from the primary for a short while after that user writes",
          "Lower the replica's priority so it is used less"],
      a: 3,
      why: "Followers lag. Reading from the primary after a write, or waiting until the replica has replayed past the user's last write position, gives read-your-writes." },
    { q: "With asynchronous replication, the leader confirms a write and crashes before any follower receives it. A follower is promoted. What happens to the write?",
      o: ["It is lost, though the client was told it succeeded",
          "The new leader fetches it from the crashed leader's disk",
          "The client's driver resends it to the new leader automatically",
          "It is recovered by read repair on the next read",
          "It is kept, because confirmation means a majority stored it"],
      a: 0,
      why: "Async replication confirms before copying, so writes not yet copied vanish on failover. Synchronous replication to at least one follower closes that gap at the cost of latency.",
      pair: "sync-vs-async-replication" },
    { q: "After a failover, the old leader comes back without knowing it was replaced and keeps accepting writes. What is this called?",
      o: ["Replication lag", "Read repair", "Split brain", "Write skew", "Livelock"],
      a: 2,
      why: "Two nodes both believe they are leader and accept writes that conflict. Fencing tokens and terms exist to make the old leader's writes rejectable." }
  ],
  "multi-leader": [
    { q: "A shared shopping list syncs between two phones. Offline, one adds `milk` and the other adds `eggs`. The list is a CRDT set. What does it hold after sync?",
      o: ["Only the edit from the phone that synced last",
          "Only the edit with the larger timestamp",
          "Neither, until a user resolves the conflict",
          "Two separate lists, one per phone",
          "Both `milk` and `eggs`, whatever order the merges happen in"],
      a: 4,
      why: "A CRDT set is built so concurrent adds always merge to the same result in any order. Last writer wins on the whole list would lose one edit." },
    { q: "Two regions each accept writes and might both sell the last seat on a flight. What is the right approach?",
      o: ["Resolve it afterwards with last writer wins",
          "Route writes for such keys to a single leader",
          "Use a CRDT counter for the seat count",
          "Shorten the replication delay between regions",
          "Let both sales stand and rely on refunds"],
      a: 1,
      why: "Conflict resolution runs after both sales happened; it cannot undo selling one seat twice. Keys that need one answer belong to one leader." }
  ],
  "leaderless-quorums": [
    { q: "A leaderless store has n = 3 replicas. Which setting guarantees that every read overlaps the latest confirmed write?",
      o: ["w = 1, r = 1", "w = 1, r = 2", "w = 2, r = 1", "w = 2, r = 2", "w = 1, r = 1 with read repair"],
      a: 3,
      why: "Overlap needs w + r > n. Only 2 + 2 = 4 exceeds 3; read repair helps convergence but gives no overlap guarantee." },
    { q: "Replicas A and B hold `x = 5` and C still holds `x = 4`. A read asks B and C. What does read repair do?",
      o: ["Returns `5` and writes `5` back to C",
          "Returns `4` because C answered first",
          "Returns both values and lets the client pick",
          "Fails the read until C catches up by itself",
          "Deletes the key on all replicas and asks the writer to retry"],
      a: 0,
      why: "The read returns the newer version and fixes the stale copy it found. Background anti-entropy repairs copies that reads never touch." },
    { q: "A team sets w + r > n and concludes the store is now linearizable. Are they right?",
      o: ["Yes, quorum overlap is the definition of linearizability",
          "Yes, as long as n is an odd number",
          "No: concurrent writes, sloppy quorums and partial failures can still show stale or conflicting values",
          "No, because quorums only apply to reads, not writes",
          "Only if read repair is turned off"],
      a: 2,
      why: "Overlap alone does not give one-copy behaviour. Tunable consistency means you choose which anomalies you accept, not that you remove them." }
  ],
  "consistency-models": [
    { q: "A user's comment appears on one reload, then vanishes on the next, because the second request hit a lagging replica. Which guarantee was broken?",
      o: ["Read-your-writes",
          "Serializability",
          "Causal consistency",
          "Linearizability of writes",
          "Monotonic reads"],
      a: 4,
      why: "Monotonic reads promises you never see time go backwards. Seeing a newer state and then an older one breaks it.",
      pair: "read-your-writes-vs-monotonic" },
    { q: "A user posts a comment and the page reloads from a replica 1 s behind, so the comment is missing and the user posts it again. Which guarantee was missing?",
      o: ["Monotonic reads",
          "Read-your-writes",
          "Eventual consistency",
          "Serializability",
          "Causal consistency between users"],
      a: 1,
      why: "Read-your-writes promises you always see your own updates. Many bugs blamed on caching are this guarantee missing after a replica read.",
      pair: "read-your-writes-vs-monotonic" },
    { q: "Which guarantee is about transactions over many objects rather than the freshness of a single object?",
      o: ["Linearizability",
          "Eventual consistency",
          "Monotonic reads",
          "Serializability",
          "Read-your-writes"],
      a: 3,
      why: "Serializability says concurrent transactions behave as if run one at a time. Linearizability is about one object behaving as a single, current copy. They are different axes.",
      pair: "linearizable-vs-serializable" }
  ],
  "cap-pacelc": [
    { q: "A database replicates synchronously between New York and London, and the network is healthy. Each write waits about 70 ms. Which idea explains that cost?",
      o: ["PACELC's else branch: with no partition you still trade latency for consistency",
          "CAP: the system chose availability over consistency",
          "CAP: a partition is in progress between the cities",
          "PACELC's partition branch: availability was lost",
          "Neither, it is a misconfiguration to fix"],
      a: 0,
      why: "CAP only speaks about partitions. PACELC adds the everyday case: when healthy, choose latency or consistency, and synchronous cross-region replication picks consistency.",
      pair: "cap-vs-pacelc" },
    { q: "What does the CAP theorem actually say?",
      o: ["Any system can have two of consistency, availability and partition tolerance",
          "Consistent systems are always slower than available ones",
          "During a partition, a system must refuse some requests or serve possibly stale data",
          "Partitions can be avoided with enough redundancy",
          "Every database is either CP or AP"],
      a: 2,
      why: "Partitions happen whether you choose them or not, so it is not pick two of three. And its definitions are narrow, so the CP and AP labels say little about real systems." }
  ],
  "consensus-raft": [
    { q: "A team plans a Raft cluster of 4 nodes instead of 3 for extra safety. What do they get?",
      o: ["Tolerance of 2 failures instead of 1",
          "Faster commits, since more nodes share the load",
          "Protection against split brain that 3 nodes lack",
          "Reads that no longer need the leader",
          "The same tolerance of 1 failure, with more cost per write"],
      a: 4,
      why: "A majority of 4 is 3, so 4 nodes survive one failure, like 3 do. Use 2f + 1 nodes: 5 for two failures." },
    { q: "Entry 42 is committed on 3 of 5 nodes, then the leader crashes. Why does the write survive the election?",
      o: ["The client resends it to whichever node wins",
          "A winner needs a majority of votes, and voters refuse candidates whose log is behind theirs",
          "The crashed leader replays it when it restarts",
          "Every follower already applied it to its state machine",
          "Raft writes every entry to shared storage first"],
      a: 1,
      why: "Any majority of votes includes a node holding entry 42, and nodes only vote for candidates at least as up to date, so the new leader has it." },
    { q: "What belongs inside a consensus group such as etcd or ZooKeeper?",
      o: ["All application data, so every write is safe",
          "Large files, so they are copied to a majority",
          "Logs and metrics, so they are ordered across nodes",
          "Small coordination data: leaders, locks, configuration",
          "Cache entries, so caches never disagree"],
      a: 3,
      why: "Every committed write needs a majority round trip, so consensus is slow by design. Keep the group small and put only coordination data in it." }
  ],
  "leases-fencing": [
    { q: "Worker A holds a lease with token 33 and stalls in a 15 s pause; the 10 s lease expires. Worker B gets token 34 and writes. Then A wakes and writes with token 33. What should happen?",
      o: ["Storage rejects A's write, because it has already seen token 34",
          "Storage accepts both writes, and the later one wins",
          "A renews its lease and B's write is rolled back",
          "The lock service kills A when it wakes",
          "Storage merges the two writes automatically"],
      a: 0,
      why: "The fencing token only ever increases, so the storage can refuse any write carrying a smaller number than one it has seen. A lease alone cannot stop a paused holder." },
    { q: "A team builds a distributed lock on Redis using only expiry times. Is it safe for correctness-critical writes?",
      o: ["Yes, if the expiry is long enough",
          "Yes, if the clocks are synced by NTP",
          "No: pauses and clock jumps can leave two holders, so the resource must check a token",
          "No, because Redis cannot store keys with expiry",
          "Only if every client renews twice per period"],
      a: 2,
      why: "Any lock based only on timing breaks when a holder pauses past its expiry. If correctness matters, the resource itself checks a fencing token or a version." }
  ],
  "two-phase-commit": [
    { q: "In two-phase commit, a participant has voted yes and then the coordinator dies. What is the participant's problem?",
      o: ["It must abort immediately to free its locks",
          "It commits alone, since it already voted yes",
          "It asks the other participants and follows the majority",
          "It loses its prepared data on restart",
          "It cannot decide alone, so it holds its locks until the coordinator returns"],
      a: 4,
      why: "Having promised to commit, it cannot abort, and without the decision it cannot commit. This blocking is the weakness of two-phase commit." },
    { q: "A booking saga reserves a flight, then a hotel, then charges a card. While it runs, another user sees the seat taken although the booking later fails. Why?",
      o: ["The saga is missing a compensation step",
          "Sagas are not isolated: other requests can see the half-finished state",
          "The flight service committed before the saga started",
          "The card charge ran before the hotel step",
          "Two-phase commit was used by mistake"],
      a: 1,
      why: "Each saga step commits locally, so others see it. Design for that, for example with a pending status, rather than expecting isolation." },
    { q: "In that saga the hotel step fails. What runs next?",
      o: ["The whole saga retries from the first step",
          "The card is charged anyway, then refunded",
          "The coordinator rolls back all steps in one transaction",
          "The compensation for each completed step, in reverse order: cancel the flight",
          "Nothing, the flight reservation expires on its own"],
      a: 3,
      why: "A saga undoes completed steps with compensating actions, newest first. There is no shared transaction to roll back.",
      pair: "saga-vs-2pc" }
  ],
  "sharding": [
    { q: "Events are range-sharded by timestamp. What happens to new writes?",
      o: ["They all land on the shard holding the newest range",
          "They spread evenly across every shard",
          "They are rejected until a new shard is created",
          "They go to a random shard and are moved later",
          "They are copied to every shard for safety"],
      a: 0,
      why: "Range sharding keeps scans fast but concentrates time-ordered writes on one shard. Hashing spreads them but scatters range scans.",
      pair: "range-vs-hash-sharding" },
    { q: "A chat app hashes `channel_id` across 16 shards. One huge channel takes a million writes a minute and its shard overloads. What helps?",
      o: ["Adding more shards, which spreads the load",
          "Switching from hash to range sharding",
          "Splitting that channel's key itself, for example by time bucket",
          "Adding read replicas to every shard",
          "Moving to consistent hashing with virtual nodes"],
      a: 2,
      why: "A hot key lives on one shard however many shards exist. The key itself has to be split." },
    { q: "Which decision is the most expensive to change once a sharded system is live?",
      o: ["The number of replicas per shard",
          "The hardware type of each node",
          "The monitoring setup for the shards",
          "The rebalancing schedule",
          "The shard key"],
      a: 4,
      why: "Changing the shard key means moving all the data. Choose it from the main access pattern so most queries touch one shard." }
  ],
  "consistent-hashing": [
    { q: "Ten cache servers use `hash(key) mod 10`. You add an eleventh. Roughly what share of keys change owner?",
      o: ["About 1 in 11", "About 91 percent", "About half", "None of them", "Exactly 10 percent"],
      a: 1,
      why: "Changing the modulus reassigns almost every key, so the cache goes cold. Consistent hashing would move only about 1/11 of them.",
      pair: "mod-n-vs-consistent-hashing" },
    { q: "Why does each physical node take many virtual nodes on a consistent hashing ring?",
      o: ["To make lookups faster",
          "To store several replicas of each key",
          "To let the ring work without a hash function",
          "To even out the slices and let bigger machines take more",
          "To stop hot keys from overloading one node"],
      a: 3,
      why: "One position per node gives uneven arcs. Many positions spread the load, and weighting the count lets a larger machine own more." },
    { q: "A key gets ten times the traffic of any other. What does consistent hashing do about it?",
      o: ["Nothing: it decides placement, and one key still lands on one node",
          "It splits the key across several nodes automatically",
          "It moves the key to the least loaded node",
          "It replicates the key to every node",
          "It adds virtual nodes until the load evens out"],
      a: 0,
      why: "Consistent hashing limits data movement when nodes change. It does nothing for one hot key, which needs its own split or cache." }
  ],
  "logs-queues": [
    { q: "An order event must reach an email service, an analytics loader and a fraud model, and analytics may need to replay last week. Which fits?",
      o: ["A queue where each message goes to one consumer",
          "Direct HTTP calls from the order service to each",
          "A log such as Kafka, with one consumer group per service",
          "A shared database table the three services poll and delete from",
          "A cron job that emails the events daily"],
      a: 2,
      why: "A log keeps messages for a retention period and each consumer group tracks its own offset, so many readers share a stream and can replay it.",
      pair: "queue-vs-log" },
    { q: "Events for the same order must be processed in order, on a Kafka topic with 12 partitions. What do you do?",
      o: ["Use one consumer for the whole topic",
          "Add a timestamp and sort in the consumer",
          "Use more partitions so each is smaller",
          "Turn on exactly-once mode",
          "Key messages by `order_id` so one order's events share a partition"],
      a: 4,
      why: "Kafka orders messages only within a partition, and the key decides the partition." },
    { q: "A consumer crashes and its group rebalances. What should the consumer code expect?",
      o: ["Some messages will be skipped for good",
          "Some messages it already processed will arrive again",
          "Messages will arrive in a new random order",
          "The producer will pause until the rebalance ends",
          "Nothing, Kafka hides rebalances from consumers"],
      a: 1,
      why: "Delivery is at-least-once unless proven otherwise: offsets committed before the crash lag the work done, so recent messages repeat. Consumers must handle duplicates." }
  ],
  "exactly-once": [
    { q: "A server checks whether an idempotency key exists, and if not, creates the charge and then stores the key. What is wrong?",
      o: ["Nothing, as long as the key is unique",
          "Keys should be generated by the server, not the client",
          "The key should be checked after the charge",
          "Two retries can both pass the check before either stores the key",
          "Idempotency keys only work for GET requests"],
      a: 3,
      why: "Insert the key in the same transaction as the effect, with a unique constraint, so only one retry can win." },
    { q: "A consumer uses Kafka's exactly-once mode and sends a welcome email for each message. Can a user get two emails?",
      o: ["Yes: exactly-once covers reads and writes within Kafka, not outside effects",
          "No, exactly-once mode guarantees each message is handled once",
          "No, because Kafka deduplicates by message key",
          "Only if the producer is not idempotent",
          "Only if the topic has more than one partition"],
      a: 0,
      why: "The email is a side effect outside Kafka's transaction. Make it idempotent on its own, for example by recording a sent marker keyed by message id." },
    { q: "Which operation is naturally idempotent, so applying a duplicate does no harm?",
      o: ["Add 10 to the balance",
          "Append a row to the payments table",
          "Set the balance to 50",
          "Increment the retry counter",
          "Send a confirmation email"],
      a: 2,
      why: "Setting a value twice gives the same result; adding or appending twice does not." }
  ],
  "load-shedding": [
    { q: "A service handles 1,000 requests per second at 50 ms, and traffic rises to 1,300. What keeps it healthiest?",
      o: ["Queue the extra requests in an unbounded buffer",
          "Raise every client's timeout to 30 seconds",
          "Serve all requests and let latency rise evenly",
          "Ask clients to retry immediately on any delay",
          "Reject the extra 300 quickly with a 503 so the rest stay at 50 ms"],
      a: 4,
      why: "Without shedding the queue grows by 300 a second and soon every request times out. Fast rejection keeps accepted work on time." },
    { q: "During an incident, every client retries failed calls three times, and load on the struggling service quadruples. What limits this?",
      o: ["Removing timeouts so clients wait longer",
          "A retry budget that caps retries as a share of traffic",
          "Retrying faster so requests finish sooner",
          "Adding more retries with the same delay",
          "Sending retries to the same instance"],
      a: 1,
      why: "Retries multiply load when the service can least afford it. Capping them, with backoff, stops clients from turning a slowdown into an outage." },
    { q: "What is the main danger of an unbounded queue in front of a busy service?",
      o: ["It loses messages when it fills",
          "It reorders requests randomly",
          "It forces producers to slow down",
          "It turns overload into minutes of latency and then a crash",
          "It makes the service reject too many requests"],
      a: 3,
      why: "An unbounded queue never pushes back, so overload hides as a growing backlog. A bounded queue gives back-pressure instead.",
      pair: "back-pressure-vs-load-shedding" }
  ],
  "tail-latency": [
    { q: "Each server answers in 10 ms at the median but 1 s at p99. A request needs replies from all of 100 servers. About what share of requests take a second or more?",
      o: ["About 63 percent", "About 1 percent", "About 10 percent", "About 99 percent", "About 37 percent"],
      a: 0,
      why: "The chance that all 100 are fast is 0.99¹⁰⁰, about 37 percent, so about 63 percent wait on at least one slow server." },
    { q: "With hedged requests, when do you send the second copy to another replica?",
      o: ["Always, to every replica at once",
          "Only after the first request has fully timed out",
          "When the first has not replied by about the 95th percentile latency",
          "Before the first, to warm the replica's cache",
          "Only for writes, never for reads"],
      a: 2,
      why: "Waiting until about p95 limits the extra load to a few percent while cutting off the slow tail. Use whichever reply arrives first." },
    { q: "A dashboard shows fleet p99 as the average of each server's own p99. What is wrong with it?",
      o: ["Nothing, it is the standard way to combine percentiles",
          "It should use the median of the p99s instead",
          "It should use the maximum of the p99s instead",
          "It needs more servers to be accurate",
          "Averaged percentiles mean nothing; merge histograms and take p99 from the result"],
      a: 4,
      why: "Percentiles do not average. Combine the underlying distributions, as histograms, then compute the percentile." }
  ]
});
