/* Multiple choice for the Frontend engineering field: 2 or 3 per topic. Checked by baseline/quiz/check.js. */
BASELINE.quiz("frontend", {
  "rendering-pipeline": [
    { q: "A slide-in panel animates `width` and stutters, while one animating `transform` stays smooth. Why?",
      o: ["`width` needs the CSSOM to be rebuilt from scratch",
          "`transform` is handled at compositing, while `width` redoes layout and paint each frame",
          "`transform` runs on a Web Worker, while `width` runs on the main thread",
          "`width` animations are throttled by the browser to save battery",
          "`transform` skips the DOM and edits pixels directly"],
      a: 1,
      why: "Compositor-only changes skip layout and paint. Geometry changes redo layout for everything they affect.",
      pair: "layout-vs-composite" },
    { q: "A loop sets an element's style and then reads `offsetHeight`, a hundred times. What is this called, and why is it slow?",
      o: ["Repaint storm: each read triggers a GPU upload",
          "Reflow caching: the browser stores a hundred layouts",
          "Style recalculation: only the CSSOM is rebuilt",
          "Layout thrashing: each read forces a synchronous layout",
          "Hydration: each read reattaches event handlers"],
      a: 3,
      why: "Reading a layout value after a style change forces the browser to lay out at once. Batch reads, then writes." },
    { q: "A page feels janky when scrolling. Where is the cause most often found?",
      o: ["Fonts loading from a slow server",
          "The HTML parser handling a large DOM",
          "The main thread busy running JavaScript",
          "The GPU struggling to paint gradients",
          "Too many CSS selectors in the stylesheet"],
      a: 2,
      why: "Most jank is JavaScript occupying the main thread, not slow painting." }
  ],
  "event-loop": [
    { q: "A click handler runs a 300 ms calculation. What does the user experience?",
      o: ["The calculation is moved to a worker automatically",
          "Input and rendering wait until it finishes, so the page feels stuck",
          "The calculation runs in parallel and the page stays smooth",
          "The browser cancels the handler after 50 ms",
          "Only animations pause; typing still appears at once"],
      a: 1,
      why: "One task runs to completion on the main thread. Anything over 50 ms is a long task that blocks input." },
    { q: "After a click task finishes, what runs before the browser gets a chance to render?",
      o: ["Only one microtask, then rendering",
          "Any pending network callbacks",
          "The next queued click handler",
          "All queued microtasks, such as promise callbacks",
          "The next timer task from `setTimeout`"],
      a: 3,
      why: "The loop runs one task, then drains the whole microtask queue, then may render.",
      pair: "task-vs-microtask" },
    { q: "A promise chain keeps scheduling new promise callbacks in a loop, never using a timer. What happens to the page?",
      o: ["Nothing, because promises are asynchronous",
          "The browser interleaves frames between each callback",
          "The chain moves to another thread after 50 ms",
          "Only network requests are delayed",
          "It can freeze, because microtasks all run before rendering"],
      a: 4,
      why: "Microtasks queued by microtasks keep running before render, so the page never paints. Yield with `setTimeout` or `scheduler.yield()`.",
      pair: "task-vs-microtask" }
  ],
  "css-layout": [
    { q: "You need a page with a header, sidebar and main area aligned in both rows and columns. Which layout fits best?",
      o: ["Absolute positioning",
          "Inline-block",
          "Grid",
          "Flexbox",
          "Floats"],
      a: 2,
      why: "Grid defines rows and columns together. Flexbox lays items along one axis.",
      pair: "flex-vs-grid" },
    { q: "A flex item holding a long URL refuses to shrink and overflows its row. What is the usual cause?",
      o: ["Flexbox cannot shrink items, only grow them",
          "The parent is missing `display: grid`",
          "`box-sizing` is set to `border-box`",
          "The item needs a higher `z-index`",
          "Its `min-width` defaults to `auto`, so it will not shrink below its content"],
      a: 4,
      why: "Most layout bugs are sizing bugs. Setting `min-width: 0` lets the item shrink." },
    { q: "A card component must switch to a stacked layout when its own column gets narrow, whatever the viewport. What fits?",
      o: ["A fixed pixel width",
          "A container query",
          "A media query on viewport width",
          "A higher specificity selector",
          "An `@layer` rule"],
      a: 1,
      why: "Container queries respond to the space a component is given; media queries respond to the viewport." }
  ],
  "components": [
    { q: "A React component copies a prop into state with `useEffect` whenever the prop changes. What is wrong?",
      o: ["It breaks server rendering of every component",
          "It should use `useState` inside the effect instead",
          "It causes an extra render and can drift; compute the value during render",
          "Nothing, this is the recommended pattern",
          "Effects cannot read props at all"],
      a: 2,
      why: "Derive data during render, handle events in handlers, and keep effects for syncing with systems outside React." },
    { q: "How do Solid's signals differ from React in finding what changed?",
      o: ["Signals update exactly the DOM that reads them, without re-running the component",
          "Signals re-run the whole app on every change",
          "Signals compare full DOM snapshots each frame",
          "Signals require a compiler that removes all JavaScript",
          "Signals only work on the server"],
      a: 0,
      why: "React re-runs a component and reconciles its output. Fine-grained signals and refs track which DOM reads which value.",
      pair: "rerender-vs-signals" }
  ],
  "state-management": [
    { q: "A list of products comes from the API and must refresh after an edit. Where should it live?",
      o: ["In a server-state cache such as TanStack Query, with invalidation",
          "In a global client store, updated by hand",
          "In `localStorage`, read on each render",
          "In a component's `useState`, fetched once",
          "In the URL query string"],
      a: 0,
      why: "Server state is a copy that can go stale, so it wants caching, deduplication and invalidation, not a store.",
      pair: "client-vs-server-state" },
    { q: "Users want the active filters to survive a reload and to share a filtered view by link. Where should the filters live?",
      o: ["In `sessionStorage`",
          "In a ref",
          "In the URL",
          "In a global store",
          "In a context provider"],
      a: 2,
      why: "State that should survive reloads or be shared belongs in the URL." },
    { q: "A component stores both `items` and `filteredItems` in state. What goes wrong over time?",
      o: ["The component renders too rarely",
          "The filtered list cannot be memoised",
          "React refuses to store arrays in state",
          "The items lose their keys",
          "Two sources of truth drift apart; derive the filtered list during render"],
      a: 4,
      why: "Store the minimum and derive the rest." }
  ],
  "routing-data-fetching": [
    { q: "A page renders, then fetches; its child then renders and fetches; then a grandchild does the same. What is this?",
      o: ["A waterfall: requests run in series instead of in parallel",
          "Streaming: data arrives in chunks as it is ready",
          "Hydration: the DOM is matched to the server output",
          "Code splitting: each level loads its own bundle",
          "Prefetching: data is loaded before it is needed"],
      a: 0,
      why: "Route loaders, server components and prefetching start requests together and early." },
    { q: "The API answers every call in 50 ms, yet the page still takes over a second. What should you look for first?",
      o: ["A larger CDN cache for the API",
          "Moving the database closer to the API",
          "A faster JSON parser in the browser",
          "Removing the router",
          "Requests that start only after another has finished, in the network panel"],
      a: 4,
      why: "A fast API behind a waterfall still gives a slow page." },
    { q: "Why do file-based routers nest layouts?",
      o: ["So routes can skip declaring their data",
          "So the History API is not needed",
          "So CSS is loaded once per route",
          "So a shared shell stays mounted while the inner page changes",
          "So every route reloads the full page"],
      a: 3,
      why: "Nested layouts keep navigation and shared UI alive across route changes." }
  ],
  "design-systems": [
    { q: "A product needs a dark mode across many teams' screens. What makes that a change in one place?",
      o: ["A separate dark build of the app",
          "Design tokens that name colours, used by every component",
          "A global stylesheet that overrides each team's CSS",
          "Copying a dark variant of every component",
          "A CSS filter that inverts the page"],
      a: 1,
      why: "Tokens are named values. Change them once and every component built on them follows." },
    { q: "A company's design system has no owner or versioning. What usually happens?",
      o: ["Accessibility improves since teams fix it locally",
          "It turns into a headless library automatically",
          "It forks into several slightly different versions of the same button",
          "It stays stable because nobody changes it",
          "Teams stop building UI altogether"],
      a: 2,
      why: "A design system is a product with users. Without owners and adoption work it fragments." },
    { q: "What does a headless component library provide?",
      o: ["Accessible behaviour and state with no styles, for teams to style with their tokens",
          "Pre-styled components that cannot be changed",
          "Server-side rendering for any framework",
          "A set of design tokens with no components",
          "Components that run without JavaScript"],
      a: 0,
      why: "Headless libraries separate behaviour from looks: focus, keyboard and state handled once, styling left to you." }
  ],
  "rendering-strategies": [
    { q: "A marketing page changes once a month and must load fast everywhere. Which rendering fits best?",
      o: ["Streaming SSR with no cache",
          "Static generation served from a CDN",
          "Client-side rendering",
          "Server-side rendering per request",
          "Rendering in a Web Worker"],
      a: 1,
      why: "SSG builds HTML once at deploy time, the fastest and cheapest option for content that rarely changes.",
      pair: "ssr-vs-ssg" },
    { q: "A personal dashboard shows each user's live data and must not be indexed by search engines. Which choice is reasonable?",
      o: ["A static page with the data baked in",
          "Prerendering every user's page at build",
          "Client-side or per-request server rendering, not a static build",
          "Static generation at deploy time",
          "Incremental static regeneration every month"],
      a: 2,
      why: "Decide by how personal the page is, how fresh it must be, and whether crawlers must read it.",
      pair: "ssr-vs-ssg" },
    { q: "After moving to SSR, content appears sooner, but users report that buttons ignore taps for a while. Why?",
      o: ["SSR speeds first paint, not interactivity; handlers attach only after hydration",
          "SSR disables event handlers by design",
          "The server sends buttons as images",
          "The CDN strips the JavaScript bundle",
          "SSR pages cannot use buttons"],
      a: 0,
      why: "The page is visible before its JavaScript loads and hydrates. Measure both first paint and interactivity." }
  ],
  "hydration": [
    { q: "A component renders `new Date().toLocaleTimeString()` on the server and again in the browser. What can happen?",
      o: ["A hydration mismatch, so React discards and re-renders that part",
          "Nothing, since React ignores text differences",
          "The server time is always kept",
          "The browser refuses to load the page",
          "The component is skipped during hydration"],
      a: 0,
      why: "Server and client must render the same output. Dates, random ids and `window` checks are the usual causes." },
    { q: "What does streaming SSR add over plain SSR?",
      o: ["It renders the page in the browser instead",
          "The shell is sent at once, and slower parts stream in as their data arrives",
          "The whole page waits for all data, then streams faster",
          "It removes the need to hydrate at all",
          "It sends JavaScript before any HTML"],
      a: 1,
      why: "`Suspense` boundaries mark pieces that can arrive later, so a slow query does not hold up the whole page.",
      pair: "streaming-vs-islands" },
    { q: "A content site has one interactive search box on otherwise static pages. Which approach avoids shipping JavaScript for the rest?",
      o: ["A service worker cache",
          "Islands, hydrating only the interactive part",
          "Full hydration of the whole page",
          "Client-side rendering of every page",
          "Streaming SSR with one boundary"],
      a: 1,
      why: "Islands hydrate only interactive regions, so static content does not ship twice.",
      pair: "streaming-vs-islands" }
  ],
  "server-components": [
    { q: "A server component imports a large markdown library to render a post. What reaches the browser?",
      o: ["The rendered result only; the library's code never ships to the client",
          "The library, so the client can render again",
          "The library, but lazily loaded on first click",
          "Nothing, server components cannot render text",
          "The source markdown, parsed in the browser"],
      a: 0,
      why: "Server components send their rendered output in a serialised form. Their code and dependencies stay on the server." },
    { q: "A server action deletes a project and is only called from an admin page. Does it need its own authorisation check?",
      o: ["No, because server code is never reachable from outside",
          "Only if it is also used by an API route",
          "Only in development builds",
          "Yes: every server action is a public endpoint anyone can call",
          "No, because only the admin page imports it"],
      a: 3,
      why: "The server and client boundary is a network boundary. Hiding the button does not protect the endpoint." },
    { q: "Why can a server component not pass a function as a prop to a client component?",
      o: ["Client components cannot accept props",
          "Functions are stripped by the bundler",
          "React forbids functions as props everywhere",
          "Only class components accept functions",
          "Props crossing the boundary must be serialisable, and plain functions are not"],
      a: 4,
      why: "Data crosses a network boundary, so it must serialise. Server actions are the exception made for calling the server." }
  ],
  "web-vitals": [
    { q: "A page's INP is poor. Where should you look first?",
      o: ["Large web fonts",
          "Long JavaScript tasks that delay the next frame after input",
          "A hero image that loads late",
          "Ads that push content down",
          "A slow server response time"],
      a: 1,
      why: "INP is nearly always long tasks on the main thread. LCP points at late images; CLS at space not reserved.",
      pair: "inp-vs-lcp" },
    { q: "LCP is slow, and the largest element is a hero image set as a CSS background. What is the likely cause?",
      o: ["The page has too many event handlers",
          "The layout shifts after the image loads",
          "The image uses a modern format",
          "The browser discovers the image late, since it is hidden in CSS",
          "The image is too wide for the viewport"],
      a: 3,
      why: "LCP is often an image found late, lazy-loaded or set in CSS. Make it discoverable in the HTML.",
      pair: "inp-vs-lcp" },
    { q: "Lighthouse scores a page 98, but Search Console reports poor Core Web Vitals. Which counts?",
      o: ["Neither, since vitals only matter on desktop",
          "The median of lab runs on a fast laptop",
          "Field data from real visits, judged at the 75th percentile",
          "The Lighthouse score, because it is reproducible",
          "Whichever number is higher"],
      a: 2,
      why: "Lab tools catch regressions; real-user field data is what the vitals are judged on." }
  ],
  "bundles": [
    { q: "Why do bundlers put content hashes in output file names?",
      o: ["So the dev server starts faster",
          "So source maps are generated",
          "So files can be cached for a year and replaced by changing the name",
          "So the browser can verify the files are not tampered with",
          "So tree shaking can find unused exports"],
      a: 2,
      why: "A changed file gets a new name, so long cache lifetimes never serve stale code." },
    { q: "A charting library is used only on the reports page. How do you stop every page paying for it?",
      o: ["Minify it more aggressively",
          "Load it from a CDN with a script tag",
          "Mark it as a dev dependency",
          "Inline it into the HTML",
          "A dynamic `import()` so it is split out and loaded on that route"],
      a: 4,
      why: "Code splitting breaks the output at dynamic imports, so heavy code loads only when needed." },
    { q: "A bundle feels fine on a MacBook but INP is poor on users' phones. Why?",
      o: ["Phones download JavaScript over a slower protocol",
          "Mobile browsers skip tree shaking",
          "Phones cannot cache hashed files",
          "Mobile GPUs cannot composite layers",
          "JavaScript must be parsed and run on the main thread, several times slower on a mid-range phone"],
      a: 4,
      why: "JavaScript costs more than its download. Test on an average Android phone, not a laptop." }
  ],
  "accessibility": [
    { q: "A clickable `<div>` opens a menu. What does a keyboard or screen reader user miss compared with a `<button>`?",
      o: ["Only the visual hover style",
          "Nothing, if the div has an onclick handler",
          "Only colour contrast",
          "Only the tooltip text",
          "Focus, Enter and Space activation, and being announced as a button"],
      a: 4,
      why: "Native elements carry role, name, state and keyboard behaviour for free. A div carries none of it." },
    { q: "A team adds ARIA roles to every element to be safe. What is the risk?",
      o: ["ARIA is ignored by every screen reader",
          "ARIA breaks CSS selectors",
          "There is no risk, more ARIA is better",
          "Wrong ARIA misleads assistive tech and can be worse than none",
          "ARIA slows page rendering noticeably"],
      a: 3,
      why: "ARIA patches the accessibility tree when no native element fits. Used wrongly, it lies to screen readers." },
    { q: "An automated checker reports no accessibility issues. What still needs testing?",
      o: ["Only colour contrast ratios",
          "Only the page title",
          "Only image alt text",
          "Keyboard and screen reader use, which tools only partly cover",
          "Nothing, the checker covers WCAG fully"],
      a: 3,
      why: "Automated tools catch only part of the problems. Focus order, dialogs and meaning need a person." }
  ],
  "testing-frontend": [
    { q: "A test finds a button by its CSS class and checks internal state after clicking. What is the problem?",
      o: ["It needs a real browser to work",
          "Nothing, this is the recommended style",
          "It tests implementation, so a harmless refactor breaks it",
          "It runs too fast to be reliable",
          "It cannot run in a simulated DOM"],
      a: 2,
      why: "Find elements by role, label or text and assert on what the user sees, so tests survive refactors." },
    { q: "Large markup snapshot tests keep failing on harmless changes. What usually happens next?",
      o: ["They speed up the test suite",
          "They replace the need for end-to-end tests",
          "They become stable after a few weeks",
          "People update them without reading, so they stop catching anything",
          "They catch more real bugs over time"],
      a: 3,
      why: "Snapshots that churn get rubber-stamped. Test behaviour instead." },
    { q: "Which flows deserve end-to-end tests in a real browser?",
      o: ["Only error states",
          "None, unit tests are enough",
          "The few that matter most, such as sign-up and checkout",
          "Every component in the design system",
          "Every CSS change"],
      a: 2,
      why: "End-to-end tests are slow and broad. Keep them for critical flows, and use component tests for the rest." }
  ],
  "web-apis": [
    { q: "A chat UI should show a model's tokens as they arrive. What makes that possible?",
      o: ["Storing tokens in `localStorage`",
          "A Web Worker that touches the DOM",
          "Waiting for the full JSON response",
          "Reading a `fetch` response body as a stream, chunk by chunk",
          "Polling the server every second"],
      a: 3,
      why: "A streaming response can be read incrementally, so text appears as it arrives." },
    { q: "Why is `localStorage` a poor place for an auth token?",
      o: ["Any script on the page can read it, so XSS can steal it",
          "It is cleared on every page load",
          "It is sent with every request like a cookie",
          "It cannot store strings",
          "It is limited to one value per site"],
      a: 0,
      why: "It is synchronous and readable by any script. An `HttpOnly` cookie keeps the token out of JavaScript's reach.",
      pair: "localstorage-vs-cookie" },
    { q: "Which tool lets a page work offline by caching responses between the page and the network?",
      o: ["`sessionStorage`",
          "A service worker",
          "A Web Worker",
          "IndexedDB on its own",
          "A cookie"],
      a: 1,
      why: "Service workers intercept requests and can serve cached responses. Web Workers only run scripts off the main thread.",
      pair: "service-worker-vs-web-worker" }
  ],
  "browser-security": [
    { q: "A chat app renders an LLM's markdown reply as raw HTML. What is the risk?",
      o: ["CORS errors when the reply loads images",
          "Nothing, since the model wrote it, not a user",
          "Layout shift from long replies",
          "XSS: injected markup or script runs in the user's session",
          "CSRF: the reply submits forms for the user"],
      a: 3,
      why: "Model output is user input. A prompt injection can produce a script on purpose. Sanitise before rendering HTML." },
    { q: "React escapes text by default. Where does XSS risk gather in a React app?",
      o: ["In every `useState` call",
          "In CSS modules",
          "In server components only",
          "In `key` props on lists",
          "At escape hatches such as `dangerouslySetInnerHTML` and `javascript:` links"],
      a: 4,
      why: "Frameworks are safe by default; the bugs live where you bypass the default." },
    { q: "What does a strict, nonce-based Content Security Policy do when an attacker manages to inject a script tag?",
      o: ["The script does not run, since it lacks the per-response nonce",
          "It sanitises the script's contents",
          "It logs the user out at once",
          "It blocks the request that delivered it",
          "It removes the script from the DOM after it runs"],
      a: 0,
      why: "CSP is a second layer: even if injection happens, scripts without the nonce are refused." }
  ],
  "cors-csrf": [
    { q: "A malicious site submits a form to your API, and the browser attaches the user's cookies. Why did CORS not stop it?",
      o: ["CORS stops reading the response, not sending the request",
          "CORS only applies to images",
          "The attacker disabled CORS in their browser",
          "CORS only applies to GET requests",
          "The API was missing a CORS header"],
      a: 0,
      why: "CSRF exploits that gap. Defend with `SameSite` cookies, CSRF tokens and checking `Origin` or `Sec-Fetch-Site`.",
      pair: "cors-vs-csrf" },
    { q: "A frontend gets a CORS error calling your API. Where is it fixed?",
      o: ["In the DNS records of the frontend",
          "On the server, by sending the right `Access-Control-Allow-Origin`",
          "In the browser, with a CORS-disabling extension",
          "In the frontend, by adding `mode: no-cors`",
          "By switching the request to XMLHttpRequest"],
      a: 1,
      why: "CORS is the server relaxing the same-origin policy. The browser enforces it; the server decides." },
    { q: "A server echoes back whatever `Origin` a request sends, with credentials allowed. What does that do?",
      o: ["Nothing harmful, since cookies are still required",
          "Blocks all cross-origin requests",
          "Disables preflight requests",
          "Only affects requests from localhost",
          "Lets any site read authenticated responses from your API"],
      a: 4,
      why: "Wildcards cannot be combined with credentials, and echoing any origin to get around that opens the API to every site.",
      pair: "cors-vs-csrf" }
  ]
});
