/* Multiple choice for the Inference field: 2 or 3 per topic. Checked by baseline/quiz/check.js. */
BASELINE.quiz("inference", {
  "what-is-inference": [
    { q: "A team doubles the batch size. Throughput rises 60%, but p95 latency now misses the product's target. What have they gained?",
      o: ["A 60% cost saving, since cost per token fell", "Lower latency for most users, since the GPU is busier",
          "Nothing usable: tokens served outside the latency target do not count", "Better answers, since larger batches average out errors",
          "A free win, since batch size does not affect each request's latency"],
      a: 2,
      why: "The job is the lowest cost that still meets the latency target. Throughput bought by breaking the target is not useful tokens." },
    { q: "Which of these levers sits at the runtime level, rather than the model or the infrastructure level?",
      o: ["The engine's batching and caching policy", "Switching to a distilled 8B model", "Moving replicas to a region nearer users",
          "Quantizing the weights to 4 bits", "Buying GPUs with more memory"],
      a: 0,
      why: "Model levers change the model (size, distillation, quantization, a draft model); runtime levers are the engine's batching, caching and kernels; infrastructure is GPUs, regions and scaling." },
    { q: "Quantizing a model cut the cost per million tokens by 40%, but answers on the team's own eval got clearly worse. How should the saving be judged?",
      o: ["As a 40% saving, since cost per token is the metric", "As a saving, since perplexity is the quality measure that counts",
          "As a latency regression, since quantized models decode slower", "As neutral, since quality and cost are unrelated",
          "As not yet a saving, since worse answers are not the same tokens"],
      a: 4,
      why: "Useful tokens is the honest unit. A cheaper model that answers worse has moved cost into quality, not removed it." }
  ],
  "prefill-decode": [
    { q: "Why is decode memory-bound while prefill is compute-bound?",
      o: ["Decode multiplies larger matrices than prefill does", "Each decode step reads every weight to produce one token per sequence",
          "Prefill skips the KV cache, so it reads far less memory", "Decode runs on the CPU while prefill runs on the GPU",
          "Prefill uses 8-bit weights while decode uses 16-bit"],
      a: 1,
      why: "Prefill multiplies thousands of prompt tokens against each weight it reads; decode reads all the weights to make one token per sequence, so the maths units wait on memory." },
    { q: "An 8B model in 16-bit (about 16 GB) runs on a GPU that reads memory at about 3.35 TB/s. Roughly what is the ceiling on one sequence's decode speed?",
      o: ["About 20 tokens per second", "About 2,000 tokens per second", "About 20,000 tokens per second",
          "About 200 tokens per second", "No ceiling, since it depends only on FLOPS"],
      a: 3,
      why: "Each token needs one full read of the weights: 3.35 TB/s ÷ 16 GB ≈ 200 reads, so about 200 tokens per second for a single sequence." },
    { q: "On a shared GPU, everyone's token stream freezes for a moment whenever one user submits a very long document. What is happening?",
      o: ["A large prefill occupies the GPU and stalls the batch's decode steps", "The KV cache of every user is evicted to the CPU",
          "The long document forces the model to recompile", "Decode is compute-bound, so long outputs block others",
          "The tokenizer is single-threaded and blocks the batch"],
      a: 0,
      why: "The two phases interfere on one GPU. Chunked prefill splits the long prompt into pieces mixed with decode steps; disaggregation moves prefill to other GPUs.",
      pair: "chunked-prefill-vs-disaggregation" }
  ],
  "kv-cache": [
    { q: "A model has 32 layers and 8 KV heads of dimension 128, stored in 16-bit. About how much KV cache does one token need?",
      o: ["About 8 KiB", "About 32 KiB", "About 128 KiB", "About 1 MiB", "About 16 MiB"],
      a: 2,
      why: "2 (K and V) x 32 layers x 8 heads x 128 dims x 2 bytes is 131,072 bytes, 128 KiB. An 8,000-token conversation then needs about 1 GiB." },
    { q: "Requests on the same GPU and model now use twice the context length. What happens to how many requests fit at once?",
      o: ["It stays the same, since the weights dominate memory", "It doubles, since longer prompts batch better",
          "It falls slightly, since only compute rises", "It stays the same, since PagedAttention removes the limit",
          "It roughly halves, since KV memory per request doubles"],
      a: 4,
      why: "Long context is a memory problem first: KV memory grows with every token, so doubling context halves the requests that fit, and with them throughput." },
    { q: "Why does grouped-query attention let more requests fit on a GPU?",
      o: ["It skips attention on half of the layers", "Several query heads share one set of keys and values, so less is stored",
          "It moves the KV cache into CPU memory", "It quantizes the weights to 8 bits",
          "It removes the need for a KV cache at decode"],
      a: 1,
      why: "The KV cache size scales with the number of KV heads. Llama 3 uses 8 KV heads for 32 query heads, ¼ of the cache full multi-head attention would need." }
  ],
  "roofline": [
    { q: "Decode at batch size 1 has an arithmetic intensity near 1 operation per byte, and the GPU's ridge point is near 300. What follows?",
      o: ["The GPU is compute-bound and needs faster tensor cores", "The workload is balanced and close to peak efficiency",
          "More FLOPS would speed it up in proportion", "Memory bandwidth starves the GPU, and batching raises intensity",
          "Only quantizing the activations can help"],
      a: 3,
      why: "Far below the ridge, the GPU waits on memory. Batching lets one read of the weights serve many sequences, which raises operations per byte." },
    { q: "In roofline terms, why do both weight quantization and FlashAttention speed up what they target?",
      o: ["Both cut the bytes moved through memory", "Both reduce the number of FLOPs performed", "Both raise the GPU's clock speed",
          "Both remove the need for a KV cache", "Both move work from the GPU to the CPU"],
      a: 0,
      why: "Decode and attention are limited by memory traffic. Fewer bytes per weight, or never writing the score matrix to HBM, moves them closer to the compute limit." },
    { q: "For long-context chat serving, you compare an 80 GB GPU and a 141 GB GPU with similar FLOPS. What usually decides it?",
      o: ["Peak TFLOPS, since serving is compute-bound", "The count of CUDA cores on each card", "Memory capacity, since it sets how much KV cache fits",
          "The PCIe generation of the host", "The base clock speed of each card"],
      a: 2,
      why: "Spec-sheet FLOPS are peaks that kernels rarely reach. HBM capacity decides how many tokens of KV cache fit, which decides batch size and throughput." }
  ],
  "metrics": [
    { q: "A voice agent starts speaking as soon as the first words arrive. Which metric matters most?",
      o: ["Throughput per GPU", "Time per output token", "Total tokens per request", "Goodput across the batch", "Time to first token"],
      a: 4,
      why: "Speech can begin with the first words, so the wait before the first token is what the caller hears as silence.",
      pair: "ttft-vs-tpot" },
    { q: "TTFT is 400 ms and TPOT is 25 ms. Roughly how long until a 200-token answer finishes?",
      o: ["About 0.4 s", "About 5.4 s", "About 25 s", "About 80 s", "About 2.5 s"],
      a: 1,
      why: "End-to-end latency is about TTFT + output length × TPOT: 0.4 s + 200 × 0.025 s = 5.4 s." },
    { q: "A vendor quotes a p50 TTFT of 150 ms measured at one request per second. You expect 50 requests per second. What can you conclude?",
      o: ["Your p50 will also be about 150 ms", "Your p99 will be about double, near 300 ms", "TTFT does not change with load",
          "Little: you need percentiles measured under your own load", "TTFT will fall at higher load thanks to batching"],
      a: 3,
      why: "TTFT includes queueing, which grows with load. A median at one request per second says nothing about the tail at the traffic you expect." }
  ],
  "benchmarking": [
    { q: "A benchmark sweeps concurrency from 1 to 256. Throughput climbs then flattens while latency keeps rising. Where is the operating point?",
      o: ["The highest concurrency where latency still meets the target", "The concurrency with the highest throughput",
          "Concurrency 1, where latency is lowest", "Where throughput first flattens, whatever the latency",
          "The concurrency where GPU utilisation reads 100%"],
      a: 0,
      why: "The curve trades latency for throughput. You take as much throughput as you can while still meeting the latency target." },
    { q: "Engine A beats engine B on a published benchmark that sends the same prompt over and over. Why be suspicious?",
      o: ["Repeated prompts slow engines that have prefix caching", "Repeated prompts force longer outputs than real traffic",
          "Repeated prompts flatter engines that have prefix caching", "Repeated prompts turn off continuous batching",
          "Repeated prompts measure only the decode phase"],
      a: 2,
      why: "With repeated prompts the prefix cache hits every time and prefill disappears. Your traffic will not look like that, so ask what a published number assumed." },
    { q: "After switching to FP8 weights, throughput rose 40% on the benchmark. What else must the benchmark check?",
      o: ["That the GPU clock stayed constant", "That the tokenizer version did not change", "That TTFT stayed exactly identical",
          "That every prompt had equal length", "That output quality on real tasks held up"],
      a: 4,
      why: "Speed without quality is not a gain. Check answers on your own tasks alongside speed whenever quantization or decoding changes." }
  ],
  "continuous-batching": [
    { q: "With static batching, one batch holds a 2,000-token answer and seven 50-token answers. What happens?",
      o: ["All eight finish together, early", "The seven short slots sit idle until the long answer ends",
          "The long answer is cut to fit the batch", "The short answers are recomputed each step",
          "New requests join as soon as a short answer ends"],
      a: 1,
      why: "Static batching runs until every member finishes, so short answers waste their slots and new requests wait for the whole batch." },
    { q: "What does continuous batching change compared with static batching?",
      o: ["It batches only requests with equal prompt lengths", "It runs prefill and decode on separate GPUs",
          "It splits the weights across GPUs on every step", "It schedules per decode step, refilling a finished slot next iteration",
          "It waits for a full batch before it starts"],
      a: 3,
      why: "Scheduling at the level of single decode steps (the Orca idea) keeps the GPU full and lets short requests leave early." },
    { q: "An operator raises the scheduler's maximum batch size. What should they expect?",
      o: ["Higher throughput and slower per-request latency", "Higher throughput and faster per-request latency",
          "Lower throughput and faster per-request latency", "No change, since continuous batching ignores the limit",
          "Lower memory use for each request"],
      a: 0,
      why: "Bigger batches always trade per-request latency for throughput; the scheduler's limits are the dial for where you sit on that curve." }
  ],
  "paged-attention": [
    { q: "What problem in earlier engines did PagedAttention solve?",
      o: ["Attention ran in 32-bit, wasting compute", "Weights were reloaded from disk for every request",
          "KV memory was reserved in one block for the longest output and mostly wasted", "Decode steps could not be batched across requests",
          "Prompts had to be padded to one length on the CPU"],
      a: 2,
      why: "Contiguous reservations sized for the maximum output sat mostly empty and fragmented memory. Small blocks allocated on demand bring waste near zero." },
    { q: "A workload with 128K-token contexts still runs out of GPU memory after moving to vLLM. Why?",
      o: ["vLLM caps contexts at a fixed small length", "PagedAttention makes each token's KV entry larger",
          "Paging moves the KV cache to disk, which fills it", "Block tables use more memory than the cache itself",
          "Paging removes waste, but the full KV cache must still fit"],
      a: 4,
      why: "Paging fixes waste, not size. It lets you use all of the GPU's memory, never more than it has." },
    { q: "Eight parallel samples are drawn from one prompt under PagedAttention. How is the prompt's KV cache held?",
      o: ["Copied eight times before decoding starts", "Shared through block tables, copied only when a sequence writes",
          "Recomputed for each sample at every step", "Stored once on the CPU and streamed per step",
          "Dropped after the first sample finishes"],
      a: 1,
      why: "Block tables map each sequence's logical positions to physical blocks, so sequences can point at the same blocks and copy on write." }
  ],
  "prefix-caching": [
    { q: "An agent's prompt starts with the current timestamp, then a 3,000-token system prompt and tool definitions. Prefix cache hits are near zero. What fixes it?",
      o: ["Raise the prefix cache's memory limit", "Shorten the system prompt by half", "Switch from RadixAttention to PagedAttention",
          "Move the timestamp after the stable content", "Turn off continuous batching"],
      a: 3,
      why: "A hit needs an exact token prefix. Anything that changes per request must come last, or every request has a new prefix from the first token." },
    { q: "Ten replicas with prefix caching sit behind a round-robin load balancer. Multi-turn chats show poor TTFT. Why?",
      o: ["Later turns land on replicas that do not hold the chat's cached prefix", "Round robin turns off prefix caching in the engine",
          "Prefix caching works only with a single replica", "Each replica evicts its cache after every request",
          "Turns of one chat cannot share a prefix"],
      a: 0,
      why: "Across replicas, the router must send a request to the replica that already holds its prefix (KV-aware routing), or the cache is wasted." },
    { q: "When a request hits the prefix cache, what work is skipped?",
      o: ["Decoding of the shared tokens", "Tokenization of the whole prompt", "Prefill of the cached prefix tokens",
          "Sampling of the first output token", "Loading of the model weights"],
      a: 2,
      why: "The KV cache for those tokens already exists, so their prefill is skipped and TTFT and compute drop." }
  ],
  "engines": [
    { q: "You need to run a quantized model on a laptop with Apple silicon and no NVIDIA GPU. Which engine fits?",
      o: ["TensorRT-LLM with FP8", "vLLM on CUDA", "NVIDIA Dynamo across nodes", "SGLang with FP4 kernels", "llama.cpp with a GGUF file"],
      a: 4,
      why: "llama.cpp is a C/C++ engine with few dependencies that runs quantized GGUF models on CPUs, Apple silicon and consumer GPUs." },
    { q: "A blog post ranks engine X as the fastest. How should you choose an engine?",
      o: ["Pick X, since rankings hold across releases", "Benchmark the candidates on your model and traffic, on current versions",
          "Pick the engine with the most GitHub stars", "Pick whichever supports the most model families",
          "Pick the one with the smallest default batch size"],
      a: 1,
      why: "Rankings flip between versions and workloads, and releases ship every few weeks. Only your model and traffic answer the question." },
    { q: "What role does NVIDIA Dynamo play relative to vLLM, SGLang or TensorRT-LLM?",
      o: ["It replaces them with its own attention kernels", "It is a quantization format for their weights",
          "It is a tokenizer shared between them", "It coordinates their workers across nodes, with disaggregation and KV-aware routing",
          "It runs them on CPUs when the GPUs are busy"],
      a: 3,
      why: "Dynamo is an orchestration layer above the engines; the engines still do the batching and kernels on each worker." }
  ],
  "quantization": [
    { q: "A team applies weight-only INT4 quantization. Which phase speeds up most?",
      o: ["Decode at small batch, since fewer weight bytes are read per token", "Prefill, since its maths now runs in 4-bit",
          "Prefill and decode equally, since all compute shrinks", "Neither, since only memory capacity changes",
          "Tokenization, since the vocabulary shrinks"],
      a: 0,
      why: "Weight-only quantization cuts bytes read, which is what limits decode. The maths still runs in 16-bit, so compute-bound prefill gains little.",
      pair: "weight-only-vs-fp8" },
    { q: "Why does FP8 weights-and-activations quantization speed up prefill when weight-only INT4 does not?",
      o: ["FP8 stores fewer bytes per weight than INT4", "FP8 removes the KV cache from prefill",
          "The maths itself runs on faster low-precision tensor cores", "FP8 skips some layers during prefill",
          "INT4 weights cannot be batched"],
      a: 2,
      why: "Quantizing activations too lets the matrix multiplies run in FP8 on tensor cores built for it, which helps the compute-bound phase.",
      pair: "weight-only-vs-fp8" },
    { q: "A quantized model's perplexity barely moved. What should you still check before shipping it?",
      o: ["Nothing more, since perplexity captures task quality", "The model file's size on disk", "Throughput at batch size 1 only",
          "The tokenizer's vocabulary size", "Your own tasks, especially maths, code and long context"],
      a: 4,
      why: "Quality loss from quantization is uneven. Perplexity can hold while maths, code or long-context answers degrade." }
  ],
  "speculative-decoding": [
    { q: "Why can speculative decoding give the same output distribution as the big model alone?",
      o: ["The draft model was trained on the big model's outputs", "A rejection-sampling rule accepts drafts only as the big model's distribution allows",
          "The big model regenerates every drafted token itself", "Drafts are used only at temperature zero",
          "The draft and the big model share their weights"],
      a: 1,
      why: "The big model scores the drafted tokens in one pass and a rejection-sampling rule keeps the longest agreeing prefix, which makes the result match the big model's distribution." },
    { q: "Speculative decoding gave a 2.5x speedup at low traffic but almost nothing at peak. Why?",
      o: ["The draft model's cache is evicted at peak", "Drafts become less accurate under load",
          "Rejection sampling is switched off at large batch", "At large batch the GPU is no longer idle, so verification competes with real work",
          "Prefix caching turns off when speculation is on"],
      a: 3,
      why: "Speculation spends the spare compute of memory-bound decode. A big batch already uses that compute, so the gain shrinks or disappears." },
    { q: "Which workload gains most from n-gram drafting, which copies likely continuations from the prompt?",
      o: ["Editing a code file where most of the output repeats the input", "Writing an original poem at high temperature",
          "Classifying a sentence into one of five labels", "Producing embeddings for search",
          "Transcribing audio with an encoder-decoder model"],
      a: 0,
      why: "Speedup depends on how predictable the text is. Edits repeat long stretches of the prompt, so copied drafts are usually accepted." }
  ],
  "attention-kernels": [
    { q: "You swap standard attention for FlashAttention. What changes about the outputs?",
      o: ["They become approximate, within a few percent", "They improve, since softmax becomes more stable",
          "They match up to floating-point rounding", "They differ only for sequences over a few thousand tokens",
          "They degrade slightly, like 8-bit quantization"],
      a: 2,
      why: "FlashAttention is exact: it changes how attention is computed, not what is computed." },
    { q: "Where does FlashAttention's speedup come from?",
      o: ["Fewer FLOPs, by skipping low-scoring tokens", "Replacing softmax with a cheaper function", "Running attention on the CPU in parallel",
          "Storing the score matrix in 8-bit", "Tiles in on-chip SRAM, so the score matrix never goes to HBM"],
      a: 4,
      why: "Naive attention's cost is memory traffic for the n by n matrix. Computing softmax per tile on chip saves traffic, not FLOPs." },
    { q: "At batch size 1, a model is slow partly because of many tiny GPU kernel launches. Which technique targets that?",
      o: ["Tensor parallelism", "Capturing CUDA graphs", "Prefix caching", "Pipeline parallelism", "KV cache quantization"],
      a: 1,
      why: "A CUDA graph records a sequence of kernel launches once and replays it, cutting launch overhead that dominates at small batch." }
  ],
  "parallelism": [
    { q: "Why does tensor parallelism usually stay inside one 8-GPU node?",
      o: ["It needs a full copy of the weights on each GPU", "It works only for mixture-of-experts models",
          "It adds idle pipeline bubbles across nodes", "Every layer ends with an all-reduce that needs fast links such as NVLink",
          "It cannot split the attention layers"],
      a: 3,
      why: "Splitting each matrix means combining partial results every layer. That traffic is cheap over NVLink and slow between nodes.",
      pair: "tensor-vs-pipeline" },
    { q: "DeepSeek-V3 has 671B parameters but activates about 37B per token. What follows for serving it?",
      o: ["Compute per token is modest, but many GPUs are needed to hold it", "It fits on one GPU, since only 37B are active",
          "Each token costs the compute of all 671B parameters", "It cannot use expert parallelism",
          "Its KV cache is about 18× smaller than a dense model's"],
      a: 0,
      why: "Mixture of experts makes each token cheap to compute, yet every expert must sit in some GPU's memory, which is why expert parallelism spreads them out." },
    { q: "A model fits on 2 GPUs with room for its KV cache, and you have 8 GPUs. What is usually the better setup?",
      o: ["One replica with tensor parallelism across all 8", "One replica with pipeline parallelism across all 8",
          "Four replicas of 2 GPUs each behind a load balancer", "Eight replicas of 1 GPU, with the model split by layer",
          "Two replicas of 4 GPUs using expert parallelism"],
      a: 2,
      why: "Communication grows with the split, so the smallest number of GPUs that fits the model and its cache, replicated, is often best." }
  ],
  "disaggregation": [
    { q: "In disaggregated serving, what moves from prefill workers to decode workers?",
      o: ["The model weights", "The tokenized prompt alone", "The sampled output tokens", "The router's queue state",
          "The KV cache that prefill produced"],
      a: 4,
      why: "Prefill builds the KV cache, then ships it over a fast interconnect so decode can continue without redoing the prompt." },
    { q: "A startup serves one model on four GPUs with moderate prompts. TTFT and streams stall when long prompts arrive. What should they try first?",
      o: ["Full disaggregation over InfiniBand", "Chunked prefill on the shared GPUs", "Pipeline parallelism across nodes",
          "Turning off continuous batching", "Doubling the maximum batch size"],
      a: 1,
      why: "Disaggregation pays at scale with long prompts and strict targets. At small scale, chunked prefill gets much of the benefit without moving KV caches.",
      pair: "chunked-prefill-vs-disaggregation" },
    { q: "In a disaggregated setup, which latency target does each pool tune for?",
      o: ["Both pools tune for throughput only", "Prefill for TPOT, decode for TTFT", "Both pools tune for TTFT",
          "Prefill for TTFT, decode for TPOT", "Prefill for cost, decode for quality"],
      a: 3,
      why: "Prefill produces the first token, so it owns TTFT; decode produces every token after, so it owns TPOT.",
      pair: "ttft-vs-tpot" }
  ],
  "autoscaling": [
    { q: "Why is GPU utilisation a poor autoscaling signal for LLM serving?",
      o: ["It can read busy while the queue is fine, or moderate while it overflows", "NVIDIA drivers do not expose it",
          "It always reads 100% during decode", "It measures only prefill, not decode", "It lags by several hours"],
      a: 0,
      why: "Utilisation does not track whether users are waiting. In-flight requests or queue depth per replica lead the problem instead." },
    { q: "Latency is already over target when the autoscaler adds a replica. Why does it not help for minutes?",
      o: ["Load balancers wait an hour before routing to it", "The new replica must first train its tokenizer",
          "Cold start: get a node, pull the image, load weights, warm up", "Replicas must sync KV caches with their peers",
          "The autoscaler adds CPUs rather than GPUs"],
      a: 2,
      why: "Loading tens to hundreds of gigabytes of weights and warming up takes a minute or more, so scale on a leading signal and scale up early." },
    { q: "A user-facing assistant is set to scale to zero overnight. What does that cost?",
      o: ["Weights are corrupted on restart", "Prefix caches survive but run slower", "A higher per-token price during the day",
          "Nothing, since scale to zero is free", "The first morning request waits through a cold start"],
      a: 4,
      why: "Scale to zero saves money and charges it back as a cold start. For user-facing work, keep a warm minimum and budget for it." }
  ],
  "modalities": [
    { q: "Which serving profile matches an embedding model?",
      o: ["Decode only, memory-bound", "Prefill only, with no decode", "Prefill then a long decode, like chat",
          "Many denoising steps, compute-bound", "An encoder then an autoregressive decoder"],
      a: 1,
      why: "An embedding model runs one forward pass over the input and returns a vector; it never generates tokens." },
    { q: "A text-to-speech model has a real-time factor of 1.3. What does that mean?",
      o: ["Audio starts 1.3 s after the request", "It runs 1.3× faster than real time", "It uses 1.3 GB per stream",
          "It needs 1.3 s of compute per second of audio, so it falls behind", "It produces 1.3 tokens per audio frame"],
      a: 3,
      why: "Real-time factor is compute time per second of audio. Above 1 the stream cannot keep up; it must stay well under 1." },
    { q: "Why is batching harder for streaming audio than for text?",
      o: ["Each user produces audio in real time, so waiting to fill a batch adds latency per stream", "Audio models cannot run on GPUs",
          "Audio tokens are larger than text tokens", "Audio needs 32-bit precision throughout", "Audio models keep no KV cache"],
      a: 0,
      why: "Audio arrives at the speed of speech. Holding chunks to batch them delays every stream, so the latency and efficiency trade is struck differently." }
  ]
});
