/* Multiple choice for the Machine learning field: 2 or 3 per topic. Checked by baseline/quiz/check.js. */
BASELINE.quiz("ml", {
  "learning-paradigms": [
    { q: "BERT was trained by hiding words in a sentence and predicting them. Which kind of learning is that?",
      o: ["Supervised, since each hidden word is a label",
          "Unsupervised, since no person labelled anything",
          "Self-supervised: the labels are made from the data itself",
          "Reinforcement learning, since predictions are rewarded",
          "Semi-supervised, since only some words are hidden"],
      a: 2,
      why: "Self-supervised learning manufactures labels by hiding part of the input; that free label is why it scales to web-sized data.",
      pair: "self-vs-unsupervised" },
    { q: "An interviewer asks whether a chat model like Claude is trained with supervised learning or reinforcement learning. Best answer?",
      o: ["Supervised, since it learns from human-written text",
          "Reinforcement learning, since it is tuned on preferences",
          "Unsupervised, since pretraining has no labels",
          "It depends on the stage: self-supervised pretraining, supervised instruction tuning, RL preference tuning",
          "Neither: it is trained by retrieval over its corpus"],
      a: 3,
      why: "The lines blur across stages of one model. Say which stage you mean." },
    { q: "A game bot gets no correct move to copy, only a score at the end of each game. Which kind of learning fits?",
      o: ["Supervised learning on past moves",
          "Unsupervised clustering of game states",
          "Self-supervised prediction of the next frame",
          "Contrastive learning on pairs of games",
          "Reinforcement learning from the reward"],
      a: 4,
      why: "Reinforcement learning has no right answer to copy, only a reward after acting." }
  ],
  "loss-functions": [
    { q: "A classifier gives the true class a probability of 0.01. What does cross-entropy do with that example?",
      o: ["Gives a large loss, −log 0.01",
          "Gives a small loss, since it is one example",
          "Gives the same loss as a 0.5 prediction",
          "Gives zero loss, since the model was confident",
          "Ignores it, since the prediction was wrong"],
      a: 0,
      why: "Cross-entropy is −log p, where p is the probability on the right class, so a confident wrong answer costs a lot." },
    { q: "Why train a classifier on cross-entropy but report accuracy?",
      o: ["Cross-entropy is faster to compute than accuracy",
          "Accuracy is not differentiable, so it gives no useful gradient",
          "Accuracy overfits more than cross-entropy",
          "Cross-entropy is easier for managers to read",
          "Accuracy needs a validation set and cross-entropy does not"],
      a: 1,
      why: "The loss is what training can optimise; the metric is what you care about. They are often different numbers.",
      pair: "loss-vs-metric" },
    { q: "Training loss keeps falling while validation loss has risen for five epochs. What does that mean?",
      o: ["The model is still improving, since training loss falls",
          "The learning rate is too low",
          "The model is overfitting; falling training loss no longer means a better model",
          "The validation set is too large",
          "The loss function is the wrong one for the task"],
      a: 2,
      why: "A falling loss is not a better model. Validation loss shows generalisation; training loss shows fit." }
  ],
  "gradient-descent": [
    { q: "In the first hundred steps the loss jumps around and then shoots to NaN. What is the most likely fix?",
      o: ["Use a larger batch and train longer",
          "Remove weight decay",
          "Switch from Adam to plain SGD",
          "Lower the learning rate, and warm it up over the first steps",
          "Add more layers to the model"],
      a: 3,
      why: "A learning rate that is too large makes the loss bounce or diverge. Warmup avoids large steps while statistics are unstable." },
    { q: "Why compute gradients on mini-batches instead of the full dataset?",
      o: ["Full-dataset gradients point in the wrong direction",
          "Mini-batches use less memory for the weights",
          "Mini-batches remove the need for a learning rate",
          "Full gradients cannot be computed by autograd",
          "Full gradients are too slow per step, and mini-batch noise tends to help generalisation"],
      a: 4,
      why: "Stochastic gradient descent estimates the gradient cheaply; the noise in that estimate turns out to help." },
    { q: "What does gradient descent on a deep network actually find?",
      o: ["A good enough region of low loss, not a guaranteed global minimum",
          "The global minimum, given enough steps",
          "The global minimum, if the learning rate is small enough",
          "A saddle point every time",
          "The same weights on every run"],
      a: 0,
      why: "A deep network's loss surface is not a bowl. Training finds a good region, and the learning rate matters most." }
  ],
  "backpropagation": [
    { q: "In PyTorch, what does `loss.backward()` do?",
      o: ["Updates every weight by one gradient step",
          "Fills each parameter's `.grad`; `optimizer.step()` then updates the weights",
          "Runs the forward pass again in reverse",
          "Resets gradients to zero for the next batch",
          "Computes the loss on the validation set"],
      a: 1,
      why: "Backpropagation computes gradients; the optimiser updates weights. Mixing them up is a quick tell in interviews.",
      pair: "backprop-vs-optimiser" },
    { q: "In a 100-layer plain network, gradients at the early layers are close to zero. What is happening, and what fixes it?",
      o: ["Exploding gradients; lower the learning rate",
          "Overfitting; add dropout",
          "Vanishing gradients; add residual connections and normalisation",
          "Dead data loader; add workers",
          "Underfitting; add more layers"],
      a: 2,
      why: "Many small factors multiplied along the chain go to zero. Residual paths and normalisation keep the gradient alive." },
    { q: "Roughly what does one backward pass cost, and what does it give you?",
      o: ["The same as the forward pass, and one weight's gradient",
          "Ten times the forward pass, and every gradient",
          "Half the forward pass, and the last layer's gradients",
          "About twice the forward pass, and the gradient of every weight",
          "One forward pass per weight, and every gradient"],
      a: 3,
      why: "Reverse-mode differentiation reuses the stored forward values, so one backward pass yields all gradients at about twice the forward cost." }
  ],
  "overfitting-regularisation": [
    { q: "A recommendation model scores far better offline than in production. Each user's rows appear in both train and test. What first?",
      o: ["Add dropout to every layer",
          "Raise the weight decay",
          "Collect ten times more data",
          "Switch to a smaller model",
          "Split by user so no user appears on both sides"],
      a: 4,
      why: "Most overfitting in practice is leakage. Fix the split before adding regularisation." },
    { q: "Training loss is 0.05 and validation loss has risen since epoch 8. Which action fits?",
      o: ["Stop at the validation minimum and add weight decay or augmentation",
          "Train for more epochs until validation loss falls again",
          "Make the model larger to fit the data better",
          "Raise the learning rate to escape the minimum",
          "Tune on the test set instead of the validation set"],
      a: 0,
      why: "Early stopping, weight decay and augmentation make the simpler explanation cheaper; more data beats all of them." }
  ],
  "evaluation-splits": [
    { q: "A demand forecaster scored well on a random split and badly in production. What went wrong?",
      o: ["The model was too small",
          "A random split let future rows inform the past; split by time",
          "The test set was too large",
          "The metric should have been accuracy",
          "The validation set was used for early stopping"],
      a: 1,
      why: "The split must mirror deployment. Forecasting trains on the past and tests on the most recent period." },
    { q: "A fraud model reports 99% accuracy where 1% of transactions are fraud. What should you check?",
      o: ["Whether the training loss is still falling",
          "Whether the model is large enough",
          "Precision and recall on fraud, since predicting 'not fraud' always scores 99%",
          "The learning rate schedule",
          "Accuracy on the training set"],
      a: 2,
      why: "Accuracy hides a rare class. Precision and recall show whether the positives are found." },
    { q: "A model wins clearly on the offline test set and then loses in an A/B test. Which explanation is most likely?",
      o: ["The A/B test was too long",
          "The test set was too clean to be useful",
          "A/B tests are noisier than offline metrics, so ignore it",
          "Offline metrics are a proxy: data shifted or the metric missed what users value",
          "The model overfit the A/B traffic"],
      a: 3,
      why: "An offline metric approximates value. Users, not the test set, decide." }
  ],
  "classic-models": [
    { q: "A bank scores loans from 200 tabular features, and regulators ask why a loan was refused. Which model family fits first?",
      o: ["A large transformer over the raw features",
          "A CNN over the feature table",
          "A diffusion model of applicants",
          "A recurrent network over features in order",
          "Gradient-boosted trees or logistic regression"],
      a: 4,
      why: "On tabular data these usually match or beat neural networks, train on a CPU, and can explain decisions." },
    { q: "How does gradient boosting differ from a random forest?",
      o: ["Boosting adds trees in sequence, each fitted to the ensemble's errors; a forest averages independent trees",
          "Boosting uses one deep tree; a forest uses many shallow ones",
          "A forest fits each tree to the previous tree's errors; boosting averages them",
          "Boosting works only for regression; forests for classification",
          "Boosting needs a GPU; a forest runs on a CPU"],
      a: 0,
      why: "A forest reduces variance by averaging trees grown on random samples; boosting reduces error by adding trees one at a time.",
      pair: "boosting-vs-random-forest" },
    { q: "A team proposes a neural network for a tabular churn task. What should exist before it ships?",
      o: ["A transformer baseline to compare against",
          "A logistic regression or LightGBM baseline it clearly beats",
          "A larger dataset scraped from the web",
          "A GPU cluster for retraining",
          "A diffusion model for synthetic rows"],
      a: 1,
      why: "A model that cannot beat the simple baseline is not ready, and the simple one is easier to monitor and explain." }
  ],
  "building-blocks": [
    { q: "You remove every activation function from a 10-layer MLP. What can it now represent?",
      o: ["The same functions, only more slowly",
          "Only step functions",
          "One linear function, no more than a single layer",
          "Only functions with ten bends",
          "Any function, given enough width"],
      a: 2,
      why: "A stack of linear layers collapses into one linear map. The nonlinearity between them is what lets networks fit curves." },
    { q: "What does a residual connection, `x + f(x)`, mainly buy?",
      o: ["Fewer parameters per layer",
          "Probabilities that sum to one",
          "Activations kept in a fixed range",
          "A direct path for gradients, so very deep networks train",
          "Built-in regularisation like dropout"],
      a: 3,
      why: "The identity path lets gradients flow back past each block. Normalisation, not the residual, keeps activations in range." },
    { q: "Where do most of a transformer's parameters sit?",
      o: ["In the attention query and key matrices",
          "In the layer norms",
          "In the positional embeddings",
          "In the softmax",
          "In the feed-forward layers"],
      a: 4,
      why: "The feed-forward blocks hold about twice the weights of attention per layer. Attention gets the attention; matrix multiplies get the compute." }
  ],
  "cnns": [
    { q: "Why does a convolutional layer need far fewer parameters than a dense layer on raw pixels?",
      o: ["The same small filter is reused at every position",
          "It looks only at the image's centre",
          "It works on grey images only",
          "It drops most pixels before computing",
          "It stores weights in 8-bit integers"],
      a: 0,
      why: "Weight sharing means a 3 × 3 filter has 9 weights however large the image, and a pattern learned once is found anywhere." },
    { q: "You have 2,000 labelled factory images and modest compute. CNN or vision transformer?",
      o: ["Vision transformer, since it is newer",
          "CNN, since its built-in assumption about nearby pixels helps when data is scarce",
          "Vision transformer, since it needs fewer labels",
          "Either, since architecture does not matter for images",
          "Neither; use gradient boosting on raw pixels"],
      a: 1,
      why: "With enough data a transformer learns locality itself; with little data the CNN's built-in assumption wins.",
      pair: "cnn-vs-vit" }
  ],
  "rnns": [
    { q: "What kept RNNs from scaling the way transformers did in training?",
      o: ["They cannot learn word order",
          "They need labelled data at every step",
          "Step 100 must wait for step 99, so training does not parallelise across time",
          "They have more parameters than transformers",
          "They cannot be trained with backpropagation"],
      a: 2,
      why: "Recurrence is sequential. Transformers process all positions at once in training." },
    { q: "For a very long streaming input, how does per-token cost compare?",
      o: ["Both grow with the square of the history",
          "Recurrent models grow; transformers stay constant",
          "Both stay constant once the cache is warm",
          "Recurrent and state-space models stay constant; transformers grow with context",
          "Neither depends on the history length"],
      a: 3,
      why: "A recurrent state has a fixed size, while attention looks back over the whole context. That is why recurrent ideas keep returning.",
      pair: "rnn-vs-transformer" },
    { q: "What are the gates in an LSTM for?",
      o: ["Splitting the input into tokens",
          "Running steps in parallel",
          "Mixing the outputs of several heads",
          "Normalising activations between layers",
          "Learning what to keep, write and forget, so memory lasts longer"],
      a: 4,
      why: "Plain RNNs forget fast because gradients vanish. Gates let the cell hold information across many steps." }
  ],
  "transformers": [
    { q: "Context length doubles. Roughly what happens to the cost of self-attention?",
      o: ["It grows about 4×, since every pair of tokens is compared",
          "It doubles",
          "It stays the same",
          "It grows about 8×",
          "It halves, thanks to caching"],
      a: 0,
      why: "Attention cost grows as n² for length n. Most long-context work, FlashAttention included, is about that cost." },
    { q: "What is the causal mask for in a GPT-style model?",
      o: ["It hides padding tokens from the loss",
          "It stops each token attending to later tokens, matching left-to-right generation",
          "It removes tokens the model is unsure of",
          "It encodes the position of each token",
          "It blocks harmful outputs at decode time"],
      a: 1,
      why: "Decoder-only models see only the past, so training matches how they generate one token at a time.",
      pair: "decoder-vs-encoder-decoder" },
    { q: "Why must transformers add positional information such as RoPE?",
      o: ["To make attention cost linear in length",
          "To store the KV cache",
          "Attention on its own ignores order, so 'dog bites man' would equal 'man bites dog'",
          "To let the model read images",
          "To normalise the attention scores"],
      a: 2,
      why: "Self-attention treats its input as a set. Position has to be put in, today usually by rotary embeddings." }
  ],
  "embeddings": [
    { q: "Semantic search returns 'how do I cancel my order' for 'how do I place an order'. What is the lesson?",
      o: ["The vector index is corrupted",
          "Cosine similarity is the wrong measure",
          "The embedding dimension is too small",
          "Close means similar by the training objective, not by your users' intent; test on your own queries",
          "Embeddings cannot handle questions"],
      a: 3,
      why: "Embeddings put things near each other by what training rewarded. Measure retrieval on real queries before trusting a leaderboard." },
    { q: "What is the first layer of every language model?",
      o: ["A sentence embedding of the whole input",
          "A contrastive encoder",
          "A convolution over characters",
          "A vector index of the vocabulary",
          "A lookup table from token id to vector"],
      a: 4,
      why: "Token embeddings are a learned table. Sentence embeddings come from a separate model trained so whole texts compare well.",
      pair: "token-vs-sentence-embeddings" }
  ],
  "optimisers": [
    { q: "A 7B model's weights fit on a GPU, but training with Adam runs out of memory. Why?",
      o: ["Adam keeps two extra values per weight, plus gradients",
          "Adam needs the whole dataset in memory",
          "Adam stores every past gradient",
          "Adam doubles the batch size automatically",
          "Adam runs in 64-bit floats"],
      a: 0,
      why: "Two running averages per weight mean optimiser state can take more memory than the model itself." },
    { q: "Training diverged. A colleague wants to switch from AdamW to a newer optimiser. What should come first?",
      o: ["Switch optimisers, since AdamW is outdated",
          "Lower the learning rate and check the data",
          "Double the batch size",
          "Remove weight decay entirely",
          "Add more layers"],
      a: 1,
      why: "Swapping optimisers rarely fixes what a bad learning rate or a bad batch broke." },
    { q: "You want an effective batch of 512 but only 64 fits in memory. What do you do?",
      o: ["Lower the learning rate by eight times",
          "Train eight models and average them",
          "Accumulate gradients over eight small batches before one step",
          "Use batch 64 and train eight times longer",
          "Switch to plain SGD"],
      a: 2,
      why: "Gradient accumulation sums gradients over several small batches, then applies one update." }
  ],
  "mixed-precision": [
    { q: "Why does float16 training need loss scaling while bfloat16 rarely does?",
      o: ["bfloat16 has more precision bits",
          "float16 is slower on tensor cores",
          "bfloat16 stores a master copy automatically",
          "float16 has a small range, so tiny gradients underflow; bfloat16 keeps float32's range",
          "float16 cannot represent negative numbers"],
      a: 3,
      why: "bfloat16 trades precision for float32's exponent range; float16 has more precision but a narrow range.",
      pair: "bf16-vs-fp16" },
    { q: "GPU utilisation sits at 35% during training. What do you look at first?",
      o: ["Switching to FP8",
          "A different optimiser",
          "A larger model",
          "Fusing the attention kernel",
          "The data loader and the communication between GPUs"],
      a: 4,
      why: "Most throughput problems are a starved GPU or communication, not the maths. Measure before tuning." },
    { q: "A model plus its optimiser state does not fit on one GPU, even at batch size 1. What helps?",
      o: ["FSDP or ZeRO, sharding weights, gradients and optimiser state across GPUs",
          "Plain data parallelism, with a full copy per GPU",
          "Gradient accumulation",
          "A larger learning rate",
          "Early stopping"],
      a: 0,
      why: "Data parallelism copies the whole model to each GPU; sharding splits it so large models fit." }
  ],
  "frameworks": [
    { q: "Which statement is true of JAX?",
      o: ["It runs eagerly with mutable tensors like PyTorch",
          "You write pure functions and transform them with grad, jit and vmap, passing random keys explicitly",
          "It has no automatic differentiation",
          "It runs only on NVIDIA GPUs",
          "It is the default framework for Hugging Face models"],
      a: 1,
      why: "JAX is functional: immutable arrays, explicit randomness, transformations. PyTorch runs eagerly and is the common default.",
      pair: "pytorch-vs-jax" },
    { q: "You have written a new training loop. What is the first sanity check?",
      o: ["Train the full model for a day",
          "Compare frameworks on speed",
          "Overfit a tiny batch to prove the loop can learn",
          "Tune the learning rate schedule",
          "Turn on mixed precision"],
      a: 2,
      why: "If the loop cannot drive loss near zero on a few examples, something is broken. Habits matter more than the framework." }
  ],
  "pretraining": [
    { q: "By the Chinchilla rule of thumb, about how many training tokens suit a 70B model for a fixed compute budget?",
      o: ["About 70 billion",
          "About 300 billion",
          "About 15 trillion",
          "About 1.4 trillion",
          "About 70 trillion"],
      a: 3,
      why: "Chinchilla suggests roughly 20 tokens per parameter for compute-optimal training: 70B × 20 = 1.4T." },
    { q: "Why do labs now train small models far past the Chinchilla ratio?",
      o: ["Chinchilla's results were shown to be wrong",
          "More tokens make the model follow instructions",
          "Small models cannot be trained any other way",
          "Larger models are banned in some regions",
          "A smaller model trained longer is cheaper to serve"],
      a: 4,
      why: "Compute-optimal for training is not optimal for serving. Inference cost dominates over a model's life." },
    { q: "Where did much of the gain in recent models come from, beyond scale?",
      o: ["Data filtering, deduplication and synthetic data",
          "Removing the tokenizer",
          "Training on fewer languages",
          "Switching from cross-entropy to MSE",
          "Smaller vocabularies"],
      a: 0,
      why: "Data quality now matters as much as quantity." }
  ],
  "fine-tuning-lora": [
    { q: "What does LoRA train?",
      o: ["Every weight in the model, at a lower learning rate",
          "Two thin low-rank matrices beside frozen weights, whose product is added",
          "Only the final classification layer",
          "A new tokenizer for the domain",
          "A reward model for preferences"],
      a: 1,
      why: "LoRA freezes the base and learns a small update; adapters are megabytes, not a full copy." },
    { q: "You need 200 customer-specific variants of one 8B model. What serves them cheaply?",
      o: ["200 fully fine-tuned copies on 200 GPUs",
          "One prompt per customer with no tuning",
          "LoRA adapters on one base model, picked per request",
          "200 distilled models of different sizes",
          "One model retrained nightly on all customers"],
      a: 2,
      why: "Multi-LoRA serving loads many small adapters on one base model and picks one per request." },
    { q: "A team wants a model to know product facts that change every month. Fine-tuning or retrieval?",
      o: ["Fine-tuning, since it bakes facts into the weights",
          "Fine-tuning with LoRA, since adapters update fast",
          "Neither; use a larger base model",
          "Retrieval, since fine-tuning teaches new facts badly",
          "Full fine-tuning every week"],
      a: 3,
      why: "Fine-tuning teaches format, style and narrow skills well and new facts badly.",
      pair: "rag-vs-fine-tuning" }
  ],
  "preference-tuning": [
    { q: "What does DPO remove compared with classic RLHF?",
      o: ["The need for preference pairs",
          "The supervised fine-tuning stage",
          "The base model",
          "Human raters entirely",
          "The separate reward model and the RL loop"],
      a: 4,
      why: "DPO uses a classification-style loss directly on preferred and rejected pairs.",
      pair: "dpo-vs-rlhf" },
    { q: "After preference tuning, answers got longer and more flattering. What happened?",
      o: ["Reward hacking: the model optimised what raters scored, not what they meant",
          "The learning rate was too low",
          "The SFT data was too short",
          "The tokenizer changed",
          "The model forgot its pretraining"],
      a: 0,
      why: "The model optimises the reward, not the intent behind it." },
    { q: "How were 2025's reasoning models, such as DeepSeek-R1, largely trained?",
      o: ["Supervised fine-tuning on human-written proofs",
          "Reinforcement learning against verifiable rewards, such as correct maths answers",
          "Pretraining on more maths text",
          "DPO on human preference pairs",
          "Distillation from a larger chat model only"],
      a: 1,
      why: "When a reward can be checked (a passing test, a right answer), RL can train reasoning without human rankings." }
  ],
  "diffusion": [
    { q: "What is a diffusion model trained to do?",
      o: ["Classify whether an image is real",
          "Predict the next pixel from the previous ones",
          "Predict the noise that was added to an image at a given noise level",
          "Compress an image into a short code",
          "Match images to their captions"],
      a: 2,
      why: "Training adds known Gaussian noise and asks the model to predict it; generation reverses the process step by step." },
    { q: "Why did latent diffusion make image generation affordable?",
      o: ["It removed the text encoder",
          "It uses a single denoising step",
          "It replaced noise with masks",
          "It runs in an autoencoder's compressed latent space instead of on pixels",
          "It trains on fewer images"],
      a: 3,
      why: "Denoising a small latent is far cheaper than denoising full-resolution pixels." },
    { q: "Why is diffusion generation slow, and what speeds it up?",
      o: ["Each step attends to every past image; caching fixes it",
          "The text encoder is huge; smaller prompts fix it",
          "It runs on CPUs; GPUs fix it",
          "It needs 1,000 steps at inference; nothing reduces that",
          "It takes many sequential denoising steps; distillation and consistency models cut them"],
      a: 4,
      why: "Typical samplers use 20 to 50 steps; distilled models get to a few steps at some cost in quality." }
  ]
});
