/* Multiple choice for the Mobile engineering field: 2 or 3 per topic. Checked by baseline/quiz/check.js. */
BASELINE.quiz("mobile", {
  "ios-native": [
    { q: "A team wants a new SwiftUI API introduced in the latest iOS, but supports the last three iOS versions. What usually happens?",
      o: ["They drop support for every older iOS at once",
          "They wait or write the screen twice, often falling back to UIKit",
          "The API is backported automatically by Xcode",
          "Older devices download the new SwiftUI on demand",
          "The App Store rejects apps that support old versions"],
      a: 1,
      why: "SwiftUI's newest features need the newest iOS, which is why knowing UIKit still pays." },
    { q: "In SwiftUI, what makes a view redraw?",
      o: ["A timer the framework runs every frame",
          "Editing the view's frame in UIKit",
          "Restarting the scene",
          "A change to state it reads, such as an `@State` value or an `@Observable` model",
          "Calling a `redraw()` method on the view"],
      a: 3,
      why: "SwiftUI views are functions of state. Change the state and the affected views redraw.",
      pair: "declarative-vs-imperative" },
    { q: "What do Swift 6's data race checks rely on?",
      o: ["A runtime race detector shipped in release builds",
          "Garbage collection pauses",
          "Locks inserted by the App Store",
          "Running all code on the main thread",
          "`async`/`await` and actors, checked at compile time"],
      a: 4,
      why: "Swift 6 checks for data races at compile time using structured concurrency and actors." }
  ],
  "android-native": [
    { q: "A composable makes a network call directly in its body. Why is that a bug?",
      o: ["Kotlin forbids network calls outside coroutines",
          "It only runs once, so data never refreshes",
          "Compose can re-run it on any recomposition, repeating the call",
          "Composables cannot access the network at all",
          "It blocks the XML view system"],
      a: 2,
      why: "Composables must be fast and free of side effects, because recomposition re-runs them whenever state they read changes." },
    { q: "Your app works on a Pixel but users report background sync never runs on some brands. What is the likely cause?",
      o: ["Room databases failing on older Android",
          "Google Play blocking sync on those devices",
          "Vendor battery savers killing background work",
          "A Kotlin version mismatch on those phones",
          "Jetpack Compose not supporting those screens"],
      a: 2,
      why: "Fragmentation is the real job: test on cheap phones and expect vendor battery savers." },
    { q: "In Google's recommended Android architecture, where does screen state live?",
      o: ["In the composable's local variables",
          "In the Room database only",
          "In a `ViewModel` in the UI layer, with state flowing down and events up",
          "In the repository, read directly by composables",
          "In a global singleton shared by all screens"],
      a: 2,
      why: "The UI layer holds a ViewModel; repositories over Room, DataStore and the network form the data layer." }
  ],
  "react-native": [
    { q: "What does a React Native `<View>` become on the device?",
      o: ["A Flutter widget",
          "A native view: a `UIView` on iOS or an Android `View`",
          "A `<div>` inside an embedded web view",
          "A canvas drawn by a custom engine",
          "An HTML element styled to look native"],
      a: 1,
      why: "React Native maps components to real native views. Flutter is the one that draws its own.",
      pair: "react-native-vs-flutter" },
    { q: "A React Native app scrolls a long feed badly. Where does the problem usually come from?",
      o: ["The native views being slower than web views",
          "TypeScript being compiled at runtime",
          "Expo adding overhead to every frame",
          "The GPU being unused by React Native",
          "Heavy work on the JavaScript thread and lists rendering too much"],
      a: 4,
      why: "Performance problems usually come from the JS thread and lists that render too much." },
    { q: "A web React team moves to React Native. What carries over?",
      o: ["Nothing, because React Native uses a different language",
          "Their CSS files and media queries",
          "Their routing code unchanged",
          "Their skills and much of their logic, but not their screens",
          "Their screens unchanged, since layouts are the same"],
      a: 3,
      why: "Mobile layouts, navigation and gestures still differ. It shares skills, not screens." }
  ],
  "flutter": [
    { q: "How does Flutter put UI on screen, compared with React Native?",
      o: ["It renders HTML inside a web view",
          "It uses the system's UIKit and Android views directly",
          "It compiles widgets into SwiftUI and Compose",
          "It draws its own widgets with its own engine instead of mapping to native views",
          "It maps each widget to a native platform view"],
      a: 3,
      why: "Flutter renders every pixel itself, which gives identical output across platforms.",
      pair: "react-native-vs-flutter" },
    { q: "Apple ships a new iOS control style. What does a Flutter app get for free?",
      o: ["The new style through hot reload",
          "Nothing until the framework matches it, since Flutter draws its own widgets",
          "The new style automatically on the next launch",
          "The new style if the phone updates iOS",
          "The new style once the app is rebuilt in Xcode"],
      a: 1,
      why: "Drawing its own widgets means platform look, text selection and accessibility semantics must be matched by the framework." },
    { q: "What does Flutter's hot reload do?",
      o: ["Recompiles the native engine",
          "Reloads only images and fonts",
          "Applies code changes in about a second while keeping app state",
          "Restarts the app with a fresh state",
          "Pushes an update to users' devices"],
      a: 2,
      why: "Hot reload keeps the running state, which makes UI iteration fast." }
  ],
  "kmp": [
    { q: "Why is Kotlin Multiplatform called the lowest-risk way to share code?",
      o: ["One layer, such as networking or models, can move over at a time",
          "It forces both apps to share every screen at once",
          "It removes the need for iOS developers",
          "It runs one JavaScript bundle on both platforms",
          "It replaces Swift with Kotlin entirely"],
      a: 0,
      why: "Teams usually share the layers below the UI first while each platform keeps native screens." },
    { q: "What must an iOS team accept when adopting KMP?",
      o: ["Losing access to iOS APIs",
          "Kotlin in their build, and care with Swift interop for coroutines and generics",
          "Rewriting all their screens in Compose",
          "Dropping SwiftUI for UIKit",
          "Shipping a JavaScript runtime in the app"],
      a: 1,
      why: "Shared code compiles to a native framework Swift calls, but interop has rough edges." },
    { q: "A shared KMP module needs a different UUID generator on iOS and Android. What feature handles that?",
      o: ["Annotations read by Xcode",
          "`expect` and `actual` declarations",
          "A runtime `if (platform)` check in Swift",
          "Separate Git branches per platform",
          "A JavaScript bridge"],
      a: 1,
      why: "`expect` declares the shared signature; each platform provides an `actual` implementation." }
  ],
  "app-lifecycle": [
    { q: "A user leaves your iOS app, and later the system needs memory. What can happen to the suspended app?",
      o: ["It gets a callback to save state first, every time",
          "It is paused forever in memory",
          "It moves to an Android-style foreground service",
          "It keeps running at low priority",
          "It is terminated without warning and without running more code"],
      a: 4,
      why: "Once suspended an app runs no code and can be killed. Save what matters as the user leaves." },
    { q: "An Android app keeps form data in a singleton. It survives rotation, but users lose it after switching apps for a while. Why?",
      o: ["The form data was too large for memory",
          "The process was killed in the background, and memory came back empty",
          "Rotation deleted the singleton",
          "The singleton was garbage collected on every pause",
          "Android clears singletons on `onResume`"],
      a: 1,
      why: "Process death is the case teams never test: the app reopens on the last screen with empty memory. Use saved state." },
    { q: "What does rotating an Android device do by default?",
      o: ["Suspends the app",
          "Does nothing to the activity",
          "Clears all saved state",
          "Recreates the activity",
          "Kills the whole process"],
      a: 3,
      why: "Rotation recreates the activity, which is why state must be saved and restored, not kept in local fields." }
  ],
  "background-work": [
    { q: "A product manager wants an iOS app to sync every 15 minutes in the background. What is the honest answer?",
      o: ["There is no reliable way; design for eventually and use push for urgent work",
          "Use a background timer, which iOS honours",
          "Run a foreground service like on Android",
          "Keep a socket open in the background",
          "Use `BGTaskScheduler` with a fixed 15-minute schedule"],
      a: 0,
      why: "iOS decides when deferred work runs. Push triggers urgent work; everything else is eventual." },
    { q: "An Android upload must happen eventually, only on Wi-Fi, and survive a reboot. What fits?",
      o: ["A coroutine in the ViewModel",
          "An alarm every minute",
          "WorkManager with a Wi-Fi constraint",
          "A thread started in `onCreate`",
          "A foreground service running forever"],
      a: 2,
      why: "WorkManager persists the job, honours constraints, retries with backoff and survives reboots.",
      pair: "workmanager-vs-foreground-service" },
    { q: "A fitness app tracks a run for an hour with the screen off on Android. What does it need?",
      o: ["A silent push every minute",
          "A background thread with a wake lock only",
          "Nothing, apps can run freely in the background",
          "A foreground service with a visible notification and a declared type",
          "WorkManager with a periodic request"],
      a: 3,
      why: "Long user-visible work needs a foreground service; since Android 14 each must declare its type.",
      pair: "workmanager-vs-foreground-service" }
  ],
  "push-notifications": [
    { q: "How does your backend reach a user's phone with a push?",
      o: ["It sends the device token and payload to APNs or FCM, which deliver it",
          "It opens a socket directly to the phone",
          "It sends an SMS that the app reads",
          "It waits for the app to poll",
          "It calls the app's local web server"],
      a: 0,
      why: "Apps cannot hold their own background connection, so the platform's always-open connection carries pushes." },
    { q: "Your app uses silent data pushes to sync every hour, but some never arrive. Why?",
      o: ["FCM only delivers notification messages",
          "The app's token expires every hour",
          "Silent pushes only work on Wi-Fi",
          "Silent pushes are throttled and not guaranteed",
          "Silent pushes always need user permission"],
      a: 3,
      why: "Data messages wake the app briefly when the system allows. They are not a scheduler.",
      pair: "notification-vs-data-message" },
    { q: "When should an app ask for notification permission?",
      o: ["At first launch, before anything else",
          "Never, since push needs no permission",
          "Only after the first crash",
          "In the App Store listing",
          "When the value is clear, such as after the user follows an order"],
      a: 4,
      why: "iOS and Android 13 onwards require permission. Asking at first launch, with no context, gets refused." }
  ],
  "deep-links": [
    { q: "Why prefer Universal Links or App Links over a custom scheme such as `myapp://`?",
      o: ["They skip the need for a router inside the app",
          "They are faster to parse than custom schemes",
          "They avoid all need for sign-in",
          "They use verified `https://` URLs, so no other app can claim them, with a web fallback",
          "They work without the app being installed, opening the app anyway"],
      a: 3,
      why: "Any app can register the same custom scheme. Verified domain files tie the link to your app." },
    { q: "A deep link `myapp://transfer?to=123&amount=500` starts a payment at once. What is wrong?",
      o: ["A deep link is untrusted input; actions need validation and confirmation",
          "Nothing, if the link uses HTTPS",
          "Deep links cannot carry parameters",
          "Payments must use custom schemes only",
          "The amount should be in the path, not the query"],
      a: 0,
      why: "Anyone can send a link. Validate its parameters and never let it trigger an action without confirmation." }
  ],
  "offline-sync": [
    { q: "Two devices edit the same note offline, and sync uses last write wins by timestamp. What can go wrong?",
      o: ["One edit is silently lost, and wrong device clocks can pick the wrong winner",
          "Both edits merge cleanly into one note",
          "The sync refuses to run until a person chooses",
          "The note is duplicated on both devices",
          "Nothing, timestamps are always reliable"],
      a: 0,
      why: "Last write wins loses data silently. Decide per field what a conflict should do.",
      pair: "lww-vs-crdt" },
    { q: "A collaborative app needs concurrent offline edits to merge without a central referee. What fits?",
      o: ["Rejecting any edit made offline",
          "Retrying the sync until one side gives up",
          "CRDTs, data types that merge concurrent edits",
          "Last write wins by server timestamp",
          "Locking the record while one device is offline"],
      a: 2,
      why: "CRDTs merge concurrent changes deterministically, so every replica converges.",
      pair: "lww-vs-crdt" },
    { q: "A record is created while the phone is offline. How should its id be assigned?",
      o: ["Generated on the client, such as a UUID",
          "Left empty until the server assigns one",
          "Taken from an auto-increment counter on the device",
          "Copied from the previous record plus one",
          "Set to the creation timestamp only"],
      a: 0,
      why: "Offline records need ids before the server sees them, and they must not collide across devices." }
  ],
  "networking": [
    { q: "A request fails halfway as the user walks from Wi-Fi to cellular. Which requests is it safe to retry automatically?",
      o: ["Only POST requests",
          "Only requests over HTTP/1.1",
          "Idempotent ones, with backoff",
          "Every request, immediately and repeatedly",
          "None, a failure should always end the flow"],
      a: 2,
      why: "Retrying a non-idempotent request can charge or post twice. Timeouts plus backoff on safe calls are the baseline." },
    { q: "Why do many small requests drain a phone's battery more than one larger one?",
      o: ["The radio stays in a high-power state for seconds after each transfer",
          "Each request is encrypted twice",
          "Small requests use more CPU to parse",
          "The OS wakes the screen for each request",
          "Small requests bypass HTTP caching"],
      a: 0,
      why: "Batching lets the radio drop back to low power." },
    { q: "A flow works perfectly in the office. What should you do before calling it done?",
      o: ["Add more logging and ship",
          "Throttle to a slow profile and toggle airplane mode mid-request",
          "Test it again on faster office Wi-Fi",
          "Run it in the simulator only",
          "Check it on the newest flagship phone"],
      a: 1,
      why: "Office Wi-Fi hides most network bugs." }
  ],
  "mobile-security": [
    { q: "Where should a refresh token be stored on the phone?",
      o: ["The Keychain on iOS or the Android Keystore",
          "Plain shared preferences or UserDefaults",
          "A SQLite table in the app's folder",
          "A file in the app's documents directory",
          "A constant in the app binary"],
      a: 0,
      why: "Protected stores are hardware-backed on modern phones; plain files and preferences are readable on a rooted or jailbroken device." },
    { q: "An app embeds a paid third-party API key in its code, obfuscated. Is the key safe?",
      o: ["Only on Android is it exposed",
          "No, anything in the binary can be extracted; call the API from your backend",
          "Yes, obfuscation hides it well enough",
          "Yes, if certificate pinning is enabled",
          "Yes, since the App Store encrypts binaries"],
      a: 1,
      why: "Anything shipped in the app binary is public. Keys that cost money belong on the server." },
    { q: "The app hides a discount button for free users. What must also be true?",
      o: ["The discount code is stored in the Keychain",
          "The server enforces who may get the discount",
          "The button is obfuscated in the binary",
          "Attestation is enabled on the client",
          "The app checks the user's plan before showing it"],
      a: 1,
      why: "A mobile app is a client you do not control. Every rule that matters is enforced on the server." }
  ],
  "performance-battery": [
    { q: "At 120 Hz, roughly how long does each frame have before main-thread work drops it?",
      o: ["About 8 ms",
          "About 16 ms",
          "About 50 ms",
          "About 100 ms",
          "About 1 ms"],
      a: 0,
      why: "A frame at 60 Hz has about 16 ms; at 120 Hz about 8 ms." },
    { q: "A team profiles a debug build on a flagship phone and finds no problems. Why is that misleading?",
      o: ["Profilers only work on emulators",
          "Flagships throttle more than cheap phones",
          "Release builds disable the main thread",
          "Debug builds are slower, and flagships hide what mid-range users feel",
          "Debug builds are faster than release builds"],
      a: 3,
      why: "Profile release builds on a mid-range device." },
    { q: "An Android app blocks the main thread for five seconds while loading a file. What happens?",
      o: ["The app is uninstalled",
          "The frame rate doubles afterwards",
          "Nothing, the user waits",
          "An 'app not responding' dialog appears",
          "The OS moves the work to a background thread"],
      a: 3,
      why: "ANRs hurt users and, past a threshold rate, the app's visibility on Google Play." }
  ],
  "on-device-ml": [
    { q: "Why run a model on the phone instead of a server?",
      o: ["It avoids the need to quantise the model",
          "App stores require on-device models",
          "No network round trip, no server cost, and data stays on the device",
          "On-device models are always more accurate",
          "Phones have more memory than servers"],
      a: 2,
      why: "Local inference trades model size for latency, cost and privacy." },
    { q: "A team's model runs on a test phone. What can still stop it shipping?",
      o: ["Nothing, if it runs once it ships",
          "Only the App Store review time",
          "Only the model's licence",
          "Only the screen size",
          "App size, memory spikes, heat and battery"],
      a: 4,
      why: "A model that runs is not a model that ships. Many apps run a small model locally and fall back to a server." },
    { q: "Why are on-device models usually quantised to 8 or 4 bits?",
      o: ["To make them more accurate",
          "To make them run only on the CPU",
          "To encrypt the weights",
          "Because NPUs cannot load floats at all",
          "To fit memory and power budgets"],
      a: 4,
      why: "Lower precision shrinks the model and its compute, at some cost in quality." }
  ],
  "app-store": [
    { q: "A team plans to download new feature code over the air to skip App Store review. What limits this?",
      o: ["Over-the-air updates are banned on both stores entirely",
          "Only images can be downloaded at runtime",
          "TestFlight blocks network access",
          "Android requires a reboot for each update",
          "Apple forbids downloading code that changes an app's features"],
      a: 4,
      why: "Guideline 2.5.2 bounds what over-the-air updates may do." },
    { q: "A bug in production must be turned off within the hour. Why is a new build not enough?",
      o: ["Signing certificates expire after each build",
          "A hotfix still waits in review; a server-side switch acts at once",
          "Builds cannot be uploaded during business hours",
          "The store forbids more than one build a week",
          "Users must uninstall the app first"],
      a: 1,
      why: "Review time and rejection risk sit on the critical path. Keep switches for anything you may need to turn off quickly." },
    { q: "An app sells a digital subscription. On the App Store, what applies in most cases?",
      o: ["It must sell only through the website",
          "It must be free on iOS",
          "It needs a separate store per country",
          "It must use in-app purchase, with exceptions in some regions",
          "It may use any payment link anywhere"],
      a: 3,
      why: "Digital goods use in-app purchase in most cases; court rulings and the EU's Digital Markets Act opened exceptions in some regions." }
  ],
  "releases": [
    { q: "A bad build reached 20% of users before you halted the staged rollout. What happens to those users?",
      o: ["They keep the bad build; halting only stops new installs",
          "The store removes the build from their phones",
          "Their phones revert to the previous version",
          "The app stops launching until they update",
          "The build is disabled remotely by the store"],
      a: 0,
      why: "A mobile release cannot be rolled back like a web deploy. The real undo is a flag that was already in place." },
    { q: "Why keep a minimum supported version on the server?",
      o: ["To replace feature flags",
          "To count active users",
          "To make very old builds update when they can no longer be supported",
          "To speed up App Store review",
          "To block new users from installing"],
      a: 2,
      why: "Old builds stay on devices until users update, so the server needs a way to retire them." },
    { q: "Which tool lets you turn off a broken feature already installed on every phone?",
      o: ["A halted staged rollout",
          "Apple's phased release",
          "A new build with the feature removed",
          "Deleting the release in the console",
          "A remote feature flag shipped in the build beforehand"],
      a: 4,
      why: "Flags ship code switched off and can be turned on or off remotely, per user or percentage.",
      pair: "rollout-vs-flag" }
  ],
  "crash-analytics": [
    { q: "Crash reports for a release build show only memory addresses. What is missing?",
      o: ["The crash reporter's API key",
          "Debug mode on users' phones",
          "A newer version of the OS",
          "Analytics consent from users",
          "The dSYM or R8 mapping files for that build, needed to symbolicate"],
      a: 4,
      why: "Release builds are stripped and obfuscated. Upload symbol files in CI with every release build." },
    { q: "How do you spot that a new release made crashes worse?",
      o: ["Wait for the next quarterly report",
          "Check the crash count on your own phone",
          "Compare crash-free user rates per release",
          "Count total crashes across all versions",
          "Read store reviews daily"],
      a: 2,
      why: "Per-release crash rates show a regression within hours." },
    { q: "An app wants to track users across other companies' apps for ads on iOS. What does it need?",
      o: ["Nothing beyond its own privacy policy",
          "A paid Apple Developer account only",
          "Crash reporting turned off",
          "A server in the user's country",
          "The user's consent under App Tracking Transparency"],
      a: 4,
      why: "ATT requires consent for cross-app tracking. First-party product analytics are a separate matter." }
  ]
});
