/* Multiple choice for the NLP field: 2 or 3 per topic. Checked by baseline/quiz/check.js. */
BASELINE.quiz("nlp", {
  "tokenization": [
    { q: "A model miscounts the letter r in 'strawberry'. What is the most likely reason?",
      o: ["It sees subword tokens, not individual letters",
          "Its temperature is set too high",
          "Its context window is too short",
          "It was never trained on English",
          "Its attention skips repeated letters"],
      a: 0,
      why: "The model reads token ids for chunks like 'straw' and 'berry'. When a model fails on spelling or digits, look at the tokens first." },
    { q: "What does byte-level BPE guarantee that a word-level vocabulary cannot?",
      o: ["Fewer tokens for every language",
          "No unknown tokens, since any byte sequence can be encoded",
          "One token per word",
          "Identical token counts across languages",
          "Better arithmetic on long numbers"],
      a: 1,
      why: "Starting from the 256 bytes means code, emoji and typos always encode, with no unknown token." },
    { q: "The same message costs noticeably more tokens in Hindi than in English. Why?",
      o: ["Hindi words are longer on average",
          "APIs charge more for non-English text",
          "The tokenizer's merges were learned mostly from English, so other text splits into more pieces",
          "Unicode characters always count as two tokens",
          "The model translates to English first"],
      a: 2,
      why: "A subword vocabulary favours the languages it was trained on. Token count sets cost, context use and latency." }
  ],
  "bow-tfidf": [
    { q: "In TF-IDF, what weight does a word get if it appears in every document?",
      o: ["The highest weight, since it is frequent",
          "A weight equal to its raw count",
          "A weight of one",
          "Near zero, since log(N / df) is near zero",
          "A negative weight"],
      a: 3,
      why: "IDF rewards rarity. A term in every document carries no information about which document is which." },
    { q: "TF-IDF with logistic regression reaches 90%; a fine-tuned encoder reaches 92%. What does that tell you?",
      o: ["The encoder is clearly better and should ship",
          "The TF-IDF model must be overfitting",
          "The test set is too small to use",
          "Both models are broken",
          "Two points may not pay for the encoder's latency and serving work"],
      a: 4,
      why: "A strong baseline tells you how hard the problem is, and what a heavier model has to earn." },
    { q: "A TF-IDF classifier misses 'end my membership' though it handles 'cancel subscription'. Why?",
      o: ["It matches words, not meaning, so synonyms and paraphrase fail",
          "Its n-gram range is too wide",
          "Its vocabulary is too large",
          "It needs a lower learning rate",
          "Its IDF weights are inverted"],
      a: 0,
      why: "Sparse counts share no features between different words with the same meaning. Dense embeddings fix that.",
      pair: "sparse-vs-dense" }
  ],
  "word-embeddings": [
    { q: "What does negative sampling in word2vec replace?",
      o: ["The context window",
          "A full softmax over the vocabulary, with binary classification of true and random pairs",
          "The embedding table",
          "The skip-gram objective",
          "Tokenization of rare words"],
      a: 1,
      why: "Scoring every vocabulary word each step is expensive; raising true pairs and lowering k random ones is cheap." },
    { q: "In a word2vec space, `hot` and `cold` sit very close. Why?",
      o: ["The model was trained too briefly",
          "The vectors have too few dimensions",
          "Antonyms appear in the same contexts, and similar context is what the model learns",
          "The corpus mislabelled them",
          "Cosine similarity ignores sign"],
      a: 2,
      why: "Distributional similarity is not sameness of meaning. Static vectors also cannot separate senses of one word." },
    { q: "Clinical notes are full of typos and rare drug names. Which static embedding copes best?",
      o: ["word2vec, since it has a larger window",
          "GloVe, since it uses global counts",
          "One-hot vectors over the vocabulary",
          "fastText, since it builds words from character n-grams",
          "TF-IDF, since it weights rare words up"],
      a: 3,
      why: "fastText composes a vector from character pieces, so unseen and misspelled words still get one." }
  ],
  "sentence-embeddings": [
    { q: "Why does mean-pooled raw BERT give poor sentence similarity?",
      o: ["BERT cannot read whole sentences",
          "BERT's vocabulary is too small",
          "Mean pooling loses the first token",
          "BERT outputs probabilities, not vectors",
          "It was trained to fill masked tokens, and its vectors crowd into a narrow cone"],
      a: 4,
      why: "Without training for similarity, cosine scores barely separate. Sentence-BERT and contrastive training fix that." },
    { q: "With in-batch negatives, why do larger batches tend to help contrastive training?",
      o: ["Each other example in the batch is a free negative, so there are more to push away",
          "Larger batches need fewer epochs to converge",
          "Larger batches remove the need for positives",
          "Larger batches make the vectors shorter",
          "Larger batches prevent overfitting to hard negatives"],
      a: 0,
      why: "More negatives per query make the task harder and the vectors sharper; mined hard negatives help further." },
    { q: "A team wants to move from one embedding model to a better one. What does the switch require?",
      o: ["Only new query embeddings; documents stay",
          "Re-embedding the whole corpus, since vectors from two models do not share a space",
          "A new distance metric, nothing else",
          "Retraining the vector index's HNSW graph only",
          "Nothing, if both have the same dimension"],
      a: 1,
      why: "Same dimension does not mean the same space. Plan for a full re-embed when you change models." }
  ],
  "text-classification": [
    { q: "You have 12 intents with about 30 examples each and want millisecond inference on a CPU. Which rung fits?",
      o: ["Prompting a frontier LLM on every message",
          "Fine-tuning a large encoder from scratch",
          "SetFit, or frozen sentence embeddings with a logistic head",
          "Training a transformer from random weights",
          "Zero-shot NLI with one pass per label"],
      a: 2,
      why: "Little data and tight latency suit embeddings plus a small head, or SetFit's contrastive fine-tune on few examples." },
    { q: "A support ticket can be both 'billing' and 'technical'. What output setup fits?",
      o: ["One softmax over the labels with cross-entropy",
          "One softmax, then take the top two labels",
          "A regression output per label",
          "Independent sigmoids, binary cross-entropy and a threshold per label",
          "A separate model trained only on billing"],
      a: 3,
      why: "Multi-class means one label and softmax; multi-label means each label is its own yes or no decision.",
      pair: "multi-class-vs-multi-label" },
    { q: "An intent classifier has stalled at 88% after two model upgrades. Where are the gains most likely?",
      o: ["A model ten times larger",
          "A longer training schedule",
          "A different tokenizer",
          "A higher dropout rate",
          "Fixing mislabelled examples and merging colliding intents"],
      a: 4,
      why: "Most production gains come from data: mislabels, colliding intents and real utterances from logs." }
  ],
  "classification-metrics": [
    { q: "Your intents are very imbalanced, and a rare 'fraud report' intent matters as much as common ones. Which average do you report?",
      o: ["Macro F1, so each class counts equally",
          "Micro F1, so every decision counts equally",
          "Accuracy, since it covers every class",
          "Weighted F1 by class frequency",
          "Precision on the largest class"],
      a: 0,
      why: "Micro averaging lets big classes dominate; macro averages per-class scores so a rare intent is not hidden.",
      pair: "micro-vs-macro" },
    { q: "What does temperature scaling change in a trained classifier?",
      o: ["Which class is predicted for each input",
          "The confidence values, while leaving the top prediction the same",
          "The model's weights in every layer",
          "The class balance in the training data",
          "The number of classes"],
      a: 1,
      why: "One scalar divides the logits, so ranking is unchanged and the probabilities become calibrated." },
    { q: "After a retrain, a fixed 0.7 escalation threshold escalates twice as many chats. What is the likely cause?",
      o: ["Traffic doubled overnight",
          "The model became more accurate",
          "The confidence distribution shifted; recalibrate and re-pick thresholds after every retrain",
          "The confusion matrix was computed on the wrong split",
          "Thresholds must always be 0.5"],
      a: 2,
      why: "Every routing rule reads the confidence, so an uncalibrated or shifted score makes thresholds meaningless." }
  ],
  "out-of-scope": [
    { q: "The top intent scores 0.75 and the second 0.72. What should the assistant do?",
      o: ["Act on the top intent, since 0.75 is high",
          "Fall back to a human at once",
          "Pick at random between them",
          "Ask the user to choose between the two",
          "Treat the message as out of scope"],
      a: 3,
      why: "The margin matters as well as the top score. Two close scores mean ambiguity, so disambiguate." },
    { q: "A flight bot's none class was trained on random Wikipedia sentences. It still accepts 'buy a book'. What fixes it?",
      o: ["More random sentences in the none class",
          "A lower confidence threshold",
          "A larger encoder",
          "Removing the none class",
          "Near misses from your own domain in the none class"],
      a: 4,
      why: "Random sentences are easy to reject. The hard cases sound like your domain but are not supported." },
    { q: "A bot acts above 0.4 and reconfirms between 0.2 and 0.4. A message scores 0.3. What happens?",
      o: ["The bot confirms with the user before acting",
          "The bot acts on the intent",
          "The bot falls back as out of scope",
          "The bot hands off to a person at once",
          "The bot asks the user to rephrase from scratch"],
      a: 0,
      why: "Three bands: act above the high threshold, confirm in the middle, fall back below." }
  ],
  "sequence-labelling": [
    { q: "In BIO tagging of 'fly from New York', what tag does 'York' get?",
      o: ["B-from_city",
          "I-from_city",
          "O",
          "E-from_city",
          "B-to_city"],
      a: 1,
      why: "B marks the first token of a span and I the rest; words outside any span are O." },
    { q: "How should an assistant extract an order ID like `ORD-48213`?",
      o: ["A fine-tuned NER model, trusted as is",
          "An LLM asked to read the ID back",
          "A pattern match, then validation against the system of record",
          "Fuzzy matching on the nearest known ID",
          "The intent classifier's top label"],
      a: 2,
      why: "For IDs, account numbers and card digits, do not trust a learned model; extract with a pattern and validate." },
    { q: "BERT splits 'Heathrow' into several subword pieces. How are NER labels usually handled?",
      o: ["Every piece gets the B tag",
          "The word is dropped from training",
          "The last piece gets the label, the rest are O",
          "Label the first piece and ignore the rest in the loss",
          "The pieces are merged back before the encoder"],
      a: 3,
      why: "Labelling the first piece and masking the others keeps one label per word in the loss." }
  ],
  "attention": [
    { q: "Why are attention scores divided by √dₖ?",
      o: ["To make attention linear in length",
          "To normalise the values before mixing",
          "To keep the KV cache small",
          "To give each head equal weight",
          "Dot products grow with dₖ, and large scores saturate softmax and kill gradients"],
      a: 4,
      why: "With unit-variance entries a dot product has variance dₖ. Scaling by √dₖ keeps softmax out of its flat regions." },
    { q: "How does multi-head attention compare in cost with one head of full width?",
      o: ["About the same, since d_model is split into h heads of d_model / h",
          "h× more, one full head each",
          "Half as much, since heads share keys",
          "Quadratic in the number of heads",
          "Cheaper, since heads skip the softmax"],
      a: 0,
      why: "Splitting the width keeps total cost the same while letting different heads track different relations." },
    { q: "Context length doubles during generation. What happens to KV cache memory?",
      o: ["It grows 4×",
          "It doubles, since it stores keys and values for every past token",
          "It stays the same",
          "It halves, since older tokens are compressed",
          "It grows with the square of the batch size"],
      a: 1,
      why: "Attention compute is quadratic in length, but the cache grows linearly: one set of keys and values per token per layer.",
      pair: "attention-vs-kv-cache" }
  ],
  "encoders-decoders": [
    { q: "You need an intent classifier under 20 ms at high volume. Which model shape fits best?",
      o: ["A large decoder-only model, prompted per message",
          "An encoder-decoder that generates the label",
          "A small fine-tuned encoder such as DistilBERT",
          "A diffusion model over intents",
          "A decoder-only model with beam search"],
      a: 2,
      why: "Encoders give rich representations for understanding tasks, cheaply. Decoders win on generation and changing tasks." },
    { q: "Which pretraining objective does BERT use?",
      o: ["Next-token prediction with a causal mask",
          "Span corruption with text-to-text output",
          "Contrastive matching of images and captions",
          "Masked language modelling: hide about 15% of tokens and predict them",
          "Predicting the noise added to embeddings"],
      a: 3,
      why: "Bidirectional attention plus masked prediction gives BERT both-side context, at the cost of fluent generation.",
      pair: "mlm-vs-next-token" },
    { q: "What is distinctive about T5?",
      o: ["It is encoder-only and used for reranking",
          "It uses no attention",
          "It generates images from text",
          "It is decoder-only with RoPE",
          "It is an encoder-decoder that casts every task as text to text"],
      a: 4,
      why: "T5 reads with an encoder, writes with a decoder that cross-attends, and phrases every task as input text to output text." }
  ],
  "llm-training": [
    { q: "Using training compute of about 6 × parameters × tokens, roughly how many FLOPs does a 7B model on 2T tokens take?",
      o: ["About 8.4 × 10²²",
          "About 1.4 × 10²²",
          "About 8.4 × 10²¹",
          "About 2.8 × 10²²",
          "About 4.2 × 10²³"],
      a: 0,
      why: "6 × 7 × 10⁹ × 2 × 10¹² = 8.4 × 10²² FLOPs." },
    { q: "What does supervised instruction tuning mainly add to a base model?",
      o: ["Most of its world knowledge",
          "Format and instruction following, more than knowledge",
          "A larger context window",
          "Calibrated probabilities",
          "Resistance to prompt injection"],
      a: 1,
      why: "Knowledge comes from pretraining. SFT on prompt and response pairs teaches the model how to answer." },
    { q: "Why can fine-tuning a model on facts it does not know raise hallucination?",
      o: ["It deletes the facts the model knew",
          "It shrinks the context window",
          "It teaches the model to answer confidently even when it has no grounding",
          "It changes the tokenizer",
          "It turns off sampling"],
      a: 2,
      why: "Put knowledge in retrieval and behaviour in tuning, and try prompting before either." }
  ],
  "decoding": [
    { q: "How does top-p (nucleus) sampling differ from top-k?",
      o: ["Top-p always keeps the same number of tokens",
          "Top-p ignores the probabilities",
          "Top-p is deterministic and top-k is random",
          "Top-p keeps the smallest set reaching probability p, so its size follows how peaked the distribution is",
          "Top-p works only with beam search"],
      a: 3,
      why: "Top-k keeps a fixed count; top-p adapts, taking few tokens when the model is sure and more when it is not.",
      pair: "top-p-vs-top-k" },
    { q: "A classifier built on a hosted LLM at temperature 0 sometimes returns a different label for the same input. What is the fix?",
      o: ["Set the temperature lower than 0",
          "Raise top-k to 1,000",
          "Send each request twice and keep the first",
          "Switch to beam search",
          "Constrain the output to the label set and accept small run-to-run variation"],
      a: 4,
      why: "Batching and floating-point order shift logits slightly, so temperature 0 is not fully deterministic on most hosted APIs." },
    { q: "Where does beam search fit better than sampling?",
      o: ["Machine translation, where one faithful output matters more than variety",
          "Open-ended story writing",
          "Brainstorming product names",
          "Casual chat replies",
          "Generating varied test data"],
      a: 0,
      why: "Beam search keeps the best partial sequences: good for translation, bland for open text." }
  ],
  "intents-entities": [
    { q: "A bot has intents `cancel_netflix`, `cancel_spotify` and `cancel_hulu`. What is the better design?",
      o: ["Keep them, since each product is a different action",
          "One cancel intent with the product as an entity",
          "One intent per product per channel",
          "Merge them into a general 'help' intent",
          "Move them all to a FAQ retrieval index"],
      a: 1,
      why: "The action is the intent and the details are entities. If flow and API call match, merge and use an entity." },
    { q: "'My card was lost' and 'my card was declined' share most words. Should they be one intent?",
      o: ["Yes, since they share vocabulary",
          "Yes, with 'lost' and 'declined' as entities",
          "No, they need different handling, so split",
          "No, but only because they are rare",
          "Yes, and let the agent decide later"],
      a: 2,
      why: "Same words with different handling means split; same handling with different words means merge." },
    { q: "Every training phrase was written by the design team, all lowercase and starting 'i want to'. What goes wrong?",
      o: ["Nothing, since consistent data trains faster",
          "The entity extractor stops working",
          "The model needs more layers",
          "The model learns the shared pattern as a shortcut and fails on real phrasing",
          "The intent count becomes too high"],
      a: 3,
      why: "Vary the phrasing, not only the word order, and source examples from production logs." }
  ],
  "dialogue-state": [
    { q: "Asked for a date, the user says 'Friday to Boston'. What should a good state tracker do?",
      o: ["Fill the date and ask for the city later",
          "Reprompt, since the answer has extra words",
          "Hand off to a person",
          "Treat it as a new intent",
          "Fill both the date and the destination"],
      a: 4,
      why: "Accepting over-answering, corrections and digressions is what separates a good tracker from a rigid form." },
    { q: "An LLM agent keeps whether the user is authenticated only in the transcript. What is the risk?",
      o: ["The model may lose or misread it, so authoritative state belongs in code",
          "The transcript uses too many tokens",
          "Authentication cannot be expressed in text",
          "The tool schema becomes invalid",
          "It makes responses slower"],
      a: 0,
      why: "LLMs carry context easily but do not guarantee it. Keep account, order and authentication state in code." },
    { q: "What does joint goal accuracy measure?",
      o: ["The share of slots filled correctly across all turns",
          "The share of turns where every slot in the state is right",
          "The share of conversations that end in success",
          "Intent accuracy on the first turn",
          "Average F1 across slot types"],
      a: 1,
      why: "One wrong slot makes the whole turn wrong, which is why the metric is strict.",
      pair: "joint-goal-vs-slot-accuracy" }
  ],
  "conversation-design": [
    { q: "The user asks to transfer $2,000. Which confirmation fits?",
      o: ["Implicit: repeat the amount and continue",
          "None, since the intent was clear",
          "Explicit: ask the user to confirm amount and recipient before acting",
          "Confirm only if speech recognition confidence is low",
          "Confirm after the transfer is done"],
      a: 2,
      why: "Confirm in proportion to cost of being wrong times chance of being wrong. Money is costly, so ask.",
      pair: "implicit-vs-explicit-confirmation" },
    { q: "The user has failed to answer the same question twice. What should the assistant do next?",
      o: ["Repeat the original prompt word for word",
          "Ask the same question more slowly",
          "Tell the user their answer was invalid",
          "Offer a way out: an alternative or a person",
          "End the conversation"],
      a: 3,
      why: "Escalate per state: rephrase, then options or examples, then an exit after about two failures. Never blame the user." },
    { q: "The bot hands off to a person, but no agents are online. What should happen?",
      o: ["Keep the user waiting in the queue",
          "Return to the start of the bot flow",
          "Tell the user to try again later and end",
          "Repeat the last bot answer",
          "Offer a callback or create a ticket"],
      a: 4,
      why: "A handoff must never be a dead end." }
  ],
  "nlu-llm-hybrid": [
    { q: "What is the hybrid routing pattern for NLU?",
      o: ["A fast classifier handles confident turns and only uncertain ones go to an LLM",
          "An LLM handles every turn and a classifier checks it",
          "Two classifiers vote, and ties go to a person",
          "The LLM writes training data for each turn",
          "Turns alternate between a classifier and an LLM"],
      a: 0,
      why: "An LLM call costs around a second against milliseconds for an encoder, so route, do not replace." },
    { q: "An LLM agent decides to issue a refund. What should authorise it?",
      o: ["The LLM's own confidence score",
          "Server-side checks in code plus a confirmation turn",
          "A second LLM asked whether it agrees",
          "The retrieved policy document",
          "The user's tone"],
      a: 1,
      why: "The LLM proposes; deterministic code authorises money-moving and data-changing actions." },
    { q: "Your FAQ intents moved to retrieval over a knowledge base. A user asks 'what is my account balance?'. What should happen?",
      o: ["Answer from the closest FAQ article",
          "Let the LLM estimate from past chats",
          "Route it to the transactional intent, never to documents",
          "Search the web for the answer",
          "Tell the user the bot cannot help"],
      a: 2,
      why: "RAG suits FAQ content; transactional intents stay routed, so documents never answer account questions." }
  ],
  "error-analysis": [
    { q: "How do you find intents your assistant is missing?",
      o: ["Ask the design team for ideas",
          "Raise the out-of-scope threshold",
          "Read random successful chats",
          "Embed fallback utterances, cluster them, and rank clusters by volume times cost",
          "Add more examples to existing intents"],
      a: 3,
      why: "Clusters of fallback utterances point to gaps; each becomes a new intent, an existing one, the none class or RAG content." },
    { q: "Per-utterance metrics look strong, yet many conversations fail. Why?",
      o: ["The confusion matrix is wrong",
          "The test set is too small",
          "Per-utterance scores are always inflated",
          "The model is overfitting",
          "Many failures are dialog failures that only show in whole conversations"],
      a: 4,
      why: "Review whole conversations, not isolated turns." },
    { q: "Before fixing errors found in labelled conversations, why double-label a subset?",
      o: ["To measure agreement, since label noise caps every fix",
          "To double the training data",
          "To check the reviewers' speed",
          "To train a second model",
          "To meet a vendor requirement"],
      a: 0,
      why: "If two people disagree on the cause, a fix aimed at one label may be aimed at noise." }
  ],
  "assistant-metrics": [
    { q: "Containment is 85%, but many of those customers phone in the next day. What is wrong with the report?",
      o: ["Containment should be computed per turn",
          "Containment alone misleads; pair it with resolution measured from outcomes",
          "The phone calls are a separate product",
          "85% is too low to be meaningful",
          "Containment should exclude greetings only"],
      a: 1,
      why: "A bot that is a wall contains everything. Resolution checks the customer did not come back on another channel." },
    { q: "In tau-bench, what does pass⁸ measure?",
      o: ["The best of eight runs of a task",
          "The average success over eight tasks",
          "The chance that all eight runs of a task succeed",
          "Success within eight turns",
          "Eight judges agreeing on success"],
      a: 2,
      why: "passᵏ rewards consistency: a task counts only if every repeated run gets it right." },
    { q: "How should an A/B test of a new assistant flow be set up?",
      o: ["Randomise by turn, for more samples",
          "Run it for one busy afternoon",
          "Use turn count as the primary metric",
          "Randomise by user over full weekly cycles, with task completion primary",
          "Compare this week's version with last week's"],
      a: 3,
      why: "Users must see one version consistently, weekly patterns must be covered, and shorter conversations can mean abandoned ones." }
  ]
});
