/* Multiple choice for the Systems fundamentals field: 2 or 3 per topic. Checked by baseline/quiz/check.js. */
BASELINE.quiz("systems", {
  "processes-threads": [
    { q: "A web server runs each request on its own thread. One handler writes past the end of a buffer and corrupts memory. What can be affected?",
      o: ["Only that thread, because each thread has its own memory",
          "Any thread in the process, because threads share one address space",
          "Only that handler's stack frame and nothing beyond it",
          "Every process on the machine, because memory is global",
          "Nothing outside the request, because the kernel isolates threads"],
      a: 1,
      why: "A thread owns only its registers and stack; the heap and the rest of the address space are shared. Isolation from corruption is what a separate process buys you.",
      pair: "process-vs-thread" },
    { q: "Bash forks, and the child calls `exec(\"/bin/ls\")`. Why does the output of `ls` still appear in your terminal?",
      o: ["The parent copies the child's output to the terminal after `wait`",
          "`ls` always opens the terminal device itself when it starts",
          "fork makes the child share the parent's thread, so output merges",
          "exec replaces the program but keeps its open file descriptors",
          "The kernel sends all output of a child process to its parent's terminal"],
      a: 3,
      why: "exec swaps the program image but keeps the process and its file descriptors, so stdout still points where bash's stdout pointed." },
    { q: "A service must hold 10,000 connections that spend almost all their time waiting on slow clients. Which design is usually cheapest?",
      o: ["An event loop that waits on all the sockets from a few threads",
          "One thread per connection, since threads give free parallelism",
          "One process per connection, for isolation between clients",
          "A larger thread pool with finer-grained locks on shared state",
          "A longer scheduler time slice so each thread runs to completion"],
      a: 0,
      why: "Threads cost memory and scheduling, and 10,000 of them mostly wait. For many connections that wait on I/O, an event loop holds them in one thread cheaply." }
  ],
  "scheduling": [
    { q: "A container with a 1 CPU limit runs 4 busy threads on a mostly idle 4-core node. Its p99 latency spikes while average CPU looks low. What is the likely cause?",
      o: ["Other pods on the node are taking the cores away from it",
          "The kernel scheduler favours batch jobs over this container",
          "It runs too few threads to make use of the four cores",
          "Memory pressure is forcing the container's pages out to swap",
          "The CPU quota is spent early in each period and the threads wait for the next"],
      a: 4,
      why: "A limit of 1 CPU is 100 ms of CPU time per 100 ms period. Four threads use it in 25 ms of wall time, then all wait 75 ms, even on an idle node. Many teams set requests and drop limits for this reason." },
    { q: "In Python's asyncio, when does the event loop switch from one task to another?",
      o: ["On every timer interrupt, the way the kernel preempts threads",
          "When the running task has used up its fixed time slice",
          "Only when the running task reaches an `await` and yields",
          "Whenever a new request arrives on any open socket",
          "Whenever any thread in the process releases the GIL"],
      a: 2,
      why: "asyncio is cooperative: tasks share one thread and switch only at `await`. A task that never awaits keeps the loop to itself.",
      pair: "preemptive-vs-cooperative" }
  ],
  "system-calls": [
    { q: "A tool copies a file using 1-byte `read` and `write` calls. It is very slow and the disk is barely busy. What is the best fix?",
      o: ["Move the file to a faster SSD so each read returns sooner",
          "Read and write in large buffers so there are far fewer system calls",
          "Split the copy across several threads, each moving one byte at a time",
          "Run the tool at a higher scheduler priority than other processes",
          "Call `fsync` after each byte so the kernel keeps up with the writes"],
      a: 1,
      why: "The time goes to crossing into the kernel billions of times, not to the disk. A 64 KiB buffer cuts the calls by a factor of tens of thousands." },
    { q: "Why does a system call cost far more than an ordinary function call?",
      o: ["It always has to wait for the disk before returning",
          "It starts a short-lived helper process inside the kernel",
          "It allocates a fresh user-space stack every time it is called",
          "It traps into kernel mode, and the mode switch disturbs caches",
          "It waits in the scheduler's queue until the kernel gets a turn"],
      a: 3,
      why: "The trap into kernel mode, the checks, and the cache and TLB disturbance make each crossing expensive, and the 2018 Meltdown mitigations raised the cost further." },
    { q: "A program reads the time with `gettimeofday` millions of times a second on Linux, yet it stays cheap. Why?",
      o: ["It is served from the vDSO, code the kernel maps into the process, with no real trap",
          "The CPU caches the result of each system call for the next caller",
          "The compiler replaces it with a constant read once at startup",
          "It is batched with other calls through io_uring automatically",
          "Time calls run in user mode because they touch no hardware"],
      a: 0,
      why: "The vDSO lets a few read-only calls like the clock run in user space, avoiding the mode switch altogether. It is one of the tricks that exist because real system calls are costly." }
  ],
  "virtual-memory": [
    { q: "A program calls `malloc` for 1 GB on Linux and then writes to only 10 MB of it. Roughly how much does its resident memory (RSS) grow?",
      o: ["About 1 GB, because malloc reserves real RAM at once",
          "About 1 GB plus 10 MB for the page tables",
          "Nothing until the program calls `free`",
          "It depends only on how much swap is configured",
          "About 10 MB, because pages are backed only when first touched"],
      a: 4,
      why: "Linux reserves the address range without backing it. Each first write to a page faults, and the kernel allocates one zeroed page then, so RSS grows with what is touched." },
    { q: "A dashboard shows a process with 8 GB of virtual memory inside a container limited to 2 GB, and the process runs fine. What explains it?",
      o: ["The container limit is not enforced until the node is full",
          "The extra 6 GB is all in swap, which limits do not count",
          "Virtual size counts reserved address space, not RAM in use",
          "The process is about to be OOM killed and has not been yet",
          "Huge pages make virtual size look four times larger than it is"],
      a: 2,
      why: "Virtual size, resident size and page cache are different numbers. Reserved but untouched address space costs no RAM, so it does not count toward the memory limit.",
      pair: "virtual-vs-resident" },
    { q: "On Linux with default settings, a machine runs short of memory. Where does the failure usually show up?",
      o: ["`malloc` returns NULL as soon as a request exceeds free RAM",
          "The OOM killer ends a process later, when pages are touched",
          "The kernel pauses every process until memory is freed",
          "The next `fork` call fails with an error before anything else",
          "The page cache refuses new files but programs are unaffected"],
      a: 1,
      why: "Linux overcommits, so allocation usually succeeds. The shortage arrives when pages are actually used, and the OOM killer picks a process to kill." }
  ],
  "memory-hierarchy": [
    { q: "Summing a 4,096 × 4,096 array of ints row by row is several times faster than column by column, with the same Big-O. Why?",
      o: ["Column order performs more additions than row order",
          "Row order lets the compiler skip half of the elements",
          "Column order needs more system calls to reach memory",
          "Row order uses every value in each cache line and the prefetcher keeps up",
          "Column order runs on a slower core chosen by the scheduler"],
      a: 3,
      why: "A 64-byte line holds 16 ints. Walking rows uses all 16 and lets prefetching work; walking columns jumps 16 KiB each step, so nearly every read misses cache." },
    { q: "Two threads each increment their own counter, and the two counters sit next to each other in one struct. Going from one thread to two makes it slower. Why?",
      o: ["Both counters share a cache line, which bounces between the cores",
          "The two threads must take a lock that the struct carries",
          "The kernel runs both threads on one core to save power",
          "Incrementing an integer is a system call on most platforms",
          "The struct is copied to each thread on every increment"],
      a: 0,
      why: "This is false sharing. The variables are separate, but caches work in lines, so each write invalidates the other core's copy of the whole line.",
      pair: "false-sharing-vs-race" },
    { q: "Two O(n) loops do the same work: one walks a linked list, the other an array. What do you expect?",
      o: ["They run at about the same speed, since Big-O is equal",
          "The linked list wins because it avoids copying data",
          "The array wins only when n is smaller than the L1 cache",
          "The linked list wins because the prefetcher follows pointers",
          "The array often wins by a wide margin, because pointer chasing misses cache"],
      a: 4,
      why: "Big-O hides a factor near 100 between a cache hit and a DRAM miss. Measure cache misses with a profiler such as `perf stat` before trusting complexity alone." }
  ],
  "latency-numbers": [
    { q: "A page makes 30 sequential database calls. The database moves from the same datacenter to a region 70 ms away, and the page now takes about 2 seconds. What is the best fix?",
      o: ["Compress the query results so fewer bytes cross the network",
          "Upgrade to a larger database instance with more CPU",
          "Batch the 30 calls into one query so there is one round trip",
          "Add an index to every table the page touches",
          "Raise the network bandwidth between the two regions"],
      a: 2,
      why: "30 round trips at 70 ms is 2.1 s. The cost is round trips, not bytes or compute, so one batched query brings it back near 70 ms." },
    { q: "Roughly how does a random read from an SSD compare with a read from main memory?",
      o: ["About the same, since both are solid-state",
          "On the order of 100× slower",
          "About 10× slower",
          "On the order of 100,000× slower",
          "Faster, because the SSD has its own controller cache"],
      a: 1,
      why: "Memory is about 100 ns and a random SSD read about 16 microseconds: two orders of magnitude. The ratios are what matter for estimates, not exact figures." },
    { q: "Over the years, network and memory bandwidth have grown much faster than latency has improved. What follows for design?",
      o: ["Payload size is now the main cost, so compress everything",
          "Latency will soon stop mattering once links are fast enough",
          "Distant regions now cost about the same as nearby ones",
          "Cutting round trips usually matters more than shrinking payloads",
          "Chatty protocols are fine as long as each message is small"],
      a: 3,
      why: "Bigger pipes do nothing for the speed of light or memory access time. Batch calls and avoid chatty protocols." }
  ],
  "file-systems": [
    { q: "A program calls `write` on a file, the call returns success, and power fails one second later. Is the data on disk?",
      o: ["Not necessarily: `write` returns once data is in the page cache",
          "Yes: a successful `write` means the data reached the disk",
          "Yes, if the file system is journaling, such as ext4",
          "No: data reaches disk only when the file is closed",
          "Yes, because the kernel flushes every write within a millisecond"],
      a: 0,
      why: "`write` copies into RAM and the kernel flushes later. Only `fsync` asks for stable storage and waits. Journaling protects metadata consistency, not your unflushed data.",
      pair: "write-vs-fsync" },
    { q: "An app must replace `config.json` so that a crash leaves either the old file or the new one, never a mix. Which sequence does that?",
      o: ["Open `config.json`, overwrite it in place, then call `fsync` on it",
          "Delete `config.json`, then write the new contents to the same name",
          "Write the new contents in place inside a journaling file system",
          "Write `config.json.tmp`, rename it over the old file, then `fsync` the tmp file",
          "Write and `fsync` a tmp file, rename it over the old one, then `fsync` the directory"],
      a: 4,
      why: "Rename is atomic on POSIX, but the new data must be durable before the rename, and the directory must be fsynced so the rename itself survives a crash." }
  ],
  "gpu": [
    { q: "Adding two vectors of a billion floats on a modern GPU leaves its arithmetic units nearly idle. What limits the speed?",
      o: ["The number of threads per warp",
          "The CPU's clock speed during the launch",
          "Memory bandwidth, since there is one add per several bytes moved",
          "The size of the instruction cache on each core",
          "The cost of converting floats to integers"],
      a: 2,
      why: "Elementwise work has low arithmetic intensity: few operations per byte read. It waits on HBM bandwidth, unlike a matrix multiply, which reuses each byte many times.",
      pair: "memory-bound-vs-compute-bound" },
    { q: "Inside one warp of 32 threads, half take the `if` branch and half take the `else`. What happens?",
      o: ["Each half runs on its own streaming multiprocessor in parallel",
          "The two branches run one after the other, with half the threads idle each time",
          "The GPU picks one branch and every thread in the warp follows it",
          "The warp splits into two new warps of 16 threads each",
          "The compiler refuses to build kernels with branches in them"],
      a: 1,
      why: "A warp executes one instruction at a time for all its threads, so divergent branches are serialised and part of the warp waits through each one." },
    { q: "A model's forward pass runs many small elementwise operations, each a separate kernel. Which change usually helps more than buying a faster GPU?",
      o: ["Copying the data to the CPU between operations",
          "Raising the batch size until memory runs out",
          "Running each operation on its own CUDA stream",
          "Fusing the operations so data stays in on-chip memory between steps",
          "Converting the operations to run in double precision"],
      a: 3,
      why: "Separate kernels read and write HBM at every step. Fusion keeps intermediate values on chip, which attacks the real limit: memory bandwidth and launch overhead, not FLOPs." }
  ],
  "races-locks": [
    { q: "Two threads each run `count += 1` a million times on a shared counter. The total ends short of 2,000,000 and differs each run. Why?",
      o: ["The increment is a load, an add and a store, and two threads can interleave them",
          "Integer overflow wraps the counter before it reaches the end",
          "The CPU caches the counter and never writes it back",
          "One thread always finishes before the other starts its loop",
          "The scheduler drops some instructions when it switches threads"],
      a: 0,
      why: "Both threads can load 41, both add one, and both store 42: one increment is lost. The outcome depends on timing, which is what a race condition is." },
    { q: "Which change makes that shared counter exact with the least overhead?",
      o: ["Declare the counter `volatile` so every read goes to memory",
          "Add a short sleep between increments in each thread",
          "Switch the counter to a 64-bit integer type",
          "Pin both threads to the same CPU core",
          "Use an atomic `fetch_add` instruction for the increment"],
      a: 4,
      why: "An atomic does the read-modify-write in one indivisible step. `volatile` does not make it atomic, and one core still lets a thread be preempted between load and store." },
    { q: "A race condition passed every test and fails about once a week in production. Which approach best avoids this class of bug?",
      o: ["Run the test suite many more times before each release",
          "Add retries around the code that touches shared data",
          "Avoid sharing: give each piece of state one owner and pass messages",
          "Replace every lock with a lock-free data structure",
          "Increase thread priorities so the critical code runs first"],
      a: 2,
      why: "Races hide from tests because they depend on timing. Not sharing state removes the possibility; lock-free code is harder to get right, not safer." }
  ],
  "deadlock": [
    { q: "A transfer from account 1 to 2 locks row 1 then row 2, while a transfer from 2 to 1 locks row 2 then row 1. They sometimes freeze. What is the standard fix?",
      o: ["Add a lock timeout so one transfer fails after a few seconds",
          "Always lock the lower account id first, whatever the direction",
          "Run the two transfers on different threads",
          "Take the locks faster so the window is smaller",
          "Lock the whole accounts table for every transfer"],
      a: 1,
      why: "Deadlock needs a cycle of waiting. A global lock order removes the cycle. Locking the whole table also works but kills concurrency; a timeout only hides the cause." },
    { q: "A low-priority thread holds a lock that a high-priority thread needs, while a medium-priority thread keeps the CPU busy. What is this called?",
      o: ["Deadlock", "Livelock", "Starvation of the low thread", "Priority inversion", "A race condition"],
      a: 3,
      why: "The high-priority thread is stuck behind the low one, which cannot run because the medium one has the CPU. No cycle of locks, so it is not a deadlock.",
      pair: "deadlock-vs-priority-inversion" },
    { q: "Under load, a service shows periodic lock timeout errors that clear on their own. What should you look for first?",
      o: ["Two code paths that take the same locks in different orders",
          "A slow disk that delays every transaction equally",
          "A memory leak that grows until the next deploy",
          "A DNS change that sends traffic to the wrong host",
          "A thread pool that is larger than the number of cores"],
      a: 0,
      why: "Lock timeouts turn deadlocks into slow errors and hide them. Periodic timeouts under load are the classic sign of inconsistent lock order." }
  ],
  "event-loops": [
    { q: "An asyncio chat server holds 1,000 requests waiting on an LLM API. Someone adds a blocking `requests.get` call taking 2 s to one handler. What happens?",
      o: ["Only that request slows down; the others continue",
          "asyncio moves the blocking call to a thread automatically",
          "The handler raises an error because blocking is not allowed",
          "The kernel preempts the handler so other tasks can run",
          "Every connection on that loop stalls for those 2 s"],
      a: 4,
      why: "Async makes waiting cheap, not work fast. A blocking call never yields to the loop, so nothing else runs. Move it to a thread pool or use an async client." },
    { q: "What is the main difference between `epoll` and io_uring on Linux?",
      o: ["epoll works only for files and io_uring only for sockets",
          "epoll needs one thread per socket and io_uring needs none",
          "epoll says a socket is ready; io_uring does the operation and reports completion",
          "epoll is for TCP and io_uring is for UDP",
          "io_uring is the Windows name for the same readiness model"],
      a: 2,
      why: "epoll is a readiness model: you still make the read yourself. io_uring is a completion model, works for files too, and submits many operations through shared rings with few system calls.",
      pair: "readiness-vs-completion" }
  ],
  "ip-packets": [
    { q: "You split a VPC range `10.0.0.0/16` into `/24` subnets. How many subnets do you get?",
      o: ["16", "256", "24", "65,536", "8"],
      a: 1,
      why: "A /24 fixes 8 more bits than a /16, and 2⁸ = 256 subnets of 256 addresses each." },
    { q: "Packet captures on a healthy network show some packets lost and some arriving out of order. What does that mean?",
      o: ["A router is failing and must be replaced",
          "The MTU is set too high on one of the hosts",
          "The NAT device is rewriting packets incorrectly",
          "This is normal for IP; the layers above cope, and it costs latency",
          "TCP has been disabled on one side of the connection"],
      a: 3,
      why: "IP is best effort and promises no delivery or order. TCP, QUIC and your retries exist to handle that, and their recovery shows up as latency." },
    { q: "A laptop on home Wi-Fi can open connections to any website, but an outside host cannot open a connection to it. Why, by default?",
      o: ["NAT shares one public address and has no mapping for an unsolicited inbound connection",
          "The laptop's IPv4 address is too long to be routed from outside",
          "Routers drop all packets that carry a destination port",
          "BGP only advertises routes toward servers, not laptops",
          "Inbound connections require IPv6 on both ends to work at all"],
      a: 0,
      why: "NAT rewrites private addresses to a shared public one and tracks connections the inside started. An inbound packet with no matching entry has nowhere to go." }
  ],
  "tcp": [
    { q: "A new HTTPS request goes from London to Virginia, about 80 ms round trip, with TCP and TLS 1.3. Roughly when does the first response byte arrive?",
      o: ["About 80 ms", "About 40 ms", "About 160 ms", "About 400 ms", "About 240 ms"],
      a: 4,
      why: "One round trip for the TCP handshake, one for TLS 1.3, one for the request and first bytes. A warm, reused connection costs one." },
    { q: "A client sends two 100-byte messages with two `send` calls. The server's first `recv` returns 150 bytes. What is going on?",
      o: ["A packet was corrupted and TCP failed to catch it",
          "The server's buffer is too small and must be enlarged",
          "Nothing wrong: TCP is a byte stream, so the protocol needs its own framing",
          "The client's kernel merged the messages because of a bug",
          "TCP lost the boundary because of a retransmission"],
      a: 2,
      why: "TCP delivers bytes in order, not messages. One send can arrive as two reads or two as one, so protocols add a length prefix or a delimiter.",
      pair: "byte-stream-vs-message" },
    { q: "Why can one lost packet delay unrelated requests multiplexed on the same TCP connection?",
      o: ["TCP must close and reopen the connection after any loss",
          "TCP delivers bytes in order, so everything after the gap waits for the retransmission",
          "Congestion control stops all sending until the loss is reported",
          "The receiver discards all later packets and asks for them again",
          "Each request must finish its own handshake again after a loss"],
      a: 1,
      why: "This is head-of-line blocking. Bytes behind the gap may have arrived, but TCP holds them until the missing one is retransmitted." }
  ],
  "udp": [
    { q: "A voice call sends a 20 ms audio frame every 20 ms, and one frame is lost. Why is UDP the better transport here?",
      o: ["UDP retransmits lost frames faster than TCP does",
          "UDP has a larger maximum packet size than TCP",
          "UDP encrypts audio and TCP does not",
          "A late frame is worthless, so concealing it beats stalling for a retransmit",
          "UDP guarantees frames arrive in order without a handshake"],
      a: 3,
      why: "Over TCP, later frames wait behind the retransmission and the listener hears a freeze. Over UDP, the player conceals one frame and stays on time." },
    { q: "A WebRTC app works at home but fails for users in some offices. What is the likely cause and the usual remedy?",
      o: ["The firewall blocks UDP; fall back to a relay over TCP or TLS, such as TURN",
          "Office networks are too fast for UDP; slow the sender down",
          "UDP packets are too large; lower the audio quality",
          "Offices use IPv6; switch the app to IPv4 only",
          "The office DNS is stale; lower the TTL on the app's records"],
      a: 0,
      why: "Corporate firewalls often block or throttle UDP, so real-time products keep a TCP or TLS fallback path." }
  ],
  "dns": [
    { q: "You will move `api.example.com` to a new IP next week, and its record has a TTL of one day. What should you do?",
      o: ["Change the record during the move and wait one minute",
          "Raise the TTL so the new answer is cached longer",
          "Restart your own resolver after the change",
          "Delete the record first, then add the new one",
          "Lower the TTL a few days before, then change the record"],
      a: 4,
      why: "Resolvers keep the old answer for the TTL in force when they cached it. Lowering it ahead of time means the change spreads quickly; some clients ignore TTLs anyway." },
    { q: "With a cold cache, in what order does a recursive resolver find the address of `api.example.com`?",
      o: ["It asks the authoritative server for example.com first, then the root",
          "It asks the `.com` servers, which return the address directly",
          "Root servers, then the `.com` servers, then the authoritative servers for example.com",
          "It broadcasts the query to every DNS server it knows",
          "It asks the nearest router, which keeps a full copy of DNS"],
      a: 2,
      why: "Each level points to the next: root to `.com`, `.com` to example.com's name servers, which hold the record. Every answer is then cached for its TTL." },
    { q: "Users in two countries get different IP addresses for the same name at the same moment. What is the most likely reason?",
      o: ["One of the users has a corrupted DNS cache",
          "The service uses DNS to answer by region or health, as a load balancer",
          "DNS records rotate randomly every second by design",
          "One country still uses IPv4 and the other only IPv6",
          "The domain has two CNAME records that conflict"],
      a: 1,
      why: "Because answers can depend on who asks, providers return different addresses by location or health to steer traffic." }
  ],
  "http": [
    { q: "A page loads many images over one connection, and one packet is lost. How do HTTP/2 and HTTP/3 differ in what waits?",
      o: ["Both stall every stream, because both run over TCP",
          "HTTP/2 waits only for the affected stream; HTTP/3 stalls all of them",
          "Neither waits, since both retransmit at the application layer",
          "HTTP/2 stalls every stream; HTTP/3 stalls only streams whose data was lost",
          "HTTP/3 reopens the connection and both resend everything"],
      a: 3,
      why: "HTTP/2 multiplexes over one TCP stream, so TCP's in-order delivery blocks all streams. QUIC under HTTP/3 orders each stream separately.",
      pair: "http2-vs-http3" },
    { q: "After switching clients to HTTP/2, one backend gets most of the traffic behind a load balancer that balances per connection. Why?",
      o: ["Each long-lived HTTP/2 connection carries many requests, so per-connection balancing goes uneven",
          "HTTP/2 always routes to the first backend in the list",
          "HTTP/2 compresses headers so the balancer cannot read them",
          "HTTP/2 disables health checks on the balancer",
          "The backend that supports HTTP/2 best is chosen on purpose"],
      a: 0,
      why: "Multiplexing means few connections carry all the requests. Balance per request (a layer 7 balancer) or cycle connections." },
    { q: "Why do browsers using HTTP/1.1 open several connections to the same host?",
      o: ["HTTP/1.1 limits each connection to one image type",
          "Each connection is encrypted with a different key for safety",
          "Servers require a new connection for every request",
          "Several connections avoid DNS lookups for each request",
          "Each connection carries one request at a time, so parallel connections fetch in parallel"],
      a: 4,
      why: "HTTP/1.1 has no multiplexing, so a slow response blocks the next on that connection. Browsers use about six connections per host to work around it." }
  ],
  "tls": [
    { q: "An attacker records a site's TLS 1.3 traffic for a year, then steals the server's private key. Can they decrypt the recordings?",
      o: ["Yes, the private key decrypts every session it signed",
          "Yes, if the certificate has not expired yet",
          "No, because session keys came from an ephemeral Diffie-Hellman exchange",
          "No, because TLS 1.3 deletes traffic after each session",
          "Only the first message of each session, the ClientHello"],
      a: 2,
      why: "The server key only signs the handshake. Session keys come from a fresh key exchange each time and are discarded, which is forward secrecy." },
    { q: "Which request is safe to send as TLS 1.3 0-RTT data?",
      o: ["A POST that transfers money between accounts",
          "A GET that loads a public product page",
          "A request that places an order and charges a card",
          "A login request that sets a new password",
          "A DELETE that removes a user's account"],
      a: 1,
      why: "0-RTT data can be replayed by an attacker, so it must only carry requests that are safe to repeat." },
    { q: "TLS is terminated at the load balancer, and the balancer forwards plain HTTP to the app servers. What does that mean?",
      o: ["The traffic is still encrypted end to end",
          "The app servers must hold the certificate's private key too",
          "Clients see a certificate warning for every request",
          "Traffic between the balancer and the servers is plaintext unless you encrypt that hop",
          "The balancer cannot route by path any more"],
      a: 3,
      why: "Encryption ends where TLS ends. Anything on the internal network can read the hop behind the balancer unless it is encrypted again." }
  ],
  "sockets": [
    { q: "A load-test client opens a new TCP connection for every request, thousands per second to one server, and starts failing to connect. What is the likely cause?",
      o: ["Ephemeral port exhaustion, worsened by connections waiting in TIME_WAIT",
          "The server's listening socket is closed after each accept",
          "DNS can only resolve the name a fixed number of times",
          "TCP forbids more than one connection between two hosts",
          "The client's CPU cannot run that many handshakes"],
      a: 0,
      why: "Each outgoing connection needs a local port, and closed ones linger in TIME_WAIT. Reusing connections fixes it." },
    { q: "A server calls `accept` on its listening socket. What does `accept` return?",
      o: ["The same listening socket, now bound to that client",
          "The client's IP address and nothing else",
          "A new port number that the client must reconnect to",
          "A thread that will handle the client",
          "A new socket descriptor for that one client"],
      a: 4,
      why: "The listening socket stays on its port. Each accepted connection gets its own descriptor, named by source and destination address and port.",
      pair: "listening-vs-connected-socket" },
    { q: "A server crashes with \"too many open files\" at about 1,024 concurrent connections on a machine with plenty of RAM. What limit did it hit?",
      o: ["The number of TCP ports on the machine",
          "The kernel's maximum number of threads",
          "The per-process file descriptor limit, set with `ulimit -n`",
          "The size of the listen backlog queue",
          "The maximum number of inodes on the file system"],
      a: 2,
      why: "Each socket is a file descriptor, and a common default limit is 1,024 per process. Raise it, and reuse connections." }
  ]
});
