"""Build INTERVIEWS.html, the hub for every interview loop.

    python interviews/hub.py      -> INTERVIEWS.html at the repo root

One card per loop module (interviews/*.py with a LOOP dict), newest first, in a grid: the
status and date, the company as a wordmark with the round beside it, one line of context,
total hours from its tracker sessions with a thin progress line, and links to the loop page
and to the job post or company site in its SOURCES. Cards are one neutral surface; the only
colour is the company name, in its brand colour: LOOP["brand"] (and LOOP["brand_dark"] when
the brand colour does not read on the dark surface), one home, in the loop's module. A loop
with an empty when_iso is upcoming with its date to be set, and sorts first. Progress
(sessions closed, hours banked) is read in the browser from the tracker's own store,
selfstudy.m1.planner; the hub never writes to it. A new loop appears when its module is
added and this is rerun.
"""
import datetime, hashlib, importlib, io, json, os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)
from build import sessions_from_tracker   # the one parser of the tracker's sessions


def minutes(s):
    """'1h 15m' -> 75, '45m' -> 45, '1h' -> 60."""
    h = re.search(r"(\d+)\s*h", s or "")
    m = re.search(r"(\d+)\s*m", s or "")
    return (int(h.group(1)) * 60 if h else 0) + (int(m.group(1)) if m else 0)


def company(L):
    """LOOP['company'] if set, else the title's first word: 'ZenML round 3' -> 'ZenML'."""
    return L.get("company") or re.split(r"[\s,]+", L["title"].strip())[0]


def round_of(title, co):
    """The title without its company, capitalised: 'Mphasis, technical' -> 'Technical'."""
    r = title.strip()[len(co):].lstrip(" ,") if title.strip().startswith(co) else title.strip()
    return r[:1].upper() + r[1:]


def links(sources):
    """The job post and the company site, only from URLs the module already has."""
    out = []
    for label, pat in (("Job post", r"\bjob\b"), ("Company", r"\bcompany\b|^\S+\.(ai|com|io)$")):
        hit = next((s for s in sources if s.get("url") and re.search(pat, s["label"], re.I)), None)
        if hit and all(hit["url"] != o["url"] for o in out):
            out.append({"label": label, "url": hit["url"], "title": hit["label"]})
    return out


def loops():
    out = []
    for f in sorted(os.listdir(HERE)):
        if not f.endswith(".py") or f in ("build.py", "hub.py") or f.startswith("_"):
            continue
        m = importlib.import_module(f[:-3])
        L = getattr(m, "LOOP", None)
        if not L:
            continue
        d = datetime.datetime.fromisoformat(L["when_iso"]) if L["when_iso"] else None
        for k in ("brand", "brand_dark"):
            assert re.fullmatch(r"#[0-9A-Fa-f]{6}", L.get(k) or "#000000"), "%s: LOOP[%r] is not a #rrggbb colour" % (f, k)
        sessions = [{"id": s["id"], "min": minutes(s.get("len"))} for s in sessions_from_tracker(getattr(m, "SESSION_IDS", []))]
        co = company(L)
        out.append({
            "title": L["title"], "subtitle": L.get("subtitle", ""), "when": L["when"], "when_iso": L["when_iso"],
            "date": "%s %d %s %d" % (d.strftime("%a"), d.day, d.strftime("%b"), d.year) if d else "",
            "company": co, "round": round_of(L["title"], co),
            "brand": L.get("brand", ""), "brandDark": L.get("brand_dark", ""),
            "href": "interviews/" + f[:-3].replace("_", "-") + ".html",
            "sessions": sessions, "total": sum(s["min"] for s in sessions),
            "links": links(getattr(m, "SOURCES", [])),
        })
    # Newest first; a loop with no date yet is still to come, so it goes on top.
    out.sort(key=lambda x: datetime.datetime.fromisoformat(x["when_iso"]).timestamp() if x["when_iso"] else float("inf"), reverse=True)
    return out


PAGE = r"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Interview loops</title>
<link rel="icon" type="image/svg+xml" href="brand/accelerate.svg">
<link rel="stylesheet" href="fonts/fonts.css">
<link rel="stylesheet" href="site/tokens.css">
<link rel="stylesheet" href="site/nav.css">
<script src="site/nav.js" defer></script>
<!-- Generated by interviews/hub.py from the loop modules and the tracker's sessions.
     Edit those and rebuild; do not edit this file by hand. -->
<style>
* { box-sizing: border-box; }
body { margin: 0; background: var(--bg); color: var(--ink); font: var(--fs-md)/var(--lh-body) var(--font); -webkit-font-smoothing: antialiased; }
a { color: var(--accent); text-decoration: none; }
a:hover { text-decoration: underline; text-underline-offset: 3px; }
:focus-visible { outline: 2px solid var(--accent); outline-offset: 2px; border-radius: var(--radius-sm); }
code { font-family: var(--mono); font-size: var(--fs-code); background: var(--sunken); padding: 1px var(--s1); border-radius: var(--radius-sm); }
.wrap { max-width: 1180px; margin: 0 auto; padding: 0 var(--s5); }
.top { display: flex; flex-wrap: wrap; align-items: center; gap: var(--s2) var(--s5); padding: var(--s4) 0 var(--s3); border-bottom: var(--hair); }
h1 { font-size: var(--fs-2xl); font-weight: var(--w-strong); line-height: var(--lh-tight); margin: 0; }
.lead { color: var(--soft); margin: var(--s4) 0 var(--s5); max-width: var(--measure); }
.lead b { color: var(--ink); font-weight: var(--w-strong); }

/* The loops: a grid of cards, newest first, all one neutral surface. The only colour is the
   company name, set in its brand colour like a wordmark (--b, and --bd on the dark surface,
   given per card from the loop's module). A card uses three sizes: 12 meta, 13 context and
   links, 17 the name. */
.grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(260px, 1fr)); gap: var(--s4); margin: 0 0 var(--s7); padding: 0; list-style: none; }
.loop { display: flex; flex-direction: column; min-width: 0; background: var(--surface); border: var(--hair); border-radius: var(--radius); padding: var(--s4); }
.st { font-size: var(--fs-xs); color: var(--muted); margin: 0; }
.st b { color: var(--ink); font-weight: var(--w-strong); }
.loop h2 { font-size: var(--fs-lg); line-height: var(--lh-tight); margin: var(--s3) 0 var(--s1); }
.loop h2 a { color: var(--soft); }
.co { color: var(--b, var(--ink)); font-weight: var(--w-strong); margin-right: var(--s2); }
.rd { font-weight: var(--w-regular); }
@media (prefers-color-scheme: dark) { :root:not([data-theme="light"]) .co { color: var(--bd, var(--b, var(--ink))); } }
:root[data-theme="dark"] .co { color: var(--bd, var(--b, var(--ink))); }
.ctx { font-size: var(--fs-sm); color: var(--soft); margin: 0; overflow: hidden; display: -webkit-box; -webkit-box-orient: vertical; -webkit-line-clamp: 2; }
.ft { margin-top: auto; padding-top: var(--s5); }   /* progress and links sit on one baseline across a row */
.hrs { font-size: var(--fs-xs); color: var(--muted); margin: 0; }
.hrs b { color: var(--ink); font-weight: var(--w-strong); }
.bar { height: 2px; background: var(--rule); margin: var(--s2) 0 0; overflow: hidden; }
.bar i { display: block; height: 100%; background: var(--soft); }
.go { display: flex; flex-wrap: wrap; gap: var(--s1) var(--s4); margin: 0; padding-top: var(--s3); font-size: var(--fs-sm); }
.go a { color: var(--soft); }
.go a:first-child { color: var(--ink); font-weight: var(--w-strong); }
.empty { background: var(--sunken); border-radius: var(--radius-lg); padding: var(--s5); max-width: var(--measure); }
.empty b { display: block; font-weight: var(--w-strong); }
.empty p { color: var(--soft); margin: var(--s1) 0 0; }
@media (max-width: 720px) {
  .wrap { padding: 0 var(--s4); }
  .top { padding: var(--s3) 0; }
}
</style>
</head>
<body>
<div class="wrap">
  <header class="top">
    <h1>Interview loops</h1>
    <nav class="sn-top" data-site-nav data-here="interviews"></nav>
  </header>
  <main>
    <p class="lead" id="lead"></p>
    <ul class="grid" id="loops"></ul>
  </main>
</div>
<script type="application/json" id="hub-data">{{DATA}}</script>
<script>
"use strict";
(function () {
  var LOOPS = JSON.parse(document.getElementById("hub-data").textContent);
  var TRACKER = "selfstudy.m1.planner";   /* the tracker's own store: read here, never written */

  function esc(s) { return String(s == null ? "" : s).replace(/[&<>"]/g, function (c) { return { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c]; }); }
  function done() {
    try { var t = JSON.parse(window.localStorage.getItem(TRACKER) || "{}"); return (t && t.done) || {}; }
    catch (err) { console.error("Could not read " + TRACKER, err); return {}; }
  }
  function hm(min) {
    if (!min) { return "0h"; }
    var h = Math.floor(min / 60), m = min % 60;
    return (h ? h + "h" : "") + (h && m ? " " : "") + (m || !h ? m + "m" : "");
  }

  function progress(L, d) {
    var n = L.sessions.length;
    if (!n) { return '<p class="hrs">No tracker sessions.</p>'; }
    var closed = L.sessions.filter(function (s) { return d[s.id]; });
    var banked = closed.reduce(function (a, s) { return a + s.min; }, 0);
    var line = closed.length === n
      ? "<b>All " + n + " sessions closed</b>, " + hm(banked)
      : "<b>" + closed.length + "</b> of " + n + " sessions, <b>" + hm(banked) + "</b> of " + hm(L.total);
    return '<p class="hrs">' + line + "</p>" +
      '<div class="bar" role="progressbar" aria-label="Hours banked" aria-valuemin="0" aria-valuemax="' + L.total + '" aria-valuenow="' + banked + '"><i style="width:' +
      (L.total ? Math.round(100 * banked / L.total) : 0) + '%"></i></div>';
  }

  function draw() {
    var d = done(), now = Date.now(), next = null;
    var grid = document.getElementById("loops"), lead = document.getElementById("lead");
    if (!LOOPS.length) {
      grid.outerHTML = '<div class="empty"><b>No interview loops yet.</b><p>Add one: write <code>interviews/&lt;module&gt;.py</code> with a <code>LOOP</code> dict, ' +
        "then run <code>python interviews/hub.py</code>. It appears here as a tile.</p></div>";
      lead.hidden = true;
      return;
    }
    grid.innerHTML = LOOPS.map(function (L) {
      var past = !!L.when_iso && new Date(L.when_iso).getTime() <= now;   /* no date yet: still to come */
      if (!past) { next = L; }
      var ctx = L.subtitle || L.company;
      var brand = (L.brand ? "--b:" + L.brand + ";" : "") + (L.brandDark ? "--bd:" + L.brandDark + ";" : "");
      return '<li class="loop"' + (brand ? ' style="' + esc(brand) + '"' : "") + ">" +
        '<p class="st" title="' + esc(L.company + ". " + L.when) + '">' +
        (past ? "Happened, " + esc(L.date) : "<b>Upcoming</b>, " + (L.date ? esc(L.date) : "date to be set")) + "</p>" +
        '<h2><a href="' + esc(L.href) + '"><span class="co">' + esc(L.company) + "</span>" +
        (L.round ? '<span class="rd">' + esc(L.round) + "</span>" : "") + "</a></h2>" +
        '<p class="ctx" title="' + esc(ctx) + '">' + esc(ctx) + "</p>" +
        '<div class="ft">' + progress(L, d) +
        '<div class="go"><a href="' + esc(L.href) + '">Loop page</a>' +
        L.links.map(function (k) { return '<a href="' + esc(k.url) + '" target="_blank" rel="noopener" title="' + esc(k.title) + '">' + esc(k.label) + "</a>"; }).join("") +
        "</div></div></li>";
    }).join("");
    var n = LOOPS.length + (LOOPS.length === 1 ? " loop" : " loops") + ", newest first. ";
    lead.innerHTML = next
      ? esc(n) + "Next: <b>" + esc(next.title) + "</b>. " + esc(next.when.replace(/\.$/, "")) + "."
      : esc(n) + "None is scheduled. A new loop is a new <code>interviews/&lt;module&gt;.py</code>.";
  }

  draw();
  window.addEventListener("storage", function (e) { if (e.key === TRACKER) { draw(); } });
}());
</script>
</body>
</html>
"""


def build():
    data = loops()
    page = PAGE
    for f in ("site/tokens.css", "site/nav.js", "site/nav.css"):
        v = hashlib.sha1(io.open(os.path.join(ROOT, f), "rb").read()).hexdigest()[:8]
        page = page.replace('%s"' % f, '%s?v=%s"' % (f, v))
    page = page.replace("{{DATA}}", json.dumps(data, ensure_ascii=False).replace("</", "<\\/"))
    out = os.path.join(ROOT, "INTERVIEWS.html")
    io.open(out, "w", encoding="utf-8", newline="\n").write(page)
    print("wrote %s: %d bytes, %d loops, %d sessions" % (out, len(page), len(data), sum(len(x["sessions"]) for x in data)))


if __name__ == "__main__":
    assert minutes("1h 15m") == 75 and minutes("45m") == 45 and minutes("1h") == 60 and minutes(None) == 0
    assert company({"title": "ZenML round 3"}) == "ZenML" and company({"title": "Mphasis, technical"}) == "Mphasis"
    assert round_of("Mphasis, technical", "Mphasis") == "Technical" and round_of("ZenML round 3", "ZenML") == "Round 3"
    build()
