"""Build INTERVIEWS.html, the hub for every interview loop.

    python interviews/hub.py      -> INTERVIEWS.html at the repo root

One card per loop module (interviews/*.py with a LOOP dict), newest first, in a grid: the
company as a wordmark alone on its line, sized in the browser to fill the card's width; the
round and one line of context below it, small; total hours from its tracker sessions with a
thin progress line; the job post or company site from its SOURCES at the bottom left and the
status and date as a small tag at the bottom right. The whole card is a link to the loop page,
opening in a new tab (a stretched link; the inner links sit above it and stay clickable). A
card is one neutral surface with the name in its brand colour: LOOP["brand"] (and
LOOP["brand_dark"] on the dark surface), one home, in the loop's module. On hover or focus the
colours flip: the card fills with the brand colour and its text takes the surface colour. A loop
with an empty when_iso is upcoming with its date to be set, and sorts first. Progress
(sessions closed, hours banked) is read in the browser from the tracker's own store,
selfstudy.m1.planner; the hub never writes to it. A new loop appears when its module is
added and this is rerun.
"""
import datetime, hashlib, importlib, io, json, os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)
from build import sessions_from_tracker   # the one parser of the tracker's sessions


def minutes(s):
    """'1h 15m' -> 75, '45m' -> 45, '1h' -> 60."""
    h = re.search(r"(\d+)\s*h", s or "")
    m = re.search(r"(\d+)\s*m", s or "")
    return (int(h.group(1)) * 60 if h else 0) + (int(m.group(1)) if m else 0)


def company(L):
    """LOOP['company'] if set, else the title's first word: 'ZenML round 3' -> 'ZenML'."""
    return L.get("company") or re.split(r"[\s,]+", L["title"].strip())[0]


def round_of(title, co):
    """The title without its company, capitalised: 'Mphasis, technical' -> 'Technical'."""
    r = title.strip()[len(co):].lstrip(" ,") if title.strip().startswith(co) else title.strip()
    return r[:1].upper() + r[1:]


def links(sources):
    """The job post and the company site, only from URLs the module already has."""
    out = []
    for label, pat in (("Job post", r"\bjob\b"), ("Company", r"\bcompany\b|^\S+\.(ai|com|io)$")):
        hit = next((s for s in sources if s.get("url") and re.search(pat, s["label"], re.I)), None)
        if hit and all(hit["url"] != o["url"] for o in out):
            out.append({"label": label, "url": hit["url"], "title": hit["label"]})
    return out


def loops():
    out = []
    for f in sorted(os.listdir(HERE)):
        if not f.endswith(".py") or f in ("build.py", "hub.py") or f.startswith("_"):
            continue
        m = importlib.import_module(f[:-3])
        L = getattr(m, "LOOP", None)
        if not L:
            continue
        d = datetime.datetime.fromisoformat(L["when_iso"]) if L["when_iso"] else None
        for k in ("brand", "brand_dark"):
            assert re.fullmatch(r"#[0-9A-Fa-f]{6}", L.get(k) or "#000000"), "%s: LOOP[%r] is not a #rrggbb colour" % (f, k)
        sessions = [{"id": s["id"], "min": minutes(s.get("len"))} for s in sessions_from_tracker(getattr(m, "SESSION_IDS", []))]
        co = company(L)
        out.append({
            "title": L["title"], "subtitle": L.get("subtitle", ""), "when": L["when"], "when_iso": L["when_iso"],
            "date": "%s %d %s %d" % (d.strftime("%a"), d.day, d.strftime("%b"), d.year) if d else "",
            "company": co, "round": round_of(L["title"], co),
            "brand": L.get("brand", ""), "brandDark": L.get("brand_dark", ""),
            "href": "interviews/" + f[:-3].replace("_", "-") + ".html",
            "sessions": sessions, "total": sum(s["min"] for s in sessions),
            "links": links(getattr(m, "SOURCES", [])),
        })
    # Newest first; a loop with no date yet is still to come, so it goes on top.
    out.sort(key=lambda x: datetime.datetime.fromisoformat(x["when_iso"]).timestamp() if x["when_iso"] else float("inf"), reverse=True)
    return out


PAGE = r"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Interview loops</title>
<link rel="icon" type="image/svg+xml" href="brand/accelerate.svg">
<link rel="stylesheet" href="fonts/fonts.css">
<link rel="stylesheet" href="site/tokens.css">
<link rel="stylesheet" href="site/nav.css">
<script src="private/site.js"></script>
<script src="site/nav.js" defer></script>
<!-- Generated by interviews/hub.py from the loop modules and the tracker's sessions.
     Edit those and rebuild; do not edit this file by hand. -->
<style>
* { box-sizing: border-box; }
body { margin: 0; background: var(--bg); color: var(--ink); font: var(--fs-md)/var(--lh-body) var(--font); -webkit-font-smoothing: antialiased; }
a { color: var(--accent); text-decoration: none; }
a:hover { text-decoration: underline; text-underline-offset: 3px; }
:focus-visible { outline: 2px solid var(--accent); outline-offset: 2px; border-radius: var(--radius-sm); }
code { font-family: var(--mono); font-size: var(--fs-code); background: var(--sunken); padding: 1px var(--s1); border-radius: var(--radius-sm); }
.wrap { max-width: 1180px; margin: 0 auto; padding: 0 var(--s5); }
.top { display: flex; flex-wrap: wrap; align-items: center; gap: var(--s2) var(--s5); padding: var(--s4) 0 var(--s3); border-bottom: var(--hair); }
h1 { font-size: var(--fs-2xl); font-weight: var(--w-strong); line-height: var(--lh-tight); margin: 0; }
.lead { color: var(--soft); margin: var(--s4) 0 var(--s5); max-width: var(--measure); }
.lead b { color: var(--ink); font-weight: var(--w-strong); }

/* The loops: a grid of cards, newest first. A card is one neutral surface with the company
   name in its brand colour (--b, and --bd on the dark surface, given per card from the
   loop's module). The card reads its colours from four local variables; hover and focus
   swap them, so the card fills with the brand colour and every line of text takes the
   surface colour. Sizes: 12 meta, 13 round, context and links, plus the wordmark. */
.grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(260px, 1fr)); gap: var(--s4); margin: 0 0 var(--s7); padding: 0; list-style: none; }
.loop {
  --brand: var(--b, var(--ink));
  --c-bg: var(--surface); --c-name: var(--brand); --c-ink: var(--ink); --c-soft: var(--soft); --c-muted: var(--muted); --c-rule: var(--rule);
  position: relative; display: flex; flex-direction: column; min-width: 0; padding: var(--s4);
  background: var(--c-bg); color: var(--c-ink); border: 1px solid var(--c-rule); border-radius: var(--radius);
}
@media (prefers-color-scheme: dark) { :root:not([data-theme="light"]) .loop { --brand: var(--bd, var(--b, var(--ink))); } }
:root[data-theme="dark"] .loop { --brand: var(--bd, var(--b, var(--ink))); }
.loop:hover, .loop:focus-within {
  --c-bg: var(--brand); --c-name: var(--surface); --c-ink: var(--surface); --c-soft: var(--surface); --c-muted: var(--surface); --c-rule: var(--brand);
}
/* Colour only, quick and ease-out; no movement. 150 ms is the ceiling in DESIGN.md rule 10. */
.loop, .loop * { transition: background-color 150ms ease-out, color 150ms ease-out, border-color 150ms ease-out; }
@media (prefers-reduced-motion: reduce) { .loop, .loop * { transition: none; } }

/* The wordmark. DESIGN.md caps text at 24px; this is the one deliberate exception: a display
   wordmark, not text. fit() in the script sets its font size per card so the name fills the
   card's width; the rows then share one baseline. Same family, bold, tight tracking. */
.wm { display: flex; align-items: flex-end; margin: 0; min-height: 1em; font-size: var(--fs-lg); }
.co { display: inline-block; white-space: nowrap; color: var(--c-name); font-weight: 700; letter-spacing: -.035em; line-height: 1; padding-bottom: .04em; }
.co:hover { text-decoration: none; }
/* The stretched link: the whole card opens the loop page. */
.co::after { content: ""; position: absolute; inset: 0; z-index: 1; border-radius: var(--radius); }
.co:focus-visible { outline: none; }
.co:focus-visible::after { outline: 2px solid var(--accent); outline-offset: 3px; }
.rd { font-size: var(--fs-sm); font-weight: var(--w-strong); color: var(--c-ink); margin: var(--s3) 0 0; }
.ctx { font-size: var(--fs-sm); color: var(--c-soft); margin: 0; overflow: hidden; white-space: nowrap; text-overflow: ellipsis; }
.ft { margin-top: auto; padding-top: var(--s5); }   /* progress and the bottom row sit on one line across a row */
.hrs { font-size: var(--fs-xs); color: var(--c-muted); margin: 0; }
.hrs b { color: var(--c-ink); font-weight: var(--w-strong); }
.bar { height: 2px; background: var(--c-rule); margin: var(--s2) 0 0; overflow: hidden; }
.loop:hover .bar, .loop:focus-within .bar { background: color-mix(in srgb, var(--surface) 30%, transparent); }
.bar i { display: block; height: 100%; background: var(--c-soft); }
.end { display: flex; flex-wrap: wrap; align-items: center; justify-content: space-between; gap: var(--s2) var(--s3); padding-top: var(--s3); }
.go { display: flex; flex-wrap: wrap; gap: var(--s1) var(--s4); font-size: var(--fs-sm); }
.go a { position: relative; z-index: 2; color: var(--c-soft); text-decoration: underline; text-decoration-color: transparent; text-underline-offset: 3px; }
.go a:hover { text-decoration-color: currentColor; }
.loop:hover .go a, .loop:focus-within .go a { text-decoration-color: currentColor; }
.go a:focus-visible { outline-color: currentColor; }
.tag { margin-left: auto; display: inline-flex; gap: var(--s2); align-items: center; font-size: var(--fs-xs); line-height: 1; color: var(--c-muted);
  border: 1px solid var(--c-rule); border-radius: var(--radius-sm); padding: var(--s1) var(--s2); white-space: nowrap; }
.tag b { color: var(--c-ink); font-weight: var(--w-strong); }
.loop:hover .tag, .loop:focus-within .tag { border-color: currentColor; }
.empty { background: var(--sunken); border-radius: var(--radius-lg); padding: var(--s5); max-width: var(--measure); }
.empty b { display: block; font-weight: var(--w-strong); }
.empty p { color: var(--soft); margin: var(--s1) 0 0; }
@media (max-width: 720px) {
  .wrap { padding: 0 var(--s4); }
  .top { padding: var(--s3) 0; }
}
</style>
</head>
<body>
<div class="wrap">
  <header class="top">
    <h1>Interview loops</h1>
    <nav class="sn-top" data-site-nav data-here="interviews"></nav>
  </header>
  <main>
    <p class="lead" id="lead"></p>
    <ul class="grid" id="loops"></ul>
  </main>
</div>
<script type="application/json" id="hub-data">{{DATA}}</script>
<script>
"use strict";
(function () {
  var LOOPS = JSON.parse(document.getElementById("hub-data").textContent);
  var TRACKER = "selfstudy.m1.planner";   /* the tracker's own store: read here, never written */

  function esc(s) { return String(s == null ? "" : s).replace(/[&<>"]/g, function (c) { return { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c]; }); }
  function done() {
    try { var t = JSON.parse(window.localStorage.getItem(TRACKER) || "{}"); return (t && t.done) || {}; }
    catch (err) { console.error("Could not read " + TRACKER, err); return {}; }
  }
  function hm(min) {
    if (!min) { return "0h"; }
    var h = Math.floor(min / 60), m = min % 60;
    return (h ? h + "h" : "") + (h && m ? " " : "") + (m || !h ? m + "m" : "");
  }

  function progress(L, d) {
    var n = L.sessions.length;
    if (!n) { return '<p class="hrs">No tracker sessions.</p>'; }
    var closed = L.sessions.filter(function (s) { return d[s.id]; });
    var banked = closed.reduce(function (a, s) { return a + s.min; }, 0);
    var line = closed.length === n
      ? "<b>All " + n + " sessions closed</b>, " + hm(banked)
      : "<b>" + closed.length + "</b> of " + n + " sessions, <b>" + hm(banked) + "</b> of " + hm(L.total);
    return '<p class="hrs">' + line + "</p>" +
      '<div class="bar" role="progressbar" aria-label="Hours banked" aria-valuemin="0" aria-valuemax="' + L.total + '" aria-valuenow="' + banked + '"><i style="width:' +
      (L.total ? Math.round(100 * banked / L.total) : 0) + '%"></i></div>';
  }

  function draw() {
    var d = done(), now = Date.now(), next = null;
    var grid = document.getElementById("loops"), lead = document.getElementById("lead");
    if (!LOOPS.length) {
      grid.outerHTML = '<div class="empty"><b>No interview loops yet.</b><p>Add one: write <code>interviews/&lt;module&gt;.py</code> with a <code>LOOP</code> dict, ' +
        "then run <code>python interviews/hub.py</code>. It appears here as a tile.</p></div>";
      lead.hidden = true;
      return;
    }
    grid.innerHTML = LOOPS.map(function (L) {
      var past = !!L.when_iso && new Date(L.when_iso).getTime() <= now;   /* no date yet: still to come */
      if (!past) { next = L; }
      var ctx = L.subtitle || L.company;
      var brand = (L.brand ? "--b:" + L.brand + ";" : "") + (L.brandDark ? "--bd:" + L.brandDark + ";" : "");
      return '<li class="loop"' + (brand ? ' style="' + esc(brand) + '"' : "") + ">" +
        '<h2 class="wm"><a class="co" href="' + esc(L.href) + '" target="_blank" rel="noopener" title="' + esc(L.when) + '" aria-label="' +
        esc(L.company + (L.round ? ", " + L.round : "") + ": loop page, opens in a new tab") + '">' + esc(L.company) + "</a></h2>" +
        (L.round ? '<p class="rd">' + esc(L.round) + "</p>" : "") +
        '<p class="ctx">' + esc(ctx) + "</p>" +
        '<div class="ft">' + progress(L, d) +
        '<div class="end"><div class="go">' +
        L.links.map(function (k) { return '<a href="' + esc(k.url) + '" target="_blank" rel="noopener" title="' + esc(k.title) + '">' + esc(k.label) + "</a>"; }).join("") +
        '</div><p class="tag">' +
        (past ? "Happened<span>" + esc(L.date) + "</span>" : "<b>Upcoming</b><span>" + (L.date ? esc(L.date) : "date to be set") + "</span>") +
        "</p></div></div></li>";
    }).join("");
    fit();
    var n = LOOPS.length + (LOOPS.length === 1 ? " loop" : " loops") + ", newest first. ";
    lead.innerHTML = next
      ? esc(n) + "Next: <b>" + esc(next.title) + "</b>. " + esc(next.when.replace(/\.$/, "")) + "."
      : esc(n) + "None is scheduled. A new loop is a new <code>interviews/&lt;module&gt;.py</code>.";
  }

  /* Every wordmark is one height: the size at which "Mphasis" fills a card's width. Each name
     then fills the width by its letter-spacing, wider for short names, tighter for long ones;
     a very long name that would need more than -0.12em is set smaller instead. The trailing
     space after the last letter is cancelled so the name ends at the card's edge. Then every
     wordmark in a grid row gets the tallest one's height, so the rounds below line up. */
  function fit() {
    var marks = [].slice.call(document.querySelectorAll(".wm"));
    if (!marks.length) { return; }
    marks.forEach(function (h) {
      h.style.minHeight = "";
      var s = h.firstChild.style;
      s.fontSize = "100px"; s.letterSpacing = ""; s.marginRight = "";
    });
    var probe = marks[0].firstChild.cloneNode(false);
    probe.textContent = "Mphasis";
    probe.style.cssText = "position:absolute;visibility:hidden;font-size:100px";
    marks[0].appendChild(probe);
    var avail = marks[0].clientWidth - 1;
    var size = Math.max(17, Math.floor(1000 * avail / probe.getBoundingClientRect().width) / 10);
    probe.remove();
    marks.forEach(function (h) {
      var co = h.firstChild, n = co.textContent.length;
      co.style.fontSize = size + "px";
      co.style.letterSpacing = "0px";
      var room = h.clientWidth - 1 - co.getBoundingClientRect().width;
      var ls = n > 1 ? room / (n - 1) : 0;
      if (ls < -0.12 * size) {   /* too long to tighten: smaller, at the base tracking */
        co.style.letterSpacing = "";
        co.style.fontSize = Math.max(17, Math.floor(1000 * (h.clientWidth - 1) / co.getBoundingClientRect().width * size / 100) / 10) + "px";
        return;
      }
      ls = Math.min(ls, 0.06 * size);   /* a short name is not stretched: it ends early instead */
      co.style.letterSpacing = ls.toFixed(2) + "px";
      co.style.marginRight = (-ls).toFixed(2) + "px";
    });
    var rows = {};
    marks.forEach(function (h) { var t = h.parentNode.offsetTop; rows[t] = Math.max(rows[t] || 0, h.getBoundingClientRect().height); });
    marks.forEach(function (h) { h.style.minHeight = rows[h.parentNode.offsetTop] + "px"; });
  }

  draw();
  window.addEventListener("storage", function (e) { if (e.key === TRACKER) { draw(); } });
  var grid = document.getElementById("loops"), width = 0;
  if (grid && window.ResizeObserver) {
    new ResizeObserver(function () { if (grid.clientWidth !== width) { width = grid.clientWidth; fit(); } }).observe(grid);
  }
  if (document.fonts) { document.fonts.ready.then(fit); }
}());
</script>
</body>
</html>
"""


def build():
    data = loops()
    page = PAGE
    for f in ("site/tokens.css", "site/nav.js", "site/nav.css"):
        v = hashlib.sha1(io.open(os.path.join(ROOT, f), "rb").read()).hexdigest()[:8]
        page = page.replace('%s"' % f, '%s?v=%s"' % (f, v))
    page = page.replace("{{DATA}}", json.dumps(data, ensure_ascii=False).replace("</", "<\\/"))
    out = os.path.join(ROOT, "INTERVIEWS.html")
    io.open(out, "w", encoding="utf-8", newline="\n").write(page)
    print("wrote %s: %d bytes, %d loops, %d sessions" % (out, len(page), len(data), sum(len(x["sessions"]) for x in data)))


if __name__ == "__main__":
    assert minutes("1h 15m") == 75 and minutes("45m") == 45 and minutes("1h") == 60 and minutes(None) == 0
    assert company({"title": "ZenML round 3"}) == "ZenML" and company({"title": "Mphasis, technical"}) == "Mphasis"
    assert round_of("Mphasis, technical", "Mphasis") == "Technical" and round_of("ZenML round 3", "ZenML") == "Round 3"
    build()
