"""Build INTERVIEWS.html, the hub for every interview loop.

    python interviews/hub.py      -> INTERVIEWS.html at the repo root

One card per loop module (interviews/*.py with a LOOP dict), newest first: title, date,
who and format, total hours from its tracker sessions, and links to the loop page and to
the job post or company site in its SOURCES. Progress (sessions closed, hours banked) is
read in the browser from the tracker's own store, selfstudy.m1.planner; the hub never
writes to it. A new loop appears when its module is added and this is rerun.
"""
import datetime, hashlib, importlib, io, json, os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)
from build import sessions_from_tracker   # the one parser of the tracker's sessions


def minutes(s):
    """'1h 15m' -> 75, '45m' -> 45, '1h' -> 60."""
    h = re.search(r"(\d+)\s*h", s or "")
    m = re.search(r"(\d+)\s*m", s or "")
    return (int(h.group(1)) * 60 if h else 0) + (int(m.group(1)) if m else 0)


def links(sources):
    """The job post and the company site, only from URLs the module already has."""
    out = []
    for label, pat in (("Job post", r"\bjob\b"), ("Company site", r"\bcompany\b|^\S+\.(ai|com|io)$")):
        hit = next((s for s in sources if s.get("url") and re.search(pat, s["label"], re.I)), None)
        if hit and all(hit["url"] != o["url"] for o in out):
            out.append({"label": label, "url": hit["url"], "title": hit["label"]})
    return out


def loops():
    out = []
    for f in sorted(os.listdir(HERE)):
        if not f.endswith(".py") or f in ("build.py", "hub.py") or f.startswith("_"):
            continue
        m = importlib.import_module(f[:-3])
        L = getattr(m, "LOOP", None)
        if not L:
            continue
        d = datetime.datetime.fromisoformat(L["when_iso"])
        sessions = [{"id": s["id"], "min": minutes(s.get("len"))} for s in sessions_from_tracker(getattr(m, "SESSION_IDS", []))]
        out.append({
            "title": L["title"], "subtitle": L.get("subtitle", ""), "when": L["when"], "when_iso": L["when_iso"],
            "date": "%s %d %s" % (d.strftime("%A"), d.day, d.strftime("%B %Y")),
            "who": L["who"], "format": re.split(r"(?<=[.!?])\s+", L["format"])[0],
            "href": "interviews/" + f[:-3].replace("_", "-") + ".html",
            "sessions": sessions, "total": sum(s["min"] for s in sessions),
            "links": links(getattr(m, "SOURCES", [])),
        })
    out.sort(key=lambda x: datetime.datetime.fromisoformat(x["when_iso"]), reverse=True)
    return out


PAGE = r"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Interview loops</title>
<link rel="icon" type="image/svg+xml" href="brand/accelerate.svg">
<link rel="stylesheet" href="fonts/fonts.css">
<link rel="stylesheet" href="site/nav.css">
<script src="site/nav.js" defer></script>
<!-- Generated by interviews/hub.py from the loop modules and the tracker's sessions.
     Edit those and rebuild; do not edit this file by hand. -->
<style>
:root { --bg: #FBF8F1; --ink: #1D1B17; --soft: #45413A; --muted: #736D62; --rule: #E7E0D2; --tint: #F2ECE0; --accent: #0A5BD3; --ok: #1A7F4B;
  --body: "Atkinson Hyperlegible", "Segoe UI", system-ui, sans-serif; color-scheme: light; }
@media (prefers-color-scheme: dark) { :root:not([data-theme="light"]) {
  --bg: #1C1B22; --ink: #EDEDF2; --soft: #C9C8D3; --muted: #9C9BA8; --rule: #33323C; --tint: #25242D; --accent: #7AB2FF; --ok: #5BC98E; color-scheme: dark; } }
:root[data-theme="dark"] { --bg: #1C1B22; --ink: #EDEDF2; --soft: #C9C8D3; --muted: #9C9BA8; --rule: #33323C; --tint: #25242D; --accent: #7AB2FF; --ok: #5BC98E; color-scheme: dark; }
* { box-sizing: border-box; }
body { margin: 0; background: var(--bg); color: var(--ink); font: 17px/1.6 var(--body); -webkit-font-smoothing: antialiased; }
a { color: var(--accent); text-decoration: none; }
a:hover { text-decoration: underline; text-underline-offset: 3px; }
:focus-visible { outline: 2px solid var(--accent); outline-offset: 2px; border-radius: 3px; }
code { font-family: "JetBrains Mono", Consolas, monospace; font-size: .86em; background: var(--tint); padding: 1px 5px; border-radius: 4px; }
.top { position: sticky; top: 0; z-index: 5; background: var(--bg); border-bottom: 1px solid var(--rule); }
.top-in { max-width: 1180px; margin: 0 auto; padding: 8px 24px; display: flex; gap: 10px 18px; align-items: center; flex-wrap: wrap; min-height: 56px; }
.top b { font-size: 17px; white-space: nowrap; }
main { max-width: 780px; margin: 0 auto; padding: 36px 24px 120px; }
h1 { font-size: 32px; line-height: 1.2; margin: 0 0 6px; }
.lead { color: var(--soft); font-size: 18px; margin: 0 0 28px; }
.loop { border: 1px solid var(--rule); border-radius: 10px; padding: 18px 22px 16px; margin: 0 0 16px; }
.loop .when { color: var(--muted); font-size: 15px; }
.loop h2 { font-size: 23px; line-height: 1.3; margin: 2px 0 6px; }
.loop h2 a { color: var(--ink); }
.loop .meta { color: var(--soft); margin: 0 0 12px; display: -webkit-box; -webkit-line-clamp: 2; -webkit-box-orient: vertical; overflow: hidden; }
.loop .hrs { color: var(--muted); font-size: 15px; margin: 0; }
.loop .hrs b { color: var(--ink); font-weight: 700; }
.loop .bar { height: 6px; border-radius: 3px; background: var(--tint); margin: 8px 0 0; overflow: hidden; }
.loop .bar i { display: block; height: 100%; background: var(--muted); }
.loop.done .bar i { background: var(--ok); }
.loop .ok { color: var(--ok); font-weight: 700; }
.loop .ok svg { width: 16px; height: 16px; vertical-align: -2px; margin-right: 4px; fill: none; stroke: currentColor; stroke-width: 2.4; stroke-linecap: round; stroke-linejoin: round; }
.loop .go { display: flex; flex-wrap: wrap; gap: 6px 20px; margin: 14px 0 0; font-size: 15.5px; }
.loop .go a:first-child { font-weight: 700; }
@media (max-height: 560px) { .top { position: static; } }
@media (max-width: 720px) {
  .top-in { padding: 6px 12px; min-height: 0; }
  main { padding: 22px 16px 80px; }
  h1 { font-size: 26px; }
  .loop { padding: 14px 16px 12px; }
  .loop h2 { font-size: 21px; }
}
</style>
</head>
<body>
<div class="top"><div class="top-in">
  <b>Interview loops</b>
  <nav class="sn-top" data-site-nav data-here="interviews"></nav>
</div></div>
<main>
  <h1>Interview loops</h1>
  <p class="lead" id="lead"></p>
  <div id="loops"></div>
</main>
<script type="application/json" id="hub-data">{{DATA}}</script>
<script>
"use strict";
(function () {
  var LOOPS = JSON.parse(document.getElementById("hub-data").textContent);
  var TRACKER = "selfstudy.m1.planner";   /* the tracker's own store: read here, never written */
  var CHECK = '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M20 6 9 17l-5-5"/></svg>';

  function esc(s) { return String(s == null ? "" : s).replace(/[&<>"]/g, function (c) { return { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c]; }); }
  function done() {
    try { var t = JSON.parse(window.localStorage.getItem(TRACKER) || "{}"); return (t && t.done) || {}; }
    catch (err) { console.error("Could not read " + TRACKER, err); return {}; }
  }
  function hm(min) {
    if (!min) { return "0h"; }
    var h = Math.floor(min / 60), m = min % 60;
    return (h ? h + "h" : "") + (h && m ? " " : "") + (m || !h ? m + "m" : "");
  }

  function progress(L, d) {
    var n = L.sessions.length;
    if (!n) { return '<p class="hrs">Hours: none. No tracker sessions; the prep is on the loop page.</p>'; }
    var closed = L.sessions.filter(function (s) { return d[s.id]; });
    var banked = closed.reduce(function (a, s) { return a + s.min; }, 0);
    var all = closed.length === n;
    var line = all
      ? '<span class="ok">' + CHECK + "All " + n + " sessions closed</span>, " + hm(banked) + " banked"
      : "<b>" + closed.length + " of " + n + "</b> sessions closed, <b>" + hm(banked) + "</b> of " + hm(L.total) + " banked";
    return '<p class="hrs">' + n + " sessions, " + hm(L.total) + " in all. " + line + "</p>" +
      '<div class="bar" role="progressbar" aria-label="Hours banked" aria-valuemin="0" aria-valuemax="' + L.total + '" aria-valuenow="' + banked + '"><i style="width:' +
      (L.total ? Math.round(100 * banked / L.total) : 0) + '%"></i></div>';
  }

  function draw() {
    var d = done(), now = Date.now(), next = null;
    document.getElementById("loops").innerHTML = LOOPS.map(function (L) {
      var past = new Date(L.when_iso).getTime() <= now;
      if (!past) { next = L; }
      var all = L.sessions.length && L.sessions.every(function (s) { return d[s.id]; });
      return '<article class="loop' + (all ? " done" : "") + '">' +
        '<div class="when">' + (past ? "Happened, " + esc(L.date) : "Upcoming, " + esc(L.when)) + "</div>" +
        '<h2><a href="' + esc(L.href) + '">' + esc(L.title) + "</a></h2>" +
        '<p class="meta">' + esc(L.subtitle) + ". " + esc(L.who) + " " + esc(L.format) + "</p>" +
        progress(L, d) +
        '<div class="go"><a href="' + esc(L.href) + '">Open the loop page</a>' +
        L.links.map(function (k) { return '<a href="' + esc(k.url) + '" target="_blank" rel="noopener" title="' + esc(k.title) + '">' + esc(k.label) + "</a>"; }).join("") +
        "</div></article>";
    }).join("");
    document.getElementById("lead").innerHTML = next
      ? "Next: <b>" + esc(next.title) + "</b>, " + esc(next.when) + "."
      : "No loop scheduled. Add one: a new <code>interviews/&lt;module&gt;.py</code>.";
  }

  draw();
  window.addEventListener("storage", function (e) { if (e.key === TRACKER) { draw(); } });
}());
</script>
</body>
</html>
"""


def build():
    data = loops()
    page = PAGE
    for f in ("site/nav.js", "site/nav.css"):
        v = hashlib.sha1(io.open(os.path.join(ROOT, f), "rb").read()).hexdigest()[:8]
        page = page.replace('%s"' % f, '%s?v=%s"' % (f, v))
    page = page.replace("{{DATA}}", json.dumps(data, ensure_ascii=False).replace("</", "<\\/"))
    out = os.path.join(ROOT, "INTERVIEWS.html")
    io.open(out, "w", encoding="utf-8", newline="\n").write(page)
    print("wrote %s: %d bytes, %d loops, %d sessions" % (out, len(page), len(data), sum(len(x["sessions"]) for x in data)))


if __name__ == "__main__":
    assert minutes("1h 15m") == 75 and minutes("45m") == 45 and minutes("1h") == 60 and minutes(None) == 0
    build()
