"""ZenML round 3: the content of interviews/zenml-round3.html.

Sources: the round-two critique (the bench story is Pranav's own account, used as
he tells it), E:/kitaru/INTERVIEW-PREP.md, E:/kitaru/KITARU.md and the teardown's
diagrams. The practice sessions themselves are read from the tracker (SESSION_IDS),
so a tick in either place shows in both.
"""

LOOP = {
    "id": "zenml-r3",
    "title": "ZenML round 3",
    "subtitle": "Kitaru, product engineer",
    "when_iso": "2026-09-28T09:00:00-04:00",
    "when": "Monday 28 September, 9 AM Eastern",
    "who": "Hamza Tahir, co-founder of ZenML, and Alex Strick van Linschoten, who ships the Claude Code skills behind Kitaru's guided tour.",
    "format": "Ninety minutes, technical, in depth. Expect them to go down, not sideways: mechanism, storage, failure, and whether each claim survives one 'how exactly?' and one 'how big?'.",
    "bar": "Every claim survives one 'how exactly?' and one 'how big?'. When pushed, go down, not sideways. Volunteer the limit before they find it. Reach for a number unprompted.",
    # Diagrams tab: keys into figures/figures.js (drawn from the Kitaru teardown).
    "figures": ["kitaruPlanes", "kitaruReplay", "kitaruModel", "kitaruPolicy", "kitaruKey", "kitaruOrder",
                "kitaruTurns", "kitaruLive", "kitaruFreeze", "kitaruScale", "kitaruPosition"],
    "plan_kicker": "Friday to Sunday",
    "mech_title": "Kitaru, mechanism by mechanism",
    "design_link": {"text": "The worked design, six steps and five deep dives:", "label": "Kitaru in your system design guide",
                    "href": "../SYSTEM%20DESIGN.html#/designs/kitaru"},
}

# Tracker sessions for this loop, in the order to do them, with the day each belongs to.
SESSION_IDS = [
    ("wc7", "Fri"), ("wc13", "Fri"), ("wc14", "Fri"), ("wc15", "Fri"),
    ("wc16", "Sat"), ("wc8", "Sat"), ("wc9", "Sat"),
    ("wc17", "Sun"), ("wc10", "Sun, if time"), ("wc11", "Sun, if time"), ("wc12", "Sun"),
]

# Prep hub. How to show up comes first; each bank opens in the one-screen panel.
PREP_LEAD = ("Start with how to show up. Then open a bank: each question shows what they are testing, the nuance, "
             "figures and reading on the light side, and what to say on the dark sheet. Mark each one revised as you go.")

SHOW_UP = [
    ("Headline first, then stop.", "About 45 seconds, then offer the depth: 'I can go into the bench or the memory work.' The first answer sets the pace for ninety minutes; in the mock it ran over three."),
    ("Answer the person asking.", "Hamza, the co-founder, wants your story, your judgement, why this move and what you would cut. Alex, their Founding DevEx Engineer, wants the mechanism, the API shape, and what the user types and sees."),
    ("Say the limit before they find it.", "In the mock, defending the empty result cost more than the gap itself. 'That's a gap, and here is what I'd do' is the senior answer. Their own value is Be honest: 'provide candid feedback and own your actions'."),
    ("When lost, go to what the user sees.", "The screen, the click, what changes next time. It rescues any design question; it would have rescued the miss question."),
    ("Buy time honestly.", "'Give me a second' is fine. 'Essentially', 'so to say', 'in a sense' are not."),
    ("Numbers, unprompted.", "5,000-plus users, about 25 real instances per task, 2.5 to 2.2 tool calls per task, about three in four genuine flags, a little over a hundred cases."),
    ("Show their words as habits, never quote them.", "Their post asks for 'end-to-end in days, not weeks', 'a Slack conversation into a merged PR before lunch', 'product taste for developer tools', 'low ego, high standards'. Tell a story that shows each; do not recite the post."),
    ("The public half is part of the job.", "Lennart and Michael both raised it. Have your YouTube channel, LinkedIn, the INFORMS talk and MockFlow-AI's launch video ready, and your first post about Kitaru in one sentence."),
    ("Care that Kitaru wins.", "They are founders. Admire one thing specifically (the selector design), then critique one thing as a question. Energy for the product reads as fit."),
    ("Leave twenty minutes.", "At minute 70 of 90, turn to your questions. One at a time, then wait."),
]

STORY_BLURB = "Intro, why this seat, the bench in two and five minutes, the refunds case, the miss, the critique, the close."

# Every outside link on the Prep tab, checked 2026-09-27.
SOURCES = [
    {"label": "Product Engineer, ZenML/Kitaru: the job post (closed to applications)", "url": "https://careers.crane.vc/companies/zenml-2/jobs/74821580-product-engineer-zenml-kitaru-f-m-d-full-time",
     "why": "What they asked for, in their words: ship end to end in days, build for Python developers, close the loop on UX, AI-first and craft-first."},
    {"label": "ZenML: company and values", "url": "https://www.zenml.io/company",
     "why": "Challenge everything, Empathize, Be efficient, Enable others, Be honest. Alex is listed as Founding DevEx Engineer."},
    {"label": "ZenML careers", "url": "https://www.zenml.io/careers", "why": "No hierarchies, full ownership, open source as the way to build software."},
    {"label": "Introducing Kitaru (1 April 2026)", "url": "https://www.zenml.io/blog/kitaru-launch",
     "why": "The launch as a durable execution layer for Python agents: crash recovery, human-in-the-loop, replay from any checkpoint."},
    {"label": "Alex Strick van Linschoten's blog", "url": "https://alexstrick.com/", "why": "He writes in public about MLOps and engineering; read two recent technical posts."},
    {"label": "ZenML's LLMOps Database", "url": "https://www.zenml.io/llmops-database", "why": "About 2,100 production case studies: how ZenML does public, useful content."},
]

# What to say, in the words to say it.
SCRIPTS = [
    {"id": "intro", "title": "Intro", "length": "about 40 seconds",
     "when": "The first question, whatever form it takes.",
     "say": [
         "I'm a founding engineer at alfred_, an AI executive assistant that runs over your work apps, email and calendar, at 5,000-plus active users. My work there has been taking an agent product and making it reliable in production: the evaluation infrastructure, the memory architecture, and the orchestration underneath it.",
         "The piece most relevant to this conversation is the eval side. I built a bench that takes real production failures and replays them against new versions of the agent, with the tools answered from a snapshot instead of hitting live systems. So I've built a rough version of what Kitaru does, and I know where mine broke.",
         "Before alfred_ I was at WheelPrice, a Techstars-backed marketplace with two engineers, where I worked across product, backend, ML features and a computer vision project. I like small teams and vertical ownership, and I want to keep doing that in AI infrastructure."],
     "land": "What alfred_ is with one number, what you own, the piece closest to Kitaru. Then stop.",
     "never": ["Never mention alfred_'s funding or a crunch.", "No filler openers: 'I have some experience', 'so to say', 'essentially'."]},
    {"id": "seat", "title": "Why this seat", "length": "about 45 seconds",
     "when": "Why are you looking, why Kitaru, why product engineer.",
     "say": [
         "I'm not looking to urgently leave alfred_. What I want is a team where the problem is clear and the AI infrastructure is the centre of the product instead of one of many hats. Kitaru being early is the appeal, since I've spent the last year on exactly this problem from the inside.",
         "On the product-engineer half: the hard part here isn't only the server. The product is a method as much as a system, and the gap between 'it works' and 'someone adopts it' is mostly the on-ramp. I want to be close enough to users to know which of the two is failing.",
         "On the public half: I already do it for my own work. I have a YouTube channel, I'm active on LinkedIn, and I post when I build: MockFlow-AI shipped with a launch video, and I presented MetaRAG at INFORMS Analytics+ to 700-plus practitioners. I haven't done it for an employer's product yet, and I'd like to. The first thing I'd post here is a walkthrough of importing real traces, finding a failure, and proving the fix with a replay."],
     "land": "Pull, not push: the problem is clear here, the product is the infrastructure, and I've built its rough version.",
     "notes": ["Never negative about alfred_. 'Not urgently leaving' keeps it a move towards something.",
               "The post says this role is not for 'specialists seeking deep focus in one stack area'. Say you want the breadth.",
               "Lennart and Michael both asked about the public side; expect Hamza to test it too. See the role bank."]},
    {"id": "bench2", "land": "The real agent against a frozen snapshot of the user's world; only the provider call swapped; scored on tool calls per completed task.", "title": "The bench, in two minutes", "length": "about 2 minutes",
     "when": "Tell me about the eval harness. Headline first, every time.",
     "say": [
         "When I joined alfred_, we had no reliable way to say whether a new version of the agent was better than the old one. People tried it and had opinions. So I built the loop that turns production failures into regression tests.",
         "It starts with a scanner over real conversations. Cheap deterministic signals flag anything that looks like one of twelve failure types, and an LLM judge, trained on a week of labels I did by hand, decides which flags are real. Roughly three out of four are genuine bugs. Real ones get fixed and promoted into a bench of a little over a hundred cases.",
         "Replay is the interesting part. The real agent runs in a harness mode. The tools execute normally, so ranking, filtering and formatting are the production code. Only the call out to Gmail, the calendar or an MCP server gets routed to a SQLite snapshot. And the snapshot isn't one recorded path: for a query type we pulled about twenty-five real instances and covered every tool the agent used across all of them, plus deliberate ambiguity, like three people named Michael.",
         "So the agent can take a path it never took in production and still get truthful answers. We score on tool calls per completed task and on assertions against the snapshot, run it nightly, and it's what we used to sign off a full rewrite of the agent's multi-turn orchestration."]},
    {"id": "bench5", "land": "Nine beats, each with its number: problem, finding, judging, promotion, snapshot, replay, scoring, trust, outcome.", "title": "The bench, in five minutes", "length": "about 5 minutes, nine beats",
     "when": "When they want the whole thing.",
     "say": [
         "**The problem.** The agent runs over email and calendar for 5,000-plus users. Every change touched prompts, tools or orchestration, and we had no deterministic way to compare versions. The trigger was a rewrite of how the agent handles multi-turn conversations: too big to eyeball, too risky to ship on vibes.",
         "**Finding failures.** The scanner runs daily over conversations with cheap deterministic checks first: the agent said it did something and no tool ran, the user repeated themselves, a tool errored and the agent kept going. Twelve classes. Each flag carries the user turn, the agent turn, the tool traces, the reasoning, and two turns either side.",
         "**Judging.** Deterministic signals over-fire, so an LLM judge sits on top, its rubric built from a week of flags I labelled by hand, a couple of hundred. It agrees with a human on roughly three in four as genuine. We reconcile it weekly, because as features change, yesterday's bug becomes today's expected behaviour.",
         "**Promotion.** A genuine bug is fixed by hand, then promoted: a reconciler adds a new case, updates one, or merges it into a case that already covers the failure, so the bench does not fill with duplicates. A little over a hundred cases now.",
         "**The snapshot.** For a query type like 'create a task from this email', we pulled about twenty-five real instances and looked at every tool used across them: six or seven, against an ideal path of two or three. The snapshot covers all of them, plus deliberate ambiguity. The base is append-only, so a case that used to pass and now fails points at the agent, not the fixture.",
         "**Replay.** The agent runs from the CLI with a harness flag. Tool code runs for real; at the provider boundary the call goes to the case's SQLite copy, which returns rows in the provider's shape. Writes land there, so a task created at turn two is visible at turn three, and we reset to the base between cases.",
         "**Scoring.** Deterministic assertions against the snapshot: the right tools, the right records, every event in the window in the output. Then an LLM judge for what is not enumerable, like a summary's quality. The headline number is tool calls per completed task: 2.5 down to 2.2 means the same outcome, found faster.",
         "**Trustworthy and cheap.** About ten percent of cases are flaky, so those run three times and we read a pass rate. A change to a tool or its description runs only the cases whose snapshots touch it: fifteen to thirty cases, under ten minutes. The full bench runs nightly, about half an hour.",
         "**Outcome.** It's how we signed off the orchestration rewrite: old and new agent against the same hundred-plus cases, and we could point at exactly which cases got better, which got worse, and why."]},
    {"id": "refunds", "land": "The case first: a clean ledger missing two refunds. Then the lesson: assert against ground truth you hold.", "title": "When the bench passed something broken", "length": "about 75 seconds",
     "when": "Tell me about a false signal. Lead with the case, never with 'I don't have one'.",
     "say": [
         "The clearest one was a ledger request: pull every financial event across my accounts and cards into one view. The agent produced a clean, well-formed ledger and left out two refunds. Every surface check passed, and the same omission showed up again on a later agent version.",
         "We found it the way you find most of these: a user noticed the output was wrong rather than malformed. The report path and the frustration signals don't fire when an answer merely looks right.",
         "The lesson was about what the scorer asserted. We checked trajectory and shape, and nothing checked completeness. For this class we could, because we own the snapshot: the fixture knows how many financial events fall in that window, so the case can assert every one appears. That's asserting against ground truth we hold, which is different from pinning an expected answer, and it's the advantage of freezing a world rather than a transcript.",
         "Where I'd stay honest: it only works when the correct answer is enumerable from the fixture. A meeting brief isn't a set you can count, so those need a human lens and stay out of automated gating."]},
    {"id": "miss", "land": "A miss is information. Make it cheap to resolve: diff, accept as an alias, then policy by effect.", "title": "The cache miss: the better the change, the worse the replay", "length": "about 90 seconds",
     "when": "A prompt change makes the agent call search_email with different phrasing, and the replay dies.",
     "say": [
         "First thing I'd separate: a miss is information. It's telling you the agent's behaviour changed, which is the thing you were measuring. So the goal isn't to make misses disappear, it's to stop a miss from killing the run and make it cheap for a human to resolve.",
         "What I'd ship first is the miss experience. Fail loudly with a diff: the recorded call, what the new agent tried, how far apart they are. Then one command to accept that variant as equivalent, which writes a static alias. Deterministic, auditable, no threshold, and it generates labelled pairs for anything automatic later.",
         "Second, enrichment at import: index the argument variants seen across every session with the same intent, so one recorded result can answer phrasings you've actually observed. That's what we did at alfred_ by hand. It needs volume, so it defaults off.",
         "Fuzzy matching last, carefully: pick the band from score distributions of known-equivalent and known-different pairs, treat the overlap as ambiguous, and ship it in shadow, then suggest, then opt-in per tool. To know it's wrong a week later: a golden set tracked every release, plus miss rate, fuzzy-hit share and the ambiguous share. And every fuzzy hit is stamped on the node, because a silent false pass is the worst bug an eval product can ship."]},
    {"id": "critique", "land": "Provenance: a reader cannot tell recorded from live. Asked as a question, tied to your own anti-fabrication fix.", "title": "What's wrong with Kitaru", "length": "about 60 seconds",
     "when": "Name one thing that's wrong, badly designed or oversold. Never answer with a compliment. If stuck: 'give me a second'.",
     "say": [
         "The one that stood out to me is provenance on mocked calls. When a tool has no policy, or on_miss is set to passthrough, the call goes out to the live provider and the node doesn't carry anything saying so. Someone reading a replay can't tell which results came from the recording and which came from the real world. For a product whose core promise is that a replay is trustworthy, I'd want every node stamped with how it was served.",
         "That one's personal, because the equivalent bug at alfred_ was the agent claiming it did something it never did. We fixed it by grounding the claim against the real tool-execution record rather than the agent's account of it. Same shape of problem.",
         "The second is time: the tool results are frozen but the agent's clock isn't, so anything reasoning about 'today' drifts against an old snapshot and shows up as a confusing failure rather than an obvious one."],
     "never": ["In reserve: evaluators see only what the trace captured; provider-native tools bypass the policy; there is no repeat-run machinery; multi-turn replays only the last turn.",
               "Ask about the gaps as questions. Never call them bugs."]},
    {"id": "compare", "land": "Kitaru froze the transcript, I froze the world; they fail in opposite directions. Promote on fork.", "title": "The comparison, when they ask how the two designs differ", "length": "about 30 seconds",
     "when": "Hold this until they ask. It is the strongest closing move.",
     "say": [
         "Kitaru freezes the transcript, so ingestion is free and counterfactuals are brittle. We froze the world, so counterfactuals held up and ingestion was expensive. They fail in opposite directions.",
         "The interesting product question is whether a recorded session can be promoted into a small queryable world model on demand, so the common case stays free and only the sessions you actually fork on get upgraded into something the agent can explore."]},
    {"id": "close", "land": "I've built this in-house and know what it costs. I'd like to build it as the product.", "title": "The close", "length": "about 20 seconds",
     "when": "The last minute. Then ask about next steps plainly.",
     "say": [
         "This is the first eval product whose source I've read and come away thinking the hard parts were hard for the right reasons. I've been on the other side of it: I know what it costs to build in-house and what it costs to keep. I'd like to build it as the product."]},
]

# The technical question bank. Each answer is written to be said.
QA = [
    {"group": "The role: product engineer, in public", "blurb": "What product engineer means to you, the move into it, and the public half of the job that Lennart and Michael both raised.", "items": [
        {"q": "What does a product engineer mean to you?", "short": "What product engineer means to you", "tests": "Do you know the job, or only the title?",
         "a": ["Owning the loop from a user's confusion to the shipped fix, and back to the user. Not a layer of the stack: the problem.",
               "At alfred_ that's what the eval work really was. I read real conversations to find what broke, fixed it, built the tool that proves it stays fixed, and wrote it up so the team used it.",
               "For Kitaru it's the same loop with developers as the users: someone's replay misses, I see it in Slack or GitHub, reproduce it, ship the fix and the doc, and reply in the thread. And the part engineers skip: making sure people know it exists."],
         "land": "Owning the loop from a user's confusion to the shipped fix, and back to the user.",
         "notes": ["Their post: 'This is not a backend role or a frontend role.' 'Own the complete loop: design, implementation, tests, documentation, rollout.'",
                   "'Convert user confusion into same-day PRs' and 'fix onboarding friction through PRs, not tickets'. Your answer should sound like that week, not a definition.",
                   "End on the public part: it is the half they asked about in both earlier rounds."]},
        {"q": "You've been a backend and AI engineer. Why product engineer, and why now?", "short": "Why the move to product engineer", "tests": "Is this a real move or a relabel? Will you miss deep specialist work?",
         "a": ["I've been doing the job without the title. The work that mattered most at alfred_ wasn't a layer of the stack; it was noticing we couldn't tell whether a new agent was better, and building the thing that could.",
               "What I want now is for that to be the job, on a product whose users are engineers like me, where I feel a clunky API myself instead of hearing about it.",
               "Kitaru is that. I built a rough version of it in-house, so I know the user's pain from the inside, and I know which parts of it were hard."],
         "land": "I've been doing the job without the title; I want it to be the job, on a product for engineers like me.",
         "notes": ["The post rules out 'specialists seeking deep focus in one stack area' and people who see 'ship in days' as reckless. Say you want breadth and pace.",
                   "It asks for 'product taste for developer tools': feel 'physical pain when an API is clunky'. Have one API you find clunky and why, from your own work.",
                   "Keep alfred_ positive: the move is towards this, not away from there."]},
        {"q": "This role is partly public: posting, demos, talking about Kitaru. How do you feel about that?", "short": "The public half of the job", "tests": "Will you actually do it, and do it like a senior engineer rather than a marketer?",
         "a": ["I like it, and it isn't new to me. I have a YouTube channel, I'm active on LinkedIn, and I post when I build my own projects: MockFlow-AI shipped with a launch video, and I presented MetaRAG at INFORMS Analytics+ to 700-plus practitioners.",
               "What I haven't done yet is do it for an employer's product, and that's part of why this role appeals.",
               "For an open-source developer tool, writing about what you shipped is part of shipping. The release, the docs, the example and the post are one piece of work. And I'd rather show a working replay than describe one: engineers share what teaches them something they can use on Monday."],
         "land": "Public is part of shipping for an open-source tool, and I already do it for my own work.",
         "notes": ["Lennart and Michael both raised it explicitly. They want someone ready to build in public. Treat it as a skill with a habit behind it, not enthusiasm.",
                   "Senior framing: posts that teach (a walkthrough on real data, an honest trade-off essay) over announcements. Never hype, never follower counts.",
                   "Be honest about the gap (not for an employer yet) and pair it with a plan (a post per meaningful release). That is their value Be honest in action.",
                   "Have one link ready to share on screen: your best video or the talk."]},
        {"q": "What would your first post about Kitaru be?", "short": "Your first post about Kitaru", "tests": "Taste: do you know what developers read?",
         "a": ["A walkthrough on real data, not a feature list. Import a handful of traces from an agent, find a failure, change the prompt, replay, and show the one case that got fixed and the one that got worse. Under five minutes, repo linked.",
               "The second would be the essay behind it: freezing the transcript against freezing the world. It's the trade-off I lived at alfred_, and every team building agent evals hits it.",
               "Both teach something a reader can use on Monday, and both end with Kitaru doing the work."],
         "land": "A five-minute walkthrough on real traces: find a failure, change one thing, prove it with a replay.",
         "notes": ["ZenML's own public content is useful first: the LLMOps Database is about 2,100 real case studies. Match that tone.",
                   "Alex writes publicly on his blog; referencing a post of his you actually read is a good bridge, if it is true."],
         "figs": ["forkReplay"]},
        {"q": "Explain Kitaru to an engineer who has never heard of it, in thirty seconds.", "short": "Kitaru in thirty seconds", "tests": "Can you sell the product plainly?",
         "a": ["You have agent sessions in production and a change you want to make. Kitaru records what the tools returned, then re-runs your real agent against those recorded answers, so you see what your change does to real sessions without touching production.",
               "It's regression testing for agents, built from traffic you already have. And because it grew out of durable execution, the same recording lets a crashed agent resume from its last checkpoint instead of starting over."],
         "land": "Regression testing for agents, built from the traffic you already have.",
         "notes": ["Launch (April 2026): a durable execution layer for Python agents, with crash recovery, human-in-the-loop and replay from any checkpoint. The replay-eval framing came in August. Both are true; lead with the one their homepage leads with on the day."],
         "figs": ["kitaruReplay"]},
        {"q": "What would you do in your first month?", "short": "Your first month", "tests": "Do you start with users and ship early?",
         "a": ["First two weeks: use Kitaru the way a new user does, on a real agent of mine, and write down every stumble. Read the support threads in Slack and GitHub. Pick up small user-reported bugs, so I learn the codebase by shipping.",
               "By the end of the month: one visible improvement from those notes, shipped with its doc and a short post. Probably the miss experience, since that's where replays hurt first.",
               "And I'd ask you both which user problem is costing you most, and start there instead of my guess."],
         "land": "Use it as a new user, ship small fixes to learn the code, then one visible improvement with its doc and post.",
         "notes": ["The post: 'Use Your Own Products', 'Fix onboarding friction immediately through PRs, not tickets'.",
                   "Ending with a question to them turns a plan into a conversation."]},
        {"q": "Users ask for everything. How do you decide what to build?", "short": "Deciding what to build", "tests": "Product judgement and pace.",
         "a": ["Frequency times pain, weighted by whether it blocks adoption. At alfred_ the scanner told me what actually broke rather than what people guessed would break, and that ordering beat any roadmap debate.",
               "For a developer tool: first anything that stops someone getting a first replay working, because that's where you lose them. Then what many users hit. Then the hard, interesting problems.",
               "And I'd rather ship a two-day prototype and watch someone use it than write a two-week design doc."],
         "land": "First whatever blocks the first replay, then what many users hit, then the hard problems; prototype over debate.",
         "notes": ["The post: not for those 'preferring two-week design debates over two-day prototypes'.", "Their value Be efficient: 'fail fast and learn even faster'."]},
        {"q": "What's a weakness you're working on?", "short": "A weakness", "tests": "Self-awareness without a fake weakness.",
         "a": ["Doing the public part professionally. I build in public on my own projects, but I haven't been the person writing about an employer's product on a schedule.",
               "I'd close it the way I close any gap: a cadence rather than inspiration. Here that would be a post for every meaningful release, written as part of shipping it, the same way the doc is."],
         "land": "The public part, done professionally: I'd make it a cadence tied to releases.",
         "notes": ["A true weakness that the role fixes reads better than 'I work too hard'.", "Keep it short; don't reopen it."]},
        {"q": "How do you give and take code review?", "short": "Code review", "tests": "Low ego, high standards.",
         "a": ["Direct on the code, kind to the person. I say what I'd change and why, and I separate 'must fix' from 'taste'.",
               "Taking it, I'd rather be corrected than stay wrong, and I read every line I merge, including what a coding agent wrote. An agent's code gets reviewed like a colleague's, not trusted like a compiler's."],
         "land": "Direct on the code, kind to the person; I'd rather be corrected than stay wrong.",
         "notes": ["The post, word for word: 'Direct in code reviews, kind in conversation. Prefer correction over being wrong.' Show it; do not quote it."]},
        {"q": "Which of our values do you connect with?", "short": "Their values", "tests": "Did you read about us, and is it real?",
         "a": ["Be honest: provide candid feedback and own your actions. The eval work only worked because we stopped trusting the agent's own account and checked the execution record.",
               "I try to hold myself to the same standard, including in an interview: I'd rather say 'I don't know, here's how I'd find out' than bluff."],
         "land": "Be honest, because the whole eval story is about not trusting an account over the record.",
         "notes": ["Their five: Challenge everything, Empathize, Be efficient, Enable others, Be honest.", "Pick one and tie it to a story; do not list all five."]},
        {"q": "Where do you want to be in two or three years?", "short": "Two or three years out", "tests": "Ambition that fits a small company.",
         "a": ["Owning a product area of developer infrastructure end to end: the users, the code, and the story people tell about it.",
               "And close enough to agents in production to know what breaks before most teams hit it. A small team shipping fast is the fastest way I know to get there."],
         "land": "Owning a product area end to end, close to where agents break.",
         "notes": ["'No layers, no politics' in the post: don't talk about titles or managing people."]},
    ]},
    {"group": "Your work, at depth", "blurb": "The bench and alfred_, at the depth Alex will go.", "items": [
        {"q": "Walk me through your day-to-day.", "tests": "Is the ownership real?",
         "a": ["It varies, but a typical week has three modes. Feature work on the email automation layer: the rules engine is our stickiest feature, users create rules in plain language from chat, so there's a steady stream of 'this rule didn't fire when I expected'.",
               "Reliability: I own the eval harness and the scanner that reads real production conversations and promotes genuine failures into a triage queue, so I'm looking at what actually broke rather than what I guessed would break.",
               "And work nobody asks for until it hurts. Our LLM spend was concentrated in one background pipeline, and I spent a week instrumenting cost per model and per stage before changing anything, because I didn't trust my intuition about where it was going."],
         "land": "I own a slice end to end, including after it ships."},
        {"q": "When you replay a case, what's running, what's faked, and where does the faking happen?", "tests": "Intercept depth.",
         "a": ["The tool body runs. Only the provider call is swapped, behind a harness flag that routes to the snapshot. So permission checks, ranking and response shaping are all on the production path.",
               "The alternative, replacing the whole tool function, would have meant testing the model against a simplified world, and most of our bugs lived in the seam between tool output and model interpretation."],
         "land": "Swap the provider, not the tool."},
        {"q": "How long does one case take to author, end to end?", "tests": "The number the whole scaling argument rests on. Do not dodge it.",
         "a": ["I never instrumented it, so this is an estimate rather than a measurement: about three to four hours per case at the start, dropping to forty-five minutes to an hour once the scanner aggregated the tool traces and prior turns automatically.",
               "It's expensive, and that's the honest trade-off. We bought counterfactual tolerance and paid for it in expert time per case. Importing a thousand recorded sessions is nearly free and gives you weaker cases. I'd want both."],
         "land": "Estimate first, with its basis. Never deflect to how cases are found."},
        {"q": "Why SQLite when production is Postgres?", "tests": "The sharpest fidelity question you will face.",
         "a": ["Two reasons, one good and one I'd revisit. The good one: a snapshot is a single file. Trivial to capture, trivial to spin up per case, no process to manage, full isolation between cases by construction, and I can open it and see exactly what the agent saw.",
               "The one I'd revisit: it isn't the production engine. No row-level security, different type affinity, dialect differences. So it tests agent behaviour faithfully and database behaviour not at all.",
               "Rebuilt today I'd use Postgres template databases, CREATE DATABASE ... TEMPLATE, cloning per case at near-SQLite speed on the real engine. The cost is a server in the test path. Did the gap bite? Not that I caught, which isn't quite the same thing."],
         "land": "Name the fidelity you traded, then the production-grade alternative.",
         "notes": ["Why it was right then: one local runner, a tiny team, and isolation per run mattered more than a distributed database.",
                   "What breaks first as it grows: concurrent writers, running it across machines, and production semantics like RLS. Next step: per-run isolated databases, then ephemeral Postgres.",
                   "The invariant to keep whatever the engine: every run starts from a known, isolated state."]},
        {"q": "What happens when the production schema changes?", "tests": "Have you lived with it, or only built it?",
         "a": ["The base snapshot is append-only by design: old rows don't move under old cases, and a new case that needs another Michael gets a new name. So a case that used to pass and now fails is a signal about the agent, not the fixture.",
               "The structural fix I'd want on top is to version the snapshot and pin each case to a version, and fail loudly on a mismatch. A test that silently measures the wrong thing is worse than one that refuses to run."],
         "land": "It rots quietly unless the version is pinned and checked."},
        {"q": "How do you stop teaching to the test?", "tests": "Do you know what a fixture is for?",
         "a": ["We never pin expected output text. Assertions are computed from the snapshot: if the fixture has four financial events in the window, the output must contain four. That's checking against ground truth we own. Pinning a known-good answer would be teaching to the test."],
         "land": "Assert against ground truth you hold."},
        {"q": "How do you deal with nondeterminism?", "tests": "Do you separate noise from regression?",
         "a": ["Partly by removing it, partly by running more. On the gating path I removed it: the decision layer is deterministic risk scoring rather than a model call, because if an action commits a side effect I don't want the classification to be a sample.",
               "On generative paths you can't, so known-flaky cases, about ten percent, run three times and report a pass rate. A case that flips between versions without a code change is quarantined and looked at. One lucky run never counts as a pass.",
               "If they push on tool calls per task: on its own it rewards an agent that guesses instead of clarifying, which is why it sits next to counts of false completion claims. A version that got decisive and wrong would win on one and lose on the other."],
         "land": "Remove it on dangerous paths; measure around it elsewhere."},
        {"q": "A tool the snapshot doesn't cover: what does the agent get back?", "tests": "Provenance: can a reader tell recorded from invented? (Mock 1 gap.)",
         "a": ["It never leaves the machine: with the harness flag on, every provider call goes to the snapshot, so there is no path to a live system.",
               "What the agent gets back is the weak spot. Today it's an empty result, and the call is logged against the run. But an empty result is a plausible answer: the agent can read it as 'there are no meeting notes', which is the harness telling it something false.",
               "So I'd return an explicit 'not in this snapshot' error the agent can't mistake for data, and treat any run that hit one as harness-limited: out of the headline number, onto a list that becomes the backlog for enriching the snapshot. It's the same problem as a Kitaru passthrough node with no mocked mark."],
         "land": "Name it as a gap before they do; every answer should carry how it was served."},
        {"q": "What makes a run count as done?", "tests": "Is the headline metric gameable? (Mock 1: took three turns to get concrete.)",
         "a": ["Deterministic assertions against the snapshot. For 'make a todo list from this email', the snapshot knows the right email and its action items, so the run passes if the agent read that email and the tasks match those items.",
               "Tool calls per completed task is computed only over runs that pass, so an agent that wraps up early on an empty result doesn't look efficient, it fails. We moved 2.5 to 2.2 on that for the same outcomes.",
               "On its own the metric would reward guessing over clarifying, so it sits next to a count of false completion claims."],
         "land": "Name the check, give one worked example, then the metric's blind spot."},
        {"q": "Four action items, the agent creates three: pass or fail?", "tests": "Completeness, and the refunds lesson. (Mock 1: answered 'pass'.)",
         "a": ["It fails, and code decides, not a model. Action items are enumerable: the snapshot knows there are four, so the case asserts all four appear. Three of four fails that assertion and scores 0.75 on the completeness number we track across the bench.",
               "We learned it on the ledger that left out two refunds while every surface check passed. A model only judges what can't be counted, like whether a brief is useful, and those cases stay out of automated gating."],
         "land": "Enumerable means asserted, never judged."},
        {"q": "How do you know the judge is still right?", "tests": "Is the judge's value measured? Name which judge.",
         "a": ["There are two judges, in different states. The scanner's judge, which decides whether a production flag is a real bug, is calibrated weekly against fresh human labels on a sample: about three in four agreement. When agreement drops it's usually because a feature changed what correct means, and the rubric gets updated.",
               "The completeness judge on the bench isn't calibrated yet; where the answer is enumerable I replaced it with assertions, so it only judges what can't be counted.",
               "To tell judge drift from agent change: keep a frozen set of past outputs and re-judge it when the judge's model or prompt changes. The outputs didn't move, so if the verdicts did, the judge moved. And the judge's model and prompt are pinned per run."],
         "land": "Two judges: one calibrated, one honestly not. Re-judge frozen outputs to catch drift."},
        {"q": "How do you decide what becomes an eval case?", "tests": "The heart of the role.",
         "a": ["The first filter is the whole game, because everything downstream is conditioned on it. Early on a signal flagged abandoned conversations, the agent said something and the user never replied, and a large share were one-way notifications where no reply was ever expected. Another class, 'agent did nothing', was just wrong: the agent had acted, we weren't joining against the tool-execution record.",
               "Both got fixed by grounding the signal in execution truth rather than tuning a threshold."],
         "land": "Ground signals in execution truth, not thresholds."},
        {"q": "What doesn't the bench catch?", "tests": "Do you volunteer the limit?",
         "a": ["Anything where the right answer isn't enumerable from the fixture, like whether a meeting brief is actually useful. And anything the scanner never saw fail: the bench only knows failures that happened. New features start with no coverage."],
         "land": "Volunteer the limit before they find it."},
        {"q": "Was it gating deploys?", "tests": "Is it real engineering practice?",
         "a": ["Nightly runs plus subset runs on changes, reviewed by whoever made the change. It informed releases and blocked the big ones, like the orchestration rewrite. It wasn't a hard CI gate on every commit, because a thirty-minute run with model variance on every push would have slowed the team more than it protected them."],
         "land": "It gated the releases that mattered."},
        {"q": "What would you do differently?", "tests": "Self-awareness.",
         "a": ["Instrument authoring time from day one, since I can't give you a measured number. And version the base snapshot explicitly so each case pins a version, instead of relying on append-only discipline."],
         "land": "Two concrete changes, no hedging."},
    ]},
    {"group": "Backend depth", "blurb": "Idempotency, queues, Postgres and providers.", "items": [
        {"q": "A side-effecting tool call fails halfway. What happens?", "tests": "Idempotency and crash windows.",
         "a": ["You can't get exactly-once against a third-party API you don't control, so the honest goal is at-least-once delivery with effects that are safe to repeat.",
               "We write the intent to a tool-execution ledger before the call, so there's a record even if the process dies mid-flight. That ledger is also what the anti-fabrication guards read: the agent can't claim it sent something unless there's a row saying it did. And side-effecting actions sit behind a confirm verdict with a bounded undo window.",
               "If the send succeeded but the response timed out, reconcile by looking the effect up at the provider before retrying blind. The design work is deciding where the idempotency key lives."],
         "land": "Exactly-once execution is out of reach; exactly-once logical effect is the goal: intent first, a key, reconcile before retry.",
         "notes": ["Classify the call first: read, idempotent write, non-idempotent write, external effect. The policy follows the class.",
                   "Where the provider supports it, pass your idempotency key through to them, so their side refuses the duplicate too.",
                   "In Kitaru terms: on a forked replay a write that misses should fail closed, never pass through."]},
        {"q": "Tell me about the queue. How is it claimed and drained?", "tests": "Postgres under concurrency.",
         "a": ["At our volume it's a Postgres table with a periodic drain, which is respectable at that scale. Where it strains is concurrent claiming: SELECT ... FOR UPDATE SKIP LOCKED so two workers don't serialise on the same rows.",
               "And a cron drain's worst-case latency is the interval, which is exactly the problem we hit on notifications: about ninety seconds down to about three by triggering on the event, with cron kept as a backstop, not removed."],
         "land": "Name the idiom, and the backstop."},
        {"q": "Hardest bug you've debugged?", "tests": "Mechanism-level understanding.",
         "a": ["Agent-facing read functions in Postgres were SECURITY DEFINER RPCs, so they run with the definer's privileges and can see past row-level security to do their job. The subtle part: Postgres grants EXECUTE to PUBLIC by default on a new function, so a function deliberately bypassing RLS was callable by any authenticated role. A cross-user leak class.",
               "Nothing was exploited; it came out of an adversarial design review. We fixed the grants, and the more important fix was the migration checklist, plus the test I'd automate: assert no SECURITY DEFINER function carries a PUBLIC execute grant."],
         "land": "Fix the class, not the instance."},
        {"q": "How do you normalise Gmail, Outlook and IMAP?", "tests": "Provider adapters, his own world.",
         "a": ["One internal model behind all three, where each provider fails differently, which is the same problem as Kitaru's importers across Langfuse, LangSmith and Braintrust with different nouns.",
               "Adapters keep each provider's schema at the edge; inside there's one canonical model with time zones, ids and contacts normalised. Contract tests against recorded provider payloads catch schema drift before users do, and the raw payload is kept next to the normalised one, because when something looks wrong you need to see what the provider actually sent."],
         "land": "Provider schemas at the edge, one canonical model inside, contract tests for drift, raw payload kept for debugging.",
         "notes": ["Have your one concrete behavioural difference between providers ready, and what it forced in the model."]},
    ]},
    {"group": "Tools and the landscape", "blurb": "The ecosystem Kitaru imports from, and how you work with coding agents.", "items": [
        {"q": "What's the difference between LangChain, LangGraph and LangSmith?", "tests": "Do you know the ecosystem Kitaru imports from?",
         "a": ["LangChain is the open-source framework: model wrappers, prompts, tools, retrievers, and the glue that chains them.",
               "LangGraph is its open-source orchestration layer for stateful agents: the agent as a graph of nodes and edges over shared state, with checkpointers for persistence, human-in-the-loop and streaming. LangChain's agents now run on it.",
               "LangSmith is the commercial platform around both, and it works outside them too: tracing, datasets, evals, a prompt hub and deployment. It's one of the trace sources Kitaru imports from.",
               "In a line: a framework, a runtime for stateful agents, and the observability-and-eval product."],
         "land": "Framework, runtime, platform."},
        {"q": "What's your experience with trace stores, open source or otherwise?", "tests": "Honest scope.",
         "a": ["At alfred_ we kept our own: conversations, the tool-execution ledger and the scanner's flags live in our own tables in Supabase Postgres, and the scanner and the bench run over them. I haven't run Langfuse or LangSmith in production; the closest I've come is importing Langfuse traces into Kitaru's example agent.",
               "What I know well is what a trace needs to hold for evaluation to work, because I built the consumer: tool inputs and outputs untruncated, the reasoning, and enough surrounding turns to judge a flag."],
         "land": "Own tables, honestly; and you know the consumer side deeply."},
        {"q": "Supabase for traces, a dedicated trace store, or build it yourself?", "tests": "Judgement.",
         "a": ["Keeping execution records in Postgres next to product data was the right call for us. The scanner's biggest false-positive fix was joining a flag against the tool-execution record, which is only easy when both live in the same database.",
               "Where a dedicated store earns its place is span trees, a UI for reading them, retention, and cost and latency at volume. So: build it yourself while your questions are about product data; adopt a trace store when your questions become about spans. That's also the appeal of Kitaru's importers: you don't have to pick."],
         "land": "Own it while the questions are about product data."},
        {"q": "How do you use AI in your own workflow?", "tests": "Are your instincts product instincts?",
         "a": ["Heavily, with scaffolding: Claude Code with project instructions and skills for the jobs I repeat, a review pass, and a verification step that drives the running surface instead of trusting that it compiled.",
               "The thing I've got strict about is not trusting an agent's self-report, the same instinct as the anti-fabrication work in our product. And where it's weak: anything depending on runtime state it can't see. It will tell you confidently which code path executes, reasoning from imports. That's exactly the gap replay closes."],
         "land": "Don't trust self-reports, from models or from yourself.",
         "notes": ["The post: 'AI-pilled, not vibes-pilled': know when to let the agent drive and when to take the wheel.",
                   "Say where you take the wheel: concurrency, security and grants, data migrations, anything where a plausible answer is not a checked one.",
                   "Their stack names Claude Code, Cursor and Codex; they also build internal tooling on Kitaru itself."]},
        {"q": "Python or TypeScript?", "tests": "Don't oversell.",
         "a": ["My production work at alfred_ is TypeScript on Deno; my research and ML work is Python. Their server is Python, and I'd say that plainly rather than oversell fluency to someone with years in this codebase."],
         "land": "Plain and exact."},
    ]},
    {"group": "Designing replay and evals", "blurb": "From first principles: what is frozen, how it runs, how it is scored, and where it breaks.", "items": [
        {"q": "Design an evaluation system for agents from scratch.", "short": "Design an eval system", "tests": "Structure before boxes.",
         "a": ["Four decisions, in order. Requirements first: are we reproducing a failure, testing a change, measuring capability, or measuring efficiency? Each wants something different.",
               "Then determinism: decide what is frozen. The transcript, the world, the tool results, or only the external effects. Kitaru freezes the transcript; my bench froze the world.",
               "Then execution: workers claiming runs from a queue with leases, slots, retries, cancellation, and isolation per run.",
               "Then evaluation: outcome and final state first, then policy and safety, then trajectory, then cost and latency, then repeatability across runs."],
         "land": "Requirements, what is frozen, how it runs, how it is scored. In that order.",
         "notes": ["This is the structure behind every other design answer here. When lost, say the four words and pick the one they asked about.",
                   "Defend trade-offs, not a perfect architecture: say why your bench fit alfred_'s scale, and how it breaks at ten times."],
         "figs": ["forkReplay", "kitaruFreeze"]},
        {"q": "Two runs take different paths to the same right answer. Pass or fail?", "short": "Different paths, same answer", "tests": "Outcome versus trajectory.",
         "a": ["Pass. Score the final state against a goal state, not the path. The same goal with different valid paths is normal for agents; tau-bench scores the final database state against an annotated goal state for exactly this reason.",
               "Trajectory is a separate score: efficiency, like tool calls per task, and policy, like whether it did anything it shouldn't have. Keep them apart, so a better path isn't punished as a regression."],
         "land": "Final state against a goal state for pass or fail; trajectory scored separately.",
         "notes": ["The same idea fixes Kitaru's miss problem at the scoring end: a new path that reaches the right state should not fail because a call missed."],
         "figs": ["completeness"]},
        {"q": "pass@k or pass^k?", "short": "pass@k or pass^k", "tests": "Reliability versus capability.",
         "a": ["pass@k is 'succeeds at least once in k tries': right for capability, whether it can ever do this. pass^k is 'succeeds every time in k tries': right for reliability, which is what a user lives with.",
               "For an agent acting on someone's mailbox, pass^k is the honest number; tau-bench showed agents that look fine on one try fall off sharply as k grows. So gating cases report pass^k, and the flaky ten percent run three times."],
         "land": "pass@k asks 'can it', pass^k asks 'will it every time'. Users live with pass^k."},
        {"q": "A worker dies halfway through a replay. What happens?", "short": "A worker dies mid-replay", "tests": "Leases, retries, cancellation.",
         "a": ["The task was claimed atomically, with FOR UPDATE SKIP LOCKED, and holds a lease kept alive by heartbeats. When the heartbeats stop, a sweeper sees the expired lease and puts the task back.",
               "The rerun has to be safe. Replay mostly is, because the tools answer from the recording; anything that went live needs an idempotency key, so a second attempt doesn't repeat the effect.",
               "Two details people miss: cancellation must kill the whole process tree, not only the parent, or orphaned subprocesses keep calling out; and retries need exponential backoff with jitter, or a bad deploy becomes a retry storm. Keep the poller separate from execution slots, so a busy worker still claims work."],
         "land": "Lease, heartbeat, sweeper; reruns safe by idempotency; kill the process tree; backoff with jitter.",
         "figs": ["skipLocked"]},
        {"q": "How would you sandbox replays of a customer's agent?", "short": "Sandboxing replays", "tests": "Threat model first.",
         "a": ["Threat model first: protect the host, keep tenants apart, stop exfiltration. Kitaru's server never runs user code; the worker runs in the customer's environment, which answers most of it by design.",
               "Inside that: least privilege, with credentials scoped to the task and expiring with it. Then isolation picked by risk, up a ladder: process, container, gVisor or Kata, microVM, confidential VM.",
               "And effects by class: reads allowed, reversible writes inside a controlled window, irreversible actions behind confirmation. The adapter hook has to see every effect, which is why a bare HTTP call inside the agent is the gap to close."],
         "land": "Threat model, least privilege with task-scoped credentials, an isolation ladder by risk, effects by class.",
         "figs": ["kitaruPlanes", "kitaruLive"]},
        {"q": "Durable execution and replay evals: how are they related?", "short": "Durable execution and replay", "tests": "Do you understand their pivot from the inside?",
         "a": ["Same substrate, different intent. Durable execution records a workflow's history: deterministic workflow code, nondeterministic work in activities, and after a crash you resume by replaying history instead of re-running what finished.",
               "Replay evals reuse that recording for another job: re-run the agent with a change and answer the tools from history.",
               "That's why Kitaru could move from one positioning to the other: checkpoints and replay were already there. Durable execution wants the same result again; an eval wants a different result and wants to know why."],
         "land": "Same recording, opposite intent: durable execution wants the same result again, an eval wants a different one and why.",
         "figs": ["kitaruPosition"]},
        {"q": "Stub, mock, fake, record-replay: when would you use each?", "short": "Stub, mock, fake, replay", "tests": "Testing vocabulary with judgement.",
         "a": ["A stub returns a canned answer. A mock returns an answer and asserts how it was called. A fake is a small working implementation with state. Record-replay captures real results and reuses them deterministically.",
               "My SQLite snapshot is a fake: the agent can take a new path and still get a coherent answer. Kitaru is record-replay: cheap and realistic for paths already seen, brittle for new ones.",
               "For stateful agent evaluation, fakes beat mocks; record-replay wins on cost at volume. The product question is when to promote one into the other."],
         "land": "My bench is a fake, Kitaru is record-replay; stateful agents need fakes for new paths.",
         "figs": ["kitaruFreeze"]},
        {"q": "Why store a trace as a self-referencing tree?", "short": "Traces as a tree", "tests": "Data modelling.",
         "a": ["Because agent work nests to any depth: tool calls, subagents, spans, retries. One table with a parent id represents all of it, and a recursive query walks ancestors or descendants.",
               "It beats fixed-depth tables, which break on the first subagent of a subagent, and it's more queryable than an opaque JSON blob. The cost is deep recursive queries on big traces: index the parent column and cache subtree summaries if they get slow."],
         "land": "Nesting to any depth in one table; recursive queries; index the parent and cache subtrees.",
         "figs": ["kitaruModel"]},
        {"q": "What's hard about replay? How would you design one?", "tests": "First principles, not reciting Kitaru.",
         "a": ["Clarify first: are we reproducing a known failure or testing a change? The design splits there. Then name the hard part: capture isn't hard, divergence is.",
               "Sketch: intercept every boundary the agent crosses, model calls, tool calls, clock, randomness, key them for lookup, and re-run the real agent with the recording answering for the outside world.",
               "Then attack it. Divergence: exact keys punish the change you're measuring. Side effects: interception must sit at a boundary that catches everything, or a direct HTTP call walks past it. Ordering: repeated identical calls and concurrency make an ordinal ambiguous. The model: if model calls go live, the baseline isn't deterministic, so you need repeat runs."],
         "land": "Name the hard part before sketching."},
        {"q": "Multi-turn: the agent's reply changes at turn two. What happens at turn three?", "tests": "The open problem.",
         "a": ["The recorded turn-three user message may no longer make sense, in Kitaru or in my bench: freezing the world doesn't fix user divergence. The options are last-turn replay, which is honest but blind; a stateful world across turns, which fixes effects but not replies; or a simulated user seeded from the recording, which only counts once it's calibrated against real replies. I'd scope the simulator to sessions that actually fork early."],
         "land": "A simulator counts only once it's calibrated."},
        {"q": "If you ran Kitaru for a quarter, what would you ship first?", "tests": "Product judgement with dependencies.",
         "a": ["I wouldn't rebuild the runner, the sandbox or the replay layer; those work. First, provenance on every node: small, and everything else depends on a reader trusting where a result came from. Then productive misses: the recorded-versus-attempted diff and one action to accept a variant.",
               "Then the evaluation layer above the runner, which is where alfred_ taught me the value is: turning production traces into eval cases, stateful multi-turn environments, scoring by outcome and final state plus policy, and regression analytics across runs.",
               "The useful unit isn't only a recorded trajectory. It's whether an agent can reliably change a realistic world into the right state."],
         "land": "Trust first, then productive misses, then the evaluation layer above the runner.",
         "notes": ["Order by dependency: trust, then the cheap feature, then the hard problem.", "Say what you would not rebuild; it shows you respect what exists."]},
    ]},
    {"group": "Product engineering on Kitaru", "blurb": "The work the job post names: adapters, onboarding, replay debugging, shipped fast and driven by users.", "items": [
        {"q": "Design the adapter for a new agent framework.", "short": "A new framework adapter", "tests": "SDK design and developer experience.",
         "a": ["Start from what the framework already exposes: its tool-execution hook, its model-call hook, and how it represents a turn.",
               "The adapter does three things: record every tool call as a node with its cache key, answer calls on replay through the policy, and mark every node with how it was served. The user-facing surface is one line of setup; the rest is configuration with good defaults.",
               "Then contract tests: one shared suite every adapter must pass, against recorded fixtures, so adapters can't drift. Canonical JSON especially, since that's where cross-adapter keys break."],
         "land": "Hook what the framework exposes; record, answer, mark how it was served; one line of setup; a shared contract suite.",
         "notes": ["The post names 'new framework adapters' as an example deliverable. Frameworks it lists: PydanticAI, OpenAI SDK, Claude Agents SDK."],
         "figs": ["kitaruReplay", "kitaruKey"]},
        {"q": "A user says their replay is broken. Walk me through it.", "short": "Debugging a user's replay", "tests": "User-driven iteration, same-day fixes.",
         "a": ["Get the session id and the replay id, not a description, and reproduce against their recording.",
               "Then read provenance node by node: which calls hit, which missed, which went live. Most breakages are one of four: a key mismatch, so show both canonical forms side by side; an adapter or framework version change; a tool with no policy; or the environment the worker spawned differs from theirs.",
               "Fix it, add the case to the contract tests, change the error message or doc that would have saved them, and reply in their thread with the PR. Same day if it's small."],
         "land": "Reproduce from ids, read provenance node by node, fix, add the test, fix the message, reply with the PR.",
         "notes": ["The post: 'Engage actively in Slack and GitHub. Convert user confusion into same-day PRs.'"],
         "figs": ["kitaruPolicy"]},
        {"q": "How would you test an SDK across frameworks and versions?", "short": "Testing across frameworks", "tests": "Quality at speed.",
         "a": ["A small matrix: supported Python versions against each framework's oldest supported and newest release. Contract tests from recorded fixtures on every PR.",
               "A nightly run against the frameworks' newest releases, so a breaking change upstream shows up before a user reports it.",
               "And one end-to-end example per framework that runs the real quickstart, because for a new user the quickstart is the product."],
         "land": "A small matrix, contract tests per PR, nightly against upstream, and the quickstart as a test.",
         "notes": ["'Raise the bar: better tests, clearer interfaces, sharper documentation.'"]},
        {"q": "What goes into the first ten minutes with Kitaru?", "short": "The first ten minutes", "tests": "Onboarding taste.",
         "a": ["One goal: a first replay that shows the user something they didn't know. Install, wrap an agent in one line, import or record a few sessions, replay with one change, see a diff.",
               "Every step that asks for a decision is a place people drop off, so defaults everywhere, and an example agent for people who don't have one ready.",
               "And measure it: time to first successful replay, and where people stop. A guided tour that walks users through their own code, like the Claude Code skills, is the right shape for this."],
         "land": "A first replay that teaches the user something, with no decisions on the way; measure time to it.",
         "notes": ["Alex ships the Claude Code skills behind the guided tour: this question may come from him. Ask what the tour changed."]},
        {"q": "What makes an error message good?", "short": "A good error message", "tests": "Product taste for developer tools.",
         "a": ["It says what happened, why, and the next thing to type. For a replay miss: which tool, the recorded arguments next to the new ones, and the command to accept the variant.",
               "A message that sends someone into the source code is a bug in the product, not in the user."],
         "land": "What happened, why, and the next thing to type.",
         "notes": ["The post: 'Every API choice, error message, and example should reflect developer experience.'"]},
        {"q": "A better prompt misses every recording. What do we build?", "tests": "Their central problem, as product judgement. (Mock 1 gap.)",
         "a": ["First, a miss is information: the agent's behaviour changed, which is what they were measuring. The goal isn't to avoid misses, it's to stop one from killing the run and make it cheap to resolve.",
               "First build: the miss experience. Misses grouped by tool with a count; open one and it's the recorded call next to what the new agent sent. If they're equivalent, one action accepts it as a static alias and the next replay hits. Deterministic, auditable, and every accepted pair is labelled data for matching later.",
               "Second: policy by effect. A read that misses can fall through to the customer's environment, marked live on the node. A write that misses fails closed on a fork, never passthrough.",
               "The limit: that fixes rephrasing, not a different path. For those few sessions, promote the trace into a small queryable world, which is what my bench does. The common case stays free."],
         "land": "Reframe, then build up in order of cost. If you blank, start with what the user sees."},
        {"q": "The customer says the two searches are the same. What button, and what changes next replay?", "tests": "Can you land a design down to data? (Mock 1 gap.)",
         "a": ["'Accept as equivalent.' It writes a static alias for that tool: these new arguments map to that recorded call's result, scoped to the cohort, and it applies to the whole group of identical misses.",
               "Next replay the lookup checks aliases before it misses, so those calls hit, and the node is stamped 'served by alias', so nobody mistakes it for an exact match.",
               "Every accepted pair is a labelled example of 'different arguments, same meaning': the data you'd need to tune fuzzy matching later, shipped in shadow first."],
         "land": "Button, then the data it writes, then what the next replay does with it."},
    ]},
]

# The order the banks show on the Prep tab.
QA_ORDER = ["The role: product engineer, in public", "Your work, at depth", "Designing replay and evals",
            "Product engineering on Kitaru", "Backend depth", "Tools and the landscape"]

ASK = [
    {"to": "Either", "q": "When an unchanged replay diverges because the model just sampled differently, what do you show the user? Is that noise, a finding, or does it fail the baseline?"},
    {"to": "Either", "q": "In multi-turn replays, when the agent's reply changes at turn two, the recorded turn-three message may no longer make sense. How are you handling that today, and is a simulated user on the roadmap or deliberately out of scope?"},
    {"to": "Either", "q": "What's been the hardest thing to get right in the replay path?"},
    {"to": "Either", "q": "How often does a forked replay hit a cache miss for your early users? Is that the main support conversation or a rare edge?"},
    {"to": "Hamza", "q": "Where do you see Kitaru sitting against observability tools long term: is replay the wedge, or the product?"},
    {"to": "Hamza", "q": "One thing I've run into repeatedly is that the hard part isn't collecting traces, it's deciding which production behaviours are worth turning into durable evaluation cases. How are you thinking about that?"},
    {"to": "Alex", "q": "What have you learned from early users about the first ten minutes, and what did the guided tour change?"},
    {"to": "Either", "q": "What would you want someone in this seat to have shipped by the end of the first month?"},
]

TRAPS = [
    ("Leading with history", "Headline first: the real agent against a frozen snapshot of the user's world, only the provider call swapped."),
    ("Dodging the authoring-cost question", "Say it's an estimate, then the number, then the basis."),
    ("Praising Kitaru when asked what's wrong", "Provenance, then time. If stuck, 'give me a second'."),
    ("Two questions in one breath", "One at a time, name the thing, then wait."),
    ("Vague numbers", "5,000+ users, 12 classes, about 3 in 4, 100+ cases, 25 to 30 minutes nightly, 90 to 3 seconds."),
    ("Going sideways when pushed", "Add a detail about the same system, not a second system."),
    ("Defending SQLite", "Name the fidelity gap, then CREATE DATABASE ... TEMPLATE."),
    ("Calling their gaps bugs", "Ask as questions; they maintain the code."),
    ("Citing their PRs or commits", "Never. Ask a normal question and let them bring it up."),
    ("Funding, crunch, internal version names, colleagues' names", "Never."),
    ("Running long", "At minute 70 of 90, hand them your questions."),
]

# Kitaru, read from source (KITARU.md), as tables.
KITARU_TABLES = [
    {"title": "Tool policies", "note": "Resolution is by exact tool name, then the default.",
     "head": ["Policy", "What it does"],
     "rows": [["passthrough", "Runs the real tool. The default when no policy is set."],
              ["history", "The recorded result, by cache key, within a scope."],
              ["static", "Ordered cases, first match wins; exact or subset matching."],
              ["llm", "Modelled in the API; rejected at runtime by the PydanticAI adapter."]]},
    {"title": "on_miss", "note": "Three values, and every one is a bad escape for an improved agent.",
     "head": ["Value", "What happens"],
     "rows": [["fail", "Raises; the node is recorded failed and the whole replay dies."],
              ["error_result", "The model gets a literal error and keeps running: you grade recovery from an error you invented."],
              ["passthrough", "Calls the real tool; the node carries no mocked attribute. The silent fidelity hole."]]},
    {"title": "The cache key", "note": "sha256(tool_name + a null byte + canonical JSON: sorted keys, compact separators, allow_nan false). No fuzzy or subset matching on history.",
     "head": ["Change to the arguments", "Matches?"],
     "rows": [["Key order, JSON formatting", "Yes"], ["Whitespace inside a string", "No"], ["1 against 1.0, true against 1", "No"],
              ["NaN, infinity, unserialisable", "No key at all: straight to on_miss, no diagnostic"],
              ["Non-ASCII", "Within one adapter language only"]]},
    {"title": "Repeated calls flip with scope", "note": "Ask about the concurrency point as a question: the counter is read, the lookup awaited, then the counter written.",
     "head": ["Scope", "Behaviour"],
     "rows": [["baseline", "The nth recorded node, ordered by started_at: ordered consumption, from completed and failed nodes."],
              ["agent, cohort version", "The latest completed node, the same one every time."]]},
    {"title": "What always runs live", "note": "",
     "head": ["Thing", "Why it matters"],
     "rows": [["Model calls", "Every replay is billed and nondeterministic, even unchanged."],
              ["Anything outside a registered tool", "A bare HTTP call reaches production."],
              ["Provider-native tools", "Recorded but never checked against policy."],
              ["Earlier turns' tool calls", "Dropped: only the final turn re-executes."]]},
    {"title": "Claims against the source", "note": "",
     "head": ["Claim", "Reality"],
     "rows": [["Replays never touch production", "The default policy is passthrough, and so is one on_miss value."],
              ["No card gets refunded twice", "True for registered function tools; native tools bypass."],
              ["Compare distributions across runs", "No repeat-count or aggregation exists."],
              ["Multi-turn replays faithfully", "Final turn only; earlier tool activity stripped."],
              ["No user code runs on the server", "Accurate."]]},
]

ADMIRE = "The selector design is the bit I keep thinking about: storing a JSON path into the payload instead of copying text out, so a human judgement, an evaluator verdict and the UI all point at the same coordinates. I hand-rolled a worse version."

# One question, out loud, timed. ref points at the script or answer to compare against.
DRILLS = [
    {"id": "intro", "prompt": "Introduce yourself.", "target": "40 seconds", "seconds": 40, "ref": "#say-intro"},
    {"id": "seat", "prompt": "Why this seat, and why now?", "target": "45 seconds", "seconds": 45, "ref": "#say-seat"},
    {"id": "bench2", "prompt": "Tell me about your eval bench.", "target": "2 minutes", "seconds": 120, "ref": "#say-bench2"},
    {"id": "refunds", "prompt": "When did your bench pass something that was actually broken?", "target": "75 seconds", "seconds": 75, "ref": "#say-refunds"},
    {"id": "critique", "prompt": "Name one thing in Kitaru that's wrong or oversold.", "target": "60 seconds", "seconds": 60, "ref": "#say-critique"},
    {"id": "miss", "prompt": "A prompt change causes a cache miss and the replay dies. What would you do?", "target": "90 seconds", "seconds": 90, "ref": "#say-miss"},
    {"id": "sqlite", "prompt": "Why SQLite when production is Postgres?", "target": "60 seconds", "seconds": 60, "ref": "#qa"},
    {"id": "halfway", "prompt": "A side-effecting tool call fails halfway. What happens?", "target": "60 seconds", "seconds": 60, "ref": "#qa"},
    {"id": "langs", "prompt": "LangChain, LangGraph, LangSmith: what's the difference?", "target": "30 seconds", "seconds": 30, "ref": "#qa"},
    {"id": "close", "prompt": "Close the interview.", "target": "20 seconds", "seconds": 20, "ref": "#say-close"},
]

MOCK_HOW = ("Full mocks run in the Claude Code chat. Say **'run the ZenML mock, 25 minutes'**. "
            "Hamza leads on your story, why this move and judgement; Alex goes down on mechanism and what the user sees. "
            "Each mock below starts with the read. Open the conversation to see every turn in one screen: the turns on the left, "
            "and for the one you pick, what they asked and how it landed, what you said, and what to say. Every gap also sits on the Prep tab.")

KITARU_LEAD = ("Kitaru spawns your agent as an ordinary subprocess in your own environment, and an in-process adapter "
               "intercepts the agent framework's tool-execution hook, answering each tool call by a SHA-256 lookup "
               "against a recorded call log. The diagrams are from your teardown; the tables are the mechanisms "
               "they will probe.")

# Your own system, fresh before you walk in: alfred_ as the guide draws it, then set against
# Kitaru. Figures are keys into figures/figures.js; "sd" resolves through extract.js like
# QA_EXTRA. The spoken lines are the guide's alfred_ scripts.
OWN = {
    "tab": "alfred_",
    "kicker": "The system you own",
    "title": "alfred_, fresh in your head",
    "lead": ["They will ask about your day-to-day, and every Kitaru question has an alfred_ answer next to it. "
             "Two loops share one tool layer: an agent the user talks to over SMS, web and MCP, and a background pipeline that acts on mail alone and never sends.",
             "Open one part at a time: the point, the figure, then say it before you open the answer."],
    "parts": [
        {"id": "doors", "title": "Three doors, one brain, one tool package", "meta": "about 45 seconds",
         "point": "SMS, web and MCP converge on packages/tools; the pipeline is its own row; everything is one Supabase project.",
         "figs": ["alfredHld"], "sd": [{"v": "alfred", "a": "hld", "why": "The full high-level design, 23 boxes."}],
         "say": ["Three doors, one brain, one tool package. SMS goes through a webhook and a job queue because the reply can take longer than a webhook should. Web streams directly. MCP runs single tools as the user, behind an allowlist.",
                 "The background pipeline is a separate row: ingestion stages mail, triage decides, the executor and the worker act, notify tells the user, and a reconciler checks the provider afterwards.",
                 "Everything is one Supabase project: Postgres with row-level security, pg_cron for schedules, pgmq for the event bus, and Deno edge functions for compute. That is a deliberate choice for a small team; the trade-off is that one database carries every workload."]},
        {"id": "turn", "title": "One chat turn, in layer order", "meta": "about 40 seconds",
         "point": "Acknowledge fast, then lease, trace, prompt, loop, guard, reply. The layer order is the senior signal.",
         "figs": ["alfredTurn"], "sd": [{"v": "alfred", "a": "dataflow", "why": "The turn and the pipeline, step by step."}],
         "say": ["For chat: acknowledge the webhook, enqueue a job, and let the turn function take a lease on the conversation, open a trace, build a cached prompt, run a bounded loop where every tool call goes through the wrapper stack, then filter tone and send.",
                 "Retries come from three places, so I need three layers: dedupe the webhook, lease the conversation, and key every write. A lock in memory would guard nothing across a provider call."]},
        {"id": "wrap", "title": "What one tool call passes through", "meta": "about 30 seconds",
         "point": "No surface calls execute(). One wrapper stack decides preview, confirmation and replay from what the tool declares; Kitaru's hook sits at the same seam.",
         "figs": ["alfredWrap"], "sd": [{"v": "alfred", "a": "deepdives", "why": "Action safety without a risk score."}],
         "say": ["I do not gate on a risk score. Every tool declares what class of side effect it has, and one wrapper stack around every call decides whether it previews, confirms, or replays. On top of that, the background executor has no send path at all.",
                 "It is the same seam Kitaru's adapter hooks. We execute there; Kitaru answers from the recording there. The difference is that every write we have goes through it, so there is no side door."]},
        {"id": "pipe", "title": "The pipeline acts on mail, and never sends", "meta": "about 40 seconds",
         "point": "Nine steps, two model calls, and only one function that sends, after approval.",
         "figs": ["alfredPipe"], "sd": [{"v": "alfred", "a": "dataflow", "why": "The nine steps, tagged code or model."}],
         "say": ["This is a pipeline, so I will list the steps and mark which ones are model calls. Nine steps, two model calls: triage and drafting. Everything that touches the provider is code.",
                 "Silent actions are archive, label, move. Drafts wait for the user. Sending is a separate function that only runs after approval, and a reconciler verifies every silent effect against the provider afterwards."]},
        {"id": "cost", "title": "Cost is a cache layout", "meta": "about 30 seconds",
         "point": "The shared prefix is about 107k tokens a call, so Block 1 is byte-identical for every user and cached for an hour.",
         "figs": [], "sd": [{"v": "alfred", "a": "deepdives", "why": "The cost dive, with the measured hit rates."}],
         "say": ["Cost is a cache layout problem. The shared prefix is about a hundred thousand tokens, so it has to be byte-identical across users and cached for an hour, with the per-user part in its own slot.",
                 "Measured on the first model call of each turn: 91.4% cached inside five minutes, 62% outside it. A test guards the byte-identical block, because one formatter change broke it on main."]},
        {"id": "quality", "title": "Production failures become eval cases", "meta": "about 30 seconds",
         "point": "The scanner turns real failing turns into cases, and the effects ledger, not the reply text, decides whether an action happened.",
         "figs": ["benchLoop"], "sd": [{"v": "alfred", "a": "deepdives", "why": "The quality-gate dive."}],
         "say": ["For quality, real failing turns get scanned, classified, and promoted into the eval suite, so the regression set is what users actually do.",
                 "Two rules a whiteboard design forgets: a refusal is not an outcome, so check the retry; and the effects ledger, not the assistant's text, decides whether an action happened."]},
        {"id": "ceiling", "title": "The honest ceiling: one Postgres", "meta": "about 20 seconds",
         "point": "Volunteer the limit before they find it, with the signal that would make you split it.",
         "figs": [], "sd": [{"v": "alfred", "a": "deepdives", "why": "One Postgres for everything."}],
         "say": ["It is one Postgres. That is right for this team size, isolated in the schema: partitioned event tables, partial indexes on hot statuses, SKIP LOCKED consumers.",
                 "The day chat latency moves with triage batch size is the day the pipeline gets its own instance."]},
    ],
    "numbers": [
        ["Edge functions", "about 370 Deno functions, about 250 cron registrations, one Postgres"],
        ["Chat volume", "about 310 turns a day fleet-wide, one every 4.6 minutes"],
        ["Prompt prefix", "about 107k cacheable tokens a call; 4 blocks, 3 cache breakpoints"],
        ["Cache hit", "91.4% inside 5 minutes at $0.38 per Mtok; 62% outside it at $1.04"],
        ["Agent loop", "at most 12 steps a turn"],
        ["Pipeline", "9 steps, 2 model calls, 1 send path"],
        ["Accounts", "up to six Gmail, Outlook or IMAP accounts a user"],
    ],
    "compare_figs": ["alfredVsKitaru"],
    "compare": {"head": ["Question", "alfred_", "Kitaru"],
                "rows": [["Where a tool call is caught", "`compose()` around every call; no surface calls execute()", "The adapter hook, on registered function tools only"],
                         ["Default for a write", "Preview, confirm, then an idempotency key", "passthrough: the real tool runs"],
                         ["What proves an action happened", "The `turn_effects` ledger, and a reconciler that checks the provider", "The mocked attribute, absent on passthrough"],
                         ["Retries and repeats", "Event dedupe, a conversation lease, idempotency keys", "An occurrence counter: read, await, then write"],
                         ["Where traces live", "Own tables in Postgres, read by the scanner", "A SessionNode tree, imported from trace stores"],
                         ["Replay for evals", "Real failures replayed against a frozen world", "A cohort replayed from the call log"]]},
    "bridges": [
        {"id": "b-prov", "title": "Provenance: what you would bring from alfred_",
         "point": "The effects ledger is the record Kitaru lacks.",
         "say": ["In alfred_ we never trusted the assistant's text to say an action happened; the effects ledger did. A replay node should carry the same: which policy answered it, and whether anything left the process. That turns the provenance gap into a field."]},
        {"id": "b-writes", "title": "Side effects: why passthrough would not have passed your review",
         "point": "A write is declared as a write, and a fork should fail closed on it.",
         "say": ["Our write tools declare a capability class and carry an idempotency key, so a default that runs the real tool would not have passed review. On a forked replay I would default writes to fail closed, and let a read fall through only if it is marked safe."]},
        {"id": "b-import", "title": "Import: the traces you already have",
         "point": "Your turn traces and tool executions are what Kitaru's importer would ingest; the scanner picks which are worth replaying.",
         "say": ["Our turn traces and tool executions are exactly what an importer would ingest. The part I would keep is the scanner: most traces are not worth replaying, and picking the failing ones is where the value was."]},
    ],
}

# Phrases bolded wherever they appear in what you say: the ideas the interviewer must hear.
EMPHASIS = [
    "frozen snapshot of the user's world", "only the call out to", "Only the provider call is swapped", "the only thing swapped",
    "harness mode", "harness flag", "SQLite snapshot", "twelve failure types", "three out of four", "a little over a hundred cases",
    "twenty-five real instances", "three people named Michael", "path it never took", "tool calls per completed task",
    "multi-turn orchestration", "append-only", "ground truth", "pinning an expected answer", "freezing a world rather than a transcript",
    "freezes the transcript", "froze the world", "fail in opposite directions", "promoted into a small queryable world",
    "a miss is information", "static alias", "shadow", "stamped on the node", "provenance", "the agent's clock isn't",
    "anti-fabrication", "tool-execution record", "tool-execution ledger", "at-least-once", "idempotent", "exactly-once",
    "FOR UPDATE SKIP LOCKED", "CREATE DATABASE ... TEMPLATE", "backstop", "SECURITY DEFINER", "PUBLIC", "row-level security",
    "fidelity", "execution truth", "a framework, a runtime for stateful agents, and the observability-and-eval product",
    "our own tables in Supabase Postgres", "divergence", "I never instrumented it", "estimate", "5,000-plus",
    "WheelPrice", "INFORMS Analytics+", "MockFlow-AI", "MetaRAG", "not looking to urgently leave",
    "Three doors, one brain", "no send path", "three layers", "byte-identical", "effects ledger", "fail closed",
    "no side door", "Volunteer the limit",
]


# Prep tab: what each technical question rests on, so an answer is something to understand
# before it is something to say. Keyed by the start of the question. Figures are keys into
# figures/figures.js; reading URLs are the checked ones in data/reading.js (labels and
# minutes come from there); guide links resolve through extract.js.
QA_EXTRA = {
    "Walk me through your day-to-day": {
        "figs": ["alfredHld"],
        "sd": [{"v": "alfred", "a": "deepdives", "why": "The system you own, drawn from your own code."}]},
    "When you replay a case": {
        "figs": ["harnessSeam"],
        "read": ["https://docs.zenml.io/kitaru/core-concepts/replay"],
        "sd": [{"p": "agent-durability", "t": "env-snapshots", "why": "The frozen world the tools answer from."}]},
    "How long does one case take to author": {
        "figs": ["benchLoop"],
        "read": ["https://hamel.dev/blog/posts/evals/index.html"]},
    "Why SQLite when production is Postgres": {
        "figs": ["sqliteTemplate"],
        "read": ["https://www.postgresql.org/docs/current/manage-ag-templatedbs.html", "https://www.sqlite.org/datatype3.html"],
        "sd": [{"p": "agent-durability", "t": "env-snapshots", "why": "Two ways to give every case its own world."}]},
    "What happens when the production schema changes": {
        "sd": [{"p": "consistency", "t": "event-sourcing", "why": "Append-only is why an old case never moves under you."}]},
    "How do you stop teaching to the test": {
        "figs": ["completeness"],
        "read": ["https://www.sitepen.com/blog/snapshot-testing-benefits-and-drawbacks"],
        "sd": [{"p": "reliability", "t": "monitoring", "why": "A completeness check against ground truth you hold."}]},
    "How do you deal with nondeterminism": {
        "figs": ["passk"],
        "read": ["https://arxiv.org/abs/2406.12045"],
        "sd": [{"p": "agent-safety", "t": "policy-gate", "why": "Why the gating decision is scored, not sampled."}]},
    "A tool the snapshot doesn't cover": {
        "figs": ["harnessSeam", "kitaruPolicy"],
        "sd": [{"v": "kitaru", "a": "deepdives", "why": "Provenance: no silent live calls."}]},
    "What makes a run count as done": {
        "figs": ["completeness"],
        "sd": [{"p": "grounding", "t": "eval-gate", "why": "What a gate asserts before it passes."}]},
    "Four action items, the agent creates three": {
        "figs": ["completeness"]},
    "A better prompt misses every recording": {
        "figs": ["missFlow", "kitaruKey", "zenEffects"],
        "sd": [{"v": "kitaru", "a": "deepdives", "why": "Divergence: the better the change, the worse the replay."}]},
    "The customer says the two searches are the same": {
        "figs": ["missFlow"],
        "sd": [{"v": "kitaru", "a": "deepdives", "why": "The productive miss, as a design option."}]},
    "How do you know the judge is still right": {
        "figs": ["passk"],
        "read": ["https://eugeneyan.com/writing/llm-evaluators/"],
        "sd": [{"p": "grounding", "t": "shadow-online", "why": "The signals the judge sits on, and why they drift."}]},
    "How do you decide what becomes an eval case": {
        "figs": ["benchLoop"],
        "read": ["https://hamel.dev/blog/posts/evals/index.html"],
        "sd": [{"p": "grounding", "t": "eval-gate", "why": "What the cases become once they are in."}]},
    "What doesn't the bench catch": {
        "figs": ["completeness"],
        "read": ["https://www.anthropic.com/engineering/demystifying-evals-for-ai-agents"]},
    "Was it gating deploys": {
        "sd": [{"p": "grounding", "t": "eval-gate", "why": "Eval suites as release gates, and what a hard gate costs."}]},
    "A side-effecting tool call fails halfway": {
        "figs": ["zenEffects", "alfredWrap"],
        "read": ["https://stripe.com/blog/idempotency", "https://brandur.org/idempotency-keys"],
        "sd": [{"p": "multi-step", "t": "idempotency", "why": "Where the key lives decides whether a retry is safe."},
               {"p": "agent-durability", "t": "unknown-results", "why": "The send succeeded but the response timed out."}]},
    "Tell me about the queue": {
        "figs": ["skipLocked"],
        "read": ["https://www.postgresql.org/docs/current/sql-select.html", "https://www.crunchydata.com/blog/message-queuing-using-native-postgresql"],
        "sd": [{"p": "contention", "t": "claim-skip-locked", "why": "The idiom to name."},
               {"p": "real-time", "t": "polling", "why": "Why a cron drain's worst case is its interval."}]},
    "Hardest bug you've debugged": {
        "figs": ["definerGrant"],
        "read": ["https://www.postgresql.org/docs/current/sql-createfunction.html", "https://supabase.com/docs/guides/database/postgres/row-level-security"],
        "sd": [{"p": "agent-safety", "t": "least-privilege", "why": "Least privilege failing by default."}]},
    "How do you normalise Gmail, Outlook and IMAP": {
        "read": ["https://developers.google.com/workspace/gmail/api/guides/sync", "https://learn.microsoft.com/en-us/graph/delta-query-messages"],
        "sd": [{"v": "email-agent", "a": "hld", "why": "The providers behind one model."}]},
    "What's the difference between LangChain, LangGraph and LangSmith": {
        "sd": [{"p": "agent-durability", "t": "transcript-checkpoint", "why": "What LangGraph's checkpointers are, in the guide's terms."}]},
    "What's your experience with trace stores": {
        "figs": ["kitaruModel", "alfredVsKitaru"],
        "sd": [{"v": "kitaru", "a": "hld", "why": "Where imported traces land in Kitaru."}]},
    "What's hard about replay": {
        "figs": ["forkReplay", "kitaruKey", "kitaruFreeze"],
        "read": ["https://docs.temporal.io/workflow-execution"],
        "sd": [{"v": "kitaru", "a": "deepdives", "why": "Divergence, drawn for both designs."}]},
    "Multi-turn: the agent's reply changes at turn two": {
        "figs": ["kitaruTurns", "multiturn"],
        "read": ["https://arxiv.org/abs/2406.12045"],
        "sd": [{"v": "kitaru", "a": "deepdives", "why": "Multi-turn replay is one of the deep dives."}]},
    "If you ran Kitaru for a quarter": {
        "figs": ["missFlow", "kitaruLive"],
        "sd": [{"v": "kitaru", "a": "deepdives", "why": "Provenance and misses, as design problems."}]},
}
